/**
 * AI Agents Library Data
 * Specialized agents that Founders can deploy to automate various business functions
 */

export type AgentCategory =
  | 'engineering'
  | 'product'
  | 'marketing'
  | 'design'
  | 'project-management'
  | 'studio-operations'
  | 'testing';

export interface AIAgent {
  id: string;
  name: string;
  category: AgentCategory;
  description: string;
  expertise: string[];
  tools: string[];
  outputFormat: string;
  approvalRequired: boolean;
  estimatedCostPerTask: string;
  icon: string; // lucide-react-native icon name
}

export const AI_AGENTS: AIAgent[] = [
  // Engineering Agents
  {
    id: 'frontend-developer',
    name: 'Frontend Developer',
    category: 'engineering',
    description: 'Expert in React, React Native, and TypeScript UI development. Builds responsive, accessible interfaces with modern design systems.',
    expertise: ['React', 'React Native', 'TypeScript', 'Component Libraries', 'Responsive Design'],
    tools: ['Code Editor', 'Component Preview', 'Design Systems', 'Browser DevTools'],
    outputFormat: 'Production-ready code with documentation',
    approvalRequired: false,
    estimatedCostPerTask: '£0.50 - £2.00',
    icon: 'Code2',
  },
  {
    id: 'backend-architect',
    name: 'Backend Architect',
    category: 'engineering',
    description: 'Designs scalable APIs, optimizes databases, and implements serverless architecture patterns for high-performance systems.',
    expertise: ['API Design', 'Database Optimization', 'Serverless', 'Microservices', 'Security'],
    tools: ['AWS/Azure', 'Database Tools', 'API Testing', 'Performance Monitoring'],
    outputFormat: 'Architecture diagrams and implementation code',
    approvalRequired: true,
    estimatedCostPerTask: '£1.00 - £5.00',
    icon: 'Database',
  },
  {
    id: 'mobile-app-builder',
    name: 'Mobile App Builder',
    category: 'engineering',
    description: 'Specializes in iOS and Android app development using Expo and React Native. Creates native-feeling mobile experiences.',
    expertise: ['iOS Development', 'Android Development', 'Expo SDK', 'App Store Submission', 'Mobile UX'],
    tools: ['Expo', 'React Native', 'Native Modules', 'App Store Connect'],
    outputFormat: 'Deployable mobile applications',
    approvalRequired: false,
    estimatedCostPerTask: '£1.00 - £3.00',
    icon: 'Smartphone',
  },
  {
    id: 'ai-engineer',
    name: 'AI Engineer',
    category: 'engineering',
    description: 'Integrates LLMs, builds RAG systems, creates embeddings, and implements intelligent features using cutting-edge AI.',
    expertise: ['LLM Integration', 'RAG Systems', 'Embeddings', 'Prompt Engineering', 'AI APIs'],
    tools: ['OpenAI', 'Anthropic', 'Vector Databases', 'LangChain'],
    outputFormat: 'AI-powered features with API integrations',
    approvalRequired: true,
    estimatedCostPerTask: '£2.00 - £8.00',
    icon: 'Brain',
  },
  {
    id: 'devops-automator',
    name: 'DevOps Automator',
    category: 'engineering',
    description: 'Automates CI/CD pipelines, manages infrastructure as code, and sets up monitoring and alerting systems.',
    expertise: ['CI/CD', 'Infrastructure as Code', 'Docker', 'Kubernetes', 'Monitoring'],
    tools: ['GitHub Actions', 'Terraform', 'AWS', 'DataDog', 'PagerDuty'],
    outputFormat: 'Automated deployment pipelines and configs',
    approvalRequired: true,
    estimatedCostPerTask: '£1.50 - £4.00',
    icon: 'GitBranch',
  },
  {
    id: 'rapid-prototyper',
    name: 'Rapid Prototyper',
    category: 'engineering',
    description: 'Quickly builds MVPs and proof-of-concept applications to validate ideas and test market fit before full development.',
    expertise: ['Rapid Development', 'MVP Creation', 'No-Code Tools', 'API Mocking', 'Quick Validation'],
    tools: ['Expo', 'Supabase', 'Vercel', 'Figma', 'API Mocking Tools'],
    outputFormat: 'Working prototypes and demos',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.50',
    icon: 'Zap',
  },

  // Product Agents
  {
    id: 'trend-researcher',
    name: 'Trend Researcher',
    category: 'product',
    description: 'Analyzes market trends, tracks competitors, and provides actionable intelligence on industry movements and opportunities.',
    expertise: ['Market Analysis', 'Competitive Intelligence', 'Industry Research', 'Trend Forecasting'],
    tools: ['Web Search', 'Analytics Platforms', 'Social Listening', 'Industry Reports'],
    outputFormat: 'Research reports with actionable insights',
    approvalRequired: false,
    estimatedCostPerTask: '£0.50 - £1.50',
    icon: 'TrendingUp',
  },
  {
    id: 'feedback-synthesizer',
    name: 'Feedback Synthesizer',
    category: 'product',
    description: 'Analyzes customer feedback from multiple sources, identifies patterns, and prioritizes feature requests based on impact.',
    expertise: ['Feedback Analysis', 'Sentiment Analysis', 'Priority Scoring', 'User Research'],
    tools: ['Analytics', 'Support Tickets', 'Reviews', 'Surveys', 'Social Media'],
    outputFormat: 'Prioritized feature roadmap with customer insights',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.00',
    icon: 'MessageSquare',
  },
  {
    id: 'sprint-prioritizer',
    name: 'Sprint Prioritizer',
    category: 'product',
    description: 'Manages product backlogs, prioritizes sprint work using impact/effort matrices, and optimizes team velocity.',
    expertise: ['Backlog Management', 'Sprint Planning', 'Priority Scoring', 'Velocity Optimization'],
    tools: ['Jira Integration', 'Linear', 'GitHub Projects', 'Analytics'],
    outputFormat: 'Prioritized sprint plans with rationale',
    approvalRequired: false,
    estimatedCostPerTask: '£0.50 - £1.50',
    icon: 'ListOrdered',
  },

  // Marketing Agents
  {
    id: 'tiktok-strategist',
    name: 'TikTok Strategist',
    category: 'marketing',
    description: 'Creates viral content strategies specifically for hardware startups, leveraging TikTok trends and algorithm insights.',
    expertise: ['Viral Strategy', 'TikTok Trends', 'Hardware Marketing', 'Content Planning', 'Engagement Growth'],
    tools: ['TikTok Analytics', 'Trend Monitoring', 'Video Editing', 'Hashtag Research'],
    outputFormat: 'Content calendar with viral hooks and scripts',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.00',
    icon: 'Video',
  },
  {
    id: 'instagram-curator',
    name: 'Instagram Curator',
    category: 'marketing',
    description: 'Plans visual content, optimizes posting schedules, and builds engagement through Instagram stories, reels, and posts.',
    expertise: ['Visual Content', 'Instagram Strategy', 'Reels', 'Stories', 'Engagement'],
    tools: ['Instagram Analytics', 'Canva', 'Scheduling Tools', 'Hashtag Analytics'],
    outputFormat: 'Visual content calendar with post designs',
    approvalRequired: false,
    estimatedCostPerTask: '£0.60 - £1.80',
    icon: 'Image',
  },
  {
    id: 'twitter-engager',
    name: 'Twitter Engager',
    category: 'marketing',
    description: 'Builds Tech Twitter presence, engages with communities, and creates thought leadership content for founders.',
    expertise: ['Twitter Strategy', 'Community Building', 'Tech Twitter', 'Thought Leadership'],
    tools: ['Twitter Analytics', 'Thread Planning', 'Engagement Tools', 'Trend Monitoring'],
    outputFormat: 'Tweet threads and engagement strategy',
    approvalRequired: false,
    estimatedCostPerTask: '£0.40 - £1.20',
    icon: 'Twitter',
  },
  {
    id: 'reddit-community-builder',
    name: 'Reddit Community Builder',
    category: 'marketing',
    description: 'Engages authentically with relevant subreddits, builds community trust, and drives organic growth through Reddit.',
    expertise: ['Reddit Strategy', 'Community Engagement', 'Authentic Marketing', 'Subreddit Growth'],
    tools: ['Reddit Analytics', 'Subreddit Research', 'Engagement Monitoring'],
    outputFormat: 'Community engagement plan with post schedule',
    approvalRequired: true,
    estimatedCostPerTask: '£0.50 - £1.50',
    icon: 'Users',
  },
  {
    id: 'app-store-optimizer',
    name: 'App Store Optimizer',
    category: 'marketing',
    description: 'Optimizes ASO keywords, improves app store listings, analyzes conversion rates, and increases organic downloads.',
    expertise: ['ASO', 'Keyword Research', 'Conversion Optimization', 'A/B Testing', 'App Store Strategy'],
    tools: ['App Store Analytics', 'Keyword Tools', 'A/B Testing', 'Competitor Analysis'],
    outputFormat: 'Optimized app store listing with keyword strategy',
    approvalRequired: false,
    estimatedCostPerTask: '£1.00 - £3.00',
    icon: 'Store',
  },
  {
    id: 'content-creator',
    name: 'Content Creator',
    category: 'marketing',
    description: 'Writes engaging blog posts, technical documentation, and landing pages optimized for SEO and conversions.',
    expertise: ['Content Writing', 'SEO', 'Technical Writing', 'Copywriting', 'Documentation'],
    tools: ['CMS', 'SEO Tools', 'Grammar Checkers', 'Analytics'],
    outputFormat: 'Polished content ready to publish',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.50',
    icon: 'FileText',
  },
  {
    id: 'growth-hacker',
    name: 'Growth Hacker',
    category: 'marketing',
    description: 'Designs viral loops, builds referral systems, and creates acquisition strategies for rapid user growth.',
    expertise: ['Growth Hacking', 'Viral Loops', 'Referral Systems', 'Acquisition Funnels', 'Metrics Analysis'],
    tools: ['Analytics', 'A/B Testing', 'Attribution Tools', 'Automation Platforms'],
    outputFormat: 'Growth strategy with implementation plan',
    approvalRequired: true,
    estimatedCostPerTask: '£1.50 - £4.00',
    icon: 'Rocket',
  },

  // Design Agents
  {
    id: 'ui-designer',
    name: 'UI Designer',
    category: 'design',
    description: 'Creates beautiful interfaces, builds component libraries, and ensures consistent design systems across products.',
    expertise: ['UI Design', 'Component Libraries', 'Design Systems', 'Figma', 'Mobile Design'],
    tools: ['Figma', 'Design Tokens', 'Component Libraries', 'Prototyping'],
    outputFormat: 'Figma designs with component library',
    approvalRequired: false,
    estimatedCostPerTask: '£1.00 - £3.50',
    icon: 'Palette',
  },
  {
    id: 'ux-researcher',
    name: 'UX Researcher',
    category: 'design',
    description: 'Conducts user research, performs usability testing, and provides data-driven recommendations for UX improvements.',
    expertise: ['User Research', 'Usability Testing', 'User Interviews', 'Journey Mapping', 'Heuristic Analysis'],
    tools: ['User Testing Platforms', 'Analytics', 'Survey Tools', 'Session Recording'],
    outputFormat: 'Research reports with actionable recommendations',
    approvalRequired: false,
    estimatedCostPerTask: '£1.50 - £4.00',
    icon: 'Search',
  },
  {
    id: 'brand-guardian',
    name: 'Brand Guardian',
    category: 'design',
    description: 'Ensures brand consistency across all touchpoints, maintains design systems, and protects brand identity.',
    expertise: ['Brand Guidelines', 'Design Systems', 'Consistency Audits', 'Brand Strategy'],
    tools: ['Figma', 'Style Guides', 'Asset Management', 'Brand Tools'],
    outputFormat: 'Brand guidelines and audit reports',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.00',
    icon: 'Shield',
  },
  {
    id: 'visual-storyteller',
    name: 'Visual Storyteller',
    category: 'design',
    description: 'Crafts compelling product narratives through visuals, creates marketing materials, and designs pitch decks.',
    expertise: ['Visual Storytelling', 'Marketing Design', 'Pitch Decks', 'Infographics', 'Brand Narratives'],
    tools: ['Figma', 'Illustrator', 'Motion Graphics', 'Presentation Tools'],
    outputFormat: 'Visual narratives and marketing materials',
    approvalRequired: false,
    estimatedCostPerTask: '£1.25 - £3.50',
    icon: 'Sparkles',
  },
  {
    id: 'whimsy-injector',
    name: 'Whimsy Injector',
    category: 'design',
    description: 'Adds delightful micro-interactions, animations, and personality to products that make users smile.',
    expertise: ['Micro-interactions', 'Animations', 'Delight Design', 'Motion Design', 'Personality'],
    tools: ['Animation Libraries', 'Motion Design', 'Lottie', 'React Spring'],
    outputFormat: 'Animated prototypes and implementation code',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.50',
    icon: 'Wand2',
  },

  // Project Management Agents
  {
    id: 'experiment-tracker',
    name: 'Experiment Tracker',
    category: 'project-management',
    description: 'Manages A/B tests, tracks feature flags, maintains learning logs, and measures experiment outcomes.',
    expertise: ['A/B Testing', 'Feature Flags', 'Experiment Design', 'Metrics Tracking', 'Learning Logs'],
    tools: ['Feature Flag Platforms', 'Analytics', 'Experiment Tools', 'Statistical Analysis'],
    outputFormat: 'Experiment plans and results summaries',
    approvalRequired: false,
    estimatedCostPerTask: '£0.60 - £1.80',
    icon: 'FlaskConical',
  },
  {
    id: 'project-shipper',
    name: 'Project Shipper',
    category: 'project-management',
    description: 'Manages releases, coordinates launches, creates go-to-market plans, and ensures smooth product shipping.',
    expertise: ['Release Management', 'Launch Coordination', 'GTM Strategy', 'Stakeholder Communication'],
    tools: ['Project Management', 'Release Tools', 'Communication Platforms', 'Checklists'],
    outputFormat: 'Launch plans with timelines and checklists',
    approvalRequired: true,
    estimatedCostPerTask: '£1.00 - £3.00',
    icon: 'Ship',
  },
  {
    id: 'studio-producer',
    name: 'Studio Producer',
    category: 'project-management',
    description: 'Orchestrates cross-functional projects, manages dependencies, and ensures teams stay aligned and productive.',
    expertise: ['Project Orchestration', 'Cross-functional Leadership', 'Dependency Management', 'Team Coordination'],
    tools: ['Project Management', 'Gantt Charts', 'Resource Planning', 'Communication Tools'],
    outputFormat: 'Project plans with resource allocation',
    approvalRequired: true,
    estimatedCostPerTask: '£1.25 - £3.50',
    icon: 'Clapperboard',
  },

  // Studio Operations Agents
  {
    id: 'support-responder',
    name: 'Support Responder',
    category: 'studio-operations',
    description: 'Automates customer support responses, handles common queries, and escalates complex issues to humans.',
    expertise: ['Customer Support', 'Ticket Management', 'Response Automation', 'Issue Classification'],
    tools: ['Support Platforms', 'Ticket Systems', 'Knowledge Base', 'Chat Tools'],
    outputFormat: 'Support responses and ticket summaries',
    approvalRequired: false,
    estimatedCostPerTask: '£0.20 - £0.60',
    icon: 'Headphones',
  },
  {
    id: 'analytics-reporter',
    name: 'Analytics Reporter',
    category: 'studio-operations',
    description: 'Creates metrics dashboards, generates insights from data, and automates regular reporting for stakeholders.',
    expertise: ['Data Analysis', 'Dashboard Creation', 'Insight Generation', 'Reporting Automation'],
    tools: ['Analytics Platforms', 'BI Tools', 'SQL', 'Visualization Tools'],
    outputFormat: 'Automated reports and dashboards',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.50',
    icon: 'BarChart3',
  },
  {
    id: 'infrastructure-maintainer',
    name: 'Infrastructure Maintainer',
    category: 'studio-operations',
    description: 'Monitors system health, performs maintenance tasks, optimizes performance, and prevents downtime.',
    expertise: ['System Monitoring', 'Performance Optimization', 'Preventive Maintenance', 'Incident Response'],
    tools: ['Monitoring Tools', 'APM', 'Log Aggregation', 'Alert Systems'],
    outputFormat: 'Health reports and maintenance logs',
    approvalRequired: true,
    estimatedCostPerTask: '£0.50 - £2.00',
    icon: 'Server',
  },
  {
    id: 'legal-compliance-checker',
    name: 'Legal Compliance Checker',
    category: 'studio-operations',
    description: 'Validates GDPR compliance, reviews privacy policies, checks terms of service, and ensures legal requirements are met.',
    expertise: ['GDPR', 'Privacy Compliance', 'Terms Review', 'Legal Documentation', 'Data Protection'],
    tools: ['Compliance Tools', 'Document Review', 'Policy Templates', 'Audit Systems'],
    outputFormat: 'Compliance reports and recommendations',
    approvalRequired: true,
    estimatedCostPerTask: '£1.50 - £5.00',
    icon: 'Scale',
  },
  {
    id: 'finance-tracker',
    name: 'Finance Tracker',
    category: 'studio-operations',
    description: 'Categorizes expenses, monitors budgets, tracks burn rate, and provides financial health insights.',
    expertise: ['Expense Categorization', 'Budget Monitoring', 'Financial Reporting', 'Burn Rate Analysis'],
    tools: ['Accounting Software', 'Bank Integrations', 'Receipt Scanning', 'Financial Dashboards'],
    outputFormat: 'Financial reports and budget alerts',
    approvalRequired: false,
    estimatedCostPerTask: '£0.50 - £1.50',
    icon: 'PiggyBank',
  },

  // Testing Agents
  {
    id: 'tool-evaluator',
    name: 'Tool Evaluator',
    category: 'testing',
    description: 'Assesses software vendors, compares tools, evaluates pricing, and provides recommendations for tech stack decisions.',
    expertise: ['Vendor Assessment', 'Tool Comparison', 'Cost Analysis', 'Integration Evaluation'],
    tools: ['Product Reviews', 'Demo Access', 'Integration Testing', 'Cost Calculators'],
    outputFormat: 'Evaluation reports with recommendations',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.50',
    icon: 'Wrench',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    category: 'testing',
    description: 'Tests API endpoints, validates integrations, checks error handling, and ensures API reliability.',
    expertise: ['API Testing', 'Integration Testing', 'Error Validation', 'Performance Testing'],
    tools: ['Postman', 'API Testing Tools', 'Monitoring', 'Load Testing'],
    outputFormat: 'Test reports with coverage metrics',
    approvalRequired: false,
    estimatedCostPerTask: '£0.50 - £1.50',
    icon: 'Plug',
  },
  {
    id: 'workflow-optimizer',
    name: 'Workflow Optimizer',
    category: 'testing',
    description: 'Analyzes processes, identifies bottlenecks, suggests improvements, and automates repetitive workflows.',
    expertise: ['Process Analysis', 'Bottleneck Identification', 'Workflow Automation', 'Efficiency Optimization'],
    tools: ['Process Mapping', 'Analytics', 'Automation Tools', 'Workflow Software'],
    outputFormat: 'Optimization recommendations with implementation plans',
    approvalRequired: false,
    estimatedCostPerTask: '£1.00 - £3.00',
    icon: 'GitMerge',
  },
  {
    id: 'performance-benchmarker',
    name: 'Performance Benchmarker',
    category: 'testing',
    description: 'Tests speed and efficiency, runs benchmarks, identifies performance bottlenecks, and provides optimization recommendations.',
    expertise: ['Performance Testing', 'Benchmarking', 'Load Testing', 'Optimization Analysis'],
    tools: ['Lighthouse', 'Load Testing Tools', 'Profilers', 'Monitoring Platforms'],
    outputFormat: 'Performance reports with optimization suggestions',
    approvalRequired: false,
    estimatedCostPerTask: '£0.75 - £2.50',
    icon: 'Gauge',
  },
  {
    id: 'test-results-analyzer',
    name: 'Test Results Analyzer',
    category: 'testing',
    description: 'Synthesizes QA reports, identifies patterns in bugs, prioritizes fixes, and tracks testing coverage.',
    expertise: ['QA Analysis', 'Bug Triage', 'Test Coverage', 'Quality Metrics', 'Pattern Recognition'],
    tools: ['Test Management', 'Bug Tracking', 'Coverage Tools', 'Analytics'],
    outputFormat: 'QA summaries with prioritized action items',
    approvalRequired: false,
    estimatedCostPerTask: '£0.50 - £1.50',
    icon: 'ClipboardCheck',
  },
];

export const AGENT_CATEGORIES = [
  { id: 'engineering', name: 'Engineering', icon: 'Code2', color: 'blue' },
  { id: 'product', name: 'Product', icon: 'Package', color: 'purple' },
  { id: 'marketing', name: 'Marketing', icon: 'Megaphone', color: 'pink' },
  { id: 'design', name: 'Design', icon: 'Palette', color: 'orange' },
  { id: 'project-management', name: 'Project Management', icon: 'Kanban', color: 'green' },
  { id: 'studio-operations', name: 'Studio Operations', icon: 'Building2', color: 'slate' },
  { id: 'testing', name: 'Testing', icon: 'TestTube2', color: 'cyan' },
] as const;

export function getAgentsByCategory(category: AgentCategory): AIAgent[] {
  return AI_AGENTS.filter(agent => agent.category === category);
}

export function getCategoryColor(category: AgentCategory): { bg: string; text: string; border: string; hex: string } {
  const colors = {
    engineering: { bg: 'bg-blue-500/20', text: 'text-blue-400', border: 'border-blue-500/30', hex: '#60a5fa' },
    product: { bg: 'bg-purple-500/20', text: 'text-purple-400', border: 'border-purple-500/30', hex: '#a78bfa' },
    marketing: { bg: 'bg-pink-500/20', text: 'text-pink-400', border: 'border-pink-500/30', hex: '#f472b6' },
    design: { bg: 'bg-orange-500/20', text: 'text-orange-400', border: 'border-orange-500/30', hex: '#fb923c' },
    'project-management': { bg: 'bg-green-500/20', text: 'text-green-400', border: 'border-green-500/30', hex: '#4ade80' },
    'studio-operations': { bg: 'bg-slate-500/20', text: 'text-slate-400', border: 'border-slate-500/30', hex: '#94a3b8' },
    testing: { bg: 'bg-cyan-500/20', text: 'text-cyan-400', border: 'border-cyan-500/30', hex: '#22d3ee' },
  };
  return colors[category];
}
