import type { Role, Function as BusinessFunction } from '@/types';
import { generateExecutives, generateApprentices } from './generate-candidates';

export interface Candidate {
  id: string;
  name: string;
  role: Role;
  specialization: BusinessFunction[];
  rating: number;
  experience: number; // years
  costPerDay: number; // GBP
  availability: string;
  bio: string;
  skills: string[];
  previousCompanies: string[];
  avatarColor: string;
  education?: string;
  certifications?: string[];
  achievements?: string[];
  location: string;
  email: string;
  phone: string;
  linkedIn?: string;
}

// First 30 handcrafted executive profiles (keeping existing high-quality data)
const baseExecutives: Candidate[] = [
  {
    id: 'exec-1',
    name: 'Sarah Mitchell',
    role: 'FractionalExec',
    specialization: ['Sales', 'Marketing'],
    rating: 4.9,
    experience: 15,
    costPerDay: 850,
    availability: 'Available Now',
    bio: 'Former VP of Sales at SaaS unicorn. Expert in building high-performing sales teams and scaling revenue operations.',
    skills: ['B2B Sales', 'Revenue Operations', 'Team Building', 'CRM Strategy'],
    previousCompanies: ['Salesforce', 'HubSpot', 'Stripe'],
    avatarColor: '#3b82f6',
    location: 'London, UK',
    email: 'sarah.mitchell@fractional.com',
    phone: '+44 7700 900401',
    education: 'MBA, London Business School',
    certifications: ['Salesforce Certified', 'Revenue Architecture Certified'],
    achievements: ['Scaled revenue from £2M to £50M ARR', 'Built 40+ person sales team', 'Closed 15 enterprise deals >£1M'],
    linkedIn: 'linkedin.com/in/sarahmitchell',
  },
  {
    id: 'exec-2',
    name: 'James Chen',
    role: 'FractionalExec',
    specialization: ['Finance', 'Ops'],
    rating: 4.8,
    experience: 18,
    costPerDay: 950,
    availability: 'Available from Feb 1',
    bio: 'Ex-CFO with extensive experience in fundraising, financial modeling, and operational efficiency for tech startups.',
    skills: ['Financial Planning', 'Fundraising', 'Unit Economics', 'Cash Flow Management'],
    previousCompanies: ['Revolut', 'TransferWise', 'Monzo'],
    avatarColor: '#10b981',
    location: 'Manchester, UK',
    email: 'james.chen@fractional.com',
    phone: '+44 7700 900402',
    education: 'BSc Economics, Oxford University; ACA Qualified',
    certifications: ['Chartered Accountant (ACA)', 'FP&A Certified'],
    achievements: ['Raised £120M Series B', 'Reduced burn rate by 45%', 'Led 3 successful exits'],
    linkedIn: 'linkedin.com/in/jameschen',
  },
  {
    id: 'exec-3',
    name: 'Priya Sharma',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.7,
    experience: 12,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Growth marketing specialist with proven track record in scaling startups from 0 to 10M ARR through data-driven campaigns.',
    skills: ['Growth Marketing', 'SEO/SEM', 'Content Strategy', 'Analytics'],
    previousCompanies: ['Notion', 'Airtable', 'Figma'],
    avatarColor: '#f59e0b',
    location: 'Bristol, UK',
    email: 'priya.sharma@fractional.com',
    phone: '+44 7700 900403',
    education: 'BA Marketing, University of Warwick',
    certifications: ['Google Analytics Certified', 'HubSpot Inbound Certified'],
    achievements: ['Generated £50M+ pipeline', '300% increase in organic traffic', 'Launched 12 successful product launches'],
    linkedIn: 'linkedin.com/in/priyasharma',
  },
  {
    id: 'exec-4',
    name: 'Marcus Rodriguez',
    role: 'FractionalExec',
    specialization: ['Engineering', 'Ops'],
    rating: 4.9,
    experience: 20,
    costPerDay: 1100,
    availability: 'Available from Jan 20',
    bio: 'Former CTO at multiple successful startups. Specializes in technical architecture, team scaling, and engineering culture.',
    skills: ['System Architecture', 'Team Leadership', 'DevOps', 'Technical Strategy'],
    previousCompanies: ['Uber', 'Airbnb', 'Dropbox'],
    avatarColor: '#8b5cf6',
    location: 'Cambridge, UK',
    email: 'marcus.rodriguez@fractional.com',
    phone: '+44 7700 900404',
    education: 'MEng Computer Science, Imperial College London',
    certifications: ['AWS Solutions Architect', 'Kubernetes Certified'],
    achievements: ['Built systems serving 100M+ users', 'Scaled team from 5 to 80 engineers', 'Reduced infrastructure costs by 60%'],
    linkedIn: 'linkedin.com/in/marcusrodriguez',
  },
  {
    id: 'exec-5',
    name: 'Emma Thompson',
    role: 'FractionalExec',
    specialization: ['Sales'],
    rating: 4.6,
    experience: 10,
    costPerDay: 700,
    availability: 'Available Now',
    bio: 'Enterprise sales expert with experience closing 7-figure deals. Specialized in building sales playbooks and processes.',
    skills: ['Enterprise Sales', 'Deal Strategy', 'Sales Enablement', 'Customer Success'],
    previousCompanies: ['Oracle', 'SAP', 'ServiceNow'],
    avatarColor: '#ec4899',
    location: 'Edinburgh, UK',
    email: 'emma.thompson@fractional.com',
    phone: '+44 7700 900405',
    education: 'BA Business Studies, Durham University',
    certifications: ['MEDDIC Sales Certified', 'Challenger Sales Certified'],
    achievements: ['Closed £45M in enterprise deals', 'Built sales playbook used by 100+ reps', 'Avg deal size £850K'],
    linkedIn: 'linkedin.com/in/emmathompson',
  },
  {
    id: 'exec-6',
    name: 'David Kim',
    role: 'FractionalExec',
    specialization: ['Finance'],
    rating: 4.8,
    experience: 16,
    costPerDay: 900,
    availability: 'Available from Jan 25',
    bio: 'Investment banking background with deep expertise in M&A, valuations, and strategic financial planning for scale-ups.',
    skills: ['M&A', 'Valuation', 'Strategic Planning', 'Investor Relations'],
    previousCompanies: ['Goldman Sachs', 'J.P. Morgan', 'Revolut'],
    avatarColor: '#06b6d4',
    location: 'London, UK',
    email: 'david.kim@fractional.com',
    phone: '+44 7700 900406',
    education: 'MSc Finance, LSE; BA Economics, Cambridge',
    certifications: ['CFA Charterholder', 'M&A Certified'],
    achievements: ['Advised on £2B+ M&A transactions', 'Led 8 successful fundraises', 'Built valuation models for 50+ startups'],
    linkedIn: 'linkedin.com/in/davidkim',
  },
  {
    id: 'exec-7',
    name: 'Olivia Martinez',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Sales'],
    rating: 4.7,
    experience: 14,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Integrated marketing and sales strategist. Built demand gen engines that generated $50M+ pipeline for B2B companies.',
    skills: ['Demand Generation', 'ABM', 'Marketing Automation', 'Sales Alignment'],
    previousCompanies: ['Gong', 'Drift', 'Outreach'],
    avatarColor: '#14b8a6',
    location: 'Birmingham, UK',
    email: 'olivia.martinez@fractional.com',
    phone: '+44 7700 900407',
    education: 'MBA, INSEAD; BSc Marketing, Nottingham',
    certifications: ['Marketo Certified', 'Demandbase ABM Certified'],
    achievements: ['Generated £80M pipeline', '45% sales-marketing alignment improvement', 'Launched ABM program with 200% ROI'],
    linkedIn: 'linkedin.com/in/oliviamartinez',
  },
  {
    id: 'exec-8',
    name: 'Thomas Anderson',
    role: 'FractionalExec',
    specialization: ['Ops'],
    rating: 4.9,
    experience: 17,
    costPerDay: 850,
    availability: 'Available from Feb 5',
    bio: 'Operations excellence expert. Led operational transformations at hyper-growth companies, improving efficiency by 40%+.',
    skills: ['Process Optimization', 'Supply Chain', 'Project Management', 'Lean Six Sigma'],
    previousCompanies: ['Amazon', 'Tesla', 'Deliveroo'],
    avatarColor: '#f97316',
    location: 'Leeds, UK',
    email: 'thomas.anderson@fractional.com',
    phone: '+44 7700 900408',
    education: 'MSc Operations Management, Warwick; BEng Manufacturing',
    certifications: ['Lean Six Sigma Black Belt', 'PMP Certified'],
    achievements: ['Reduced operational costs by £12M annually', 'Implemented ERP across 8 locations', '99.5% on-time delivery rate'],
    linkedIn: 'linkedin.com/in/thomasanderson',
  },
  {
    id: 'exec-9',
    name: 'Sophia Patel',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 11,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Brand and product marketing specialist. Launched 20+ products with combined $500M+ in revenue impact.',
    skills: ['Product Marketing', 'Brand Strategy', 'Go-to-Market', 'Positioning'],
    previousCompanies: ['Apple', 'Google', 'Spotify'],
    avatarColor: '#ef4444',
    location: 'Oxford, UK',
    email: 'sophia.patel@fractional.com',
    phone: '+44 7700 900409',
    education: 'BA Communications, Kings College London',
    certifications: ['Product Marketing Certified', 'Pragmatic Marketing Certified'],
    achievements: ['Launched products generating £200M revenue', 'Created brand strategy for unicorn startup', 'Led repositioning for 500% growth'],
    linkedIn: 'linkedin.com/in/sophiapatel',
  },
  {
    id: 'exec-10',
    name: 'Robert Zhang',
    role: 'FractionalExec',
    specialization: ['Engineering'],
    rating: 4.7,
    experience: 19,
    costPerDay: 1000,
    availability: 'Available from Jan 30',
    bio: 'Platform engineering leader. Built infrastructure supporting billions of daily requests at major tech companies.',
    skills: ['Platform Engineering', 'Cloud Architecture', 'Scalability', 'Security'],
    previousCompanies: ['Netflix', 'Twitter', 'LinkedIn'],
    avatarColor: '#a855f7',
    location: 'London, UK',
    email: 'robert.zhang@fractional.com',
    phone: '+44 7700 900410',
    education: 'PhD Computer Science, MIT; BSc CS, Stanford',
    certifications: ['AWS Certified Solutions Architect', 'CISSP Certified'],
    achievements: ['Built platform serving 500M users', 'Reduced latency by 75%', 'Published 12 technical papers'],
    linkedIn: 'linkedin.com/in/robertzhang',
  },
  {
    id: 'exec-11',
    name: 'Isabella Romano',
    role: 'FractionalExec',
    specialization: ['Finance', 'Ops'],
    rating: 4.9,
    experience: 13,
    costPerDay: 850,
    availability: 'Available Now',
    bio: 'FP&A and operations leader. Helped 15+ startups optimize burn rate and extend runway during difficult market conditions.',
    skills: ['FP&A', 'Scenario Planning', 'Cost Optimization', 'KPI Frameworks'],
    previousCompanies: ['Meta', 'Snap', 'Pinterest'],
    avatarColor: '#84cc16',
    location: 'Glasgow, UK',
    email: 'isabella.romano@fractional.com',
    phone: '+44 7700 900411',
    education: 'MSc Finance, Cass Business School; ACCA Qualified',
    certifications: ['ACCA Qualified', 'FP&A Certified Professional'],
    achievements: ['Extended runway by avg 18 months for clients', 'Implemented FP&A systems for 20+ companies', 'Reduced overhead costs by 35%'],
    linkedIn: 'linkedin.com/in/isabellaromano',
  },
  {
    id: 'exec-12',
    name: 'William Foster',
    role: 'FractionalExec',
    specialization: ['Sales'],
    rating: 4.6,
    experience: 12,
    costPerDay: 700,
    availability: 'Available from Feb 10',
    bio: 'Channel sales and partnerships expert. Built partner networks generating $100M+ in indirect revenue.',
    skills: ['Channel Sales', 'Partnerships', 'Ecosystem Development', 'Co-selling'],
    previousCompanies: ['Microsoft', 'AWS', 'Cisco'],
    avatarColor: '#0ea5e9',
    location: 'Reading, UK',
    email: 'william.foster@fractional.com',
    phone: '+44 7700 900412',
    education: 'BA Business Management, Bath University',
    certifications: ['Strategic Alliance Certified', 'Partner Management Certified'],
    achievements: ['Built network of 200+ active partners', 'Generated £150M indirect revenue', 'Launched 5 strategic alliances'],
    linkedIn: 'linkedin.com/in/williamfoster',
  },
  {
    id: 'exec-13',
    name: 'Amara Johnson',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Sales'],
    rating: 4.8,
    experience: 15,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Customer lifecycle expert. Designed retention and expansion programs that doubled customer LTV across multiple companies.',
    skills: ['Customer Marketing', 'Retention', 'Upsell/Cross-sell', 'Community Building'],
    previousCompanies: ['Slack', 'Intercom', 'Zendesk'],
    avatarColor: '#6366f1',
    location: 'Liverpool, UK',
    email: 'amara.johnson@fractional.com',
    phone: '+44 7700 900413',
    education: 'MSc Marketing, Manchester Business School',
    certifications: ['Customer Success Certified', 'Community Management Certified'],
    achievements: ['Improved NRR to 125%', 'Built community of 50K+ members', 'Reduced churn by 40%'],
    linkedIn: 'linkedin.com/in/amarajohnson',
  },
  {
    id: 'exec-14',
    name: 'Alexander Novak',
    role: 'FractionalExec',
    specialization: ['Engineering', 'Ops'],
    rating: 4.7,
    experience: 16,
    costPerDay: 900,
    availability: 'Available from Jan 28',
    bio: 'Engineering operations and site reliability expert. Reduced incidents by 80% and improved deployment frequency 10x.',
    skills: ['SRE', 'Incident Management', 'Monitoring', 'Automation'],
    previousCompanies: ['Google', 'Cloudflare', 'DataDog'],
    avatarColor: '#22c55e',
    location: 'Brighton, UK',
    email: 'alexander.novak@fractional.com',
    phone: '+44 7700 900414',
    education: 'MSc Computer Engineering, ETH Zurich',
    certifications: ['SRE Certified', 'Kubernetes Certified Administrator'],
    achievements: ['Achieved 99.99% uptime', 'Reduced MTTR by 85%', 'Automated 90% of operational tasks'],
    linkedIn: 'linkedin.com/in/alexandernovak',
  },
  {
    id: 'exec-15',
    name: 'Mia Wilson',
    role: 'FractionalExec',
    specialization: ['Finance'],
    rating: 4.9,
    experience: 14,
    costPerDay: 850,
    availability: 'Available Now',
    bio: 'Venture debt and growth financing specialist. Raised $200M+ in non-dilutive capital for high-growth tech companies.',
    skills: ['Venture Debt', 'Growth Financing', 'Cap Table Management', 'Financial Modeling'],
    previousCompanies: ['Silicon Valley Bank', 'Brex', 'Ramp'],
    avatarColor: '#fb923c',
    location: 'London, UK',
    email: 'mia.wilson@fractional.com',
    phone: '+44 7700 900415',
    education: 'MBA, Harvard Business School; BSc Finance, Wharton',
    certifications: ['CFA Level 2', 'Venture Capital Certified'],
    achievements: ['Raised £280M in venture debt', 'Advised 40+ companies on capital strategy', 'Structured 25+ debt facilities'],
    linkedIn: 'linkedin.com/in/miawilson',
  },
  {
    id: 'exec-16',
    name: 'Lucas Schmidt',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.6,
    experience: 11,
    costPerDay: 700,
    availability: 'Available from Feb 3',
    bio: 'Performance marketing and growth hacking specialist. Achieved sub-$20 CAC across multiple competitive verticals.',
    skills: ['Performance Marketing', 'Growth Hacking', 'Conversion Optimization', 'A/B Testing'],
    previousCompanies: ['Uber', 'DoorDash', 'Instacart'],
    avatarColor: '#d946ef',
    location: 'Nottingham, UK',
    email: 'lucas.schmidt@fractional.com',
    phone: '+44 7700 900416',
    education: 'BSc Marketing Analytics, Bristol University',
    certifications: ['Google Ads Certified', 'Facebook Blueprint Certified'],
    achievements: ['Reduced CAC by 60%', 'Generated 2M+ qualified leads', 'Managed £50M ad budget'],
    linkedIn: 'linkedin.com/in/lucasschmidt',
  },
  {
    id: 'exec-17',
    name: 'Charlotte Davis',
    role: 'FractionalExec',
    specialization: ['Sales', 'Ops'],
    rating: 4.8,
    experience: 13,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Revenue operations architect. Integrated sales, marketing, and CS systems to create unified revenue engine.',
    skills: ['RevOps', 'Systems Integration', 'Data Analytics', 'Process Design'],
    previousCompanies: ['Salesforce', 'Twilio', 'Segment'],
    avatarColor: '#f43f5e',
    location: 'Cardiff, UK',
    email: 'charlotte.davis@fractional.com',
    phone: '+44 7700 900417',
    education: 'BSc Information Systems, Southampton University',
    certifications: ['RevOps Certified', 'Salesforce Administrator'],
    achievements: ['Integrated tech stack for 20+ companies', 'Improved sales efficiency by 50%', 'Built RevOps playbook used by 100+ teams'],
    linkedIn: 'linkedin.com/in/charlottedavis',
  },
  {
    id: 'exec-18',
    name: 'Noah Campbell',
    role: 'FractionalExec',
    specialization: ['Engineering'],
    rating: 4.7,
    experience: 18,
    costPerDay: 950,
    availability: 'Available from Jan 22',
    bio: 'AI/ML engineering leader. Built and deployed production ML systems serving 100M+ users at top tech companies.',
    skills: ['Machine Learning', 'AI Strategy', 'Data Engineering', 'MLOps'],
    previousCompanies: ['OpenAI', 'DeepMind', 'Tesla'],
    avatarColor: '#06b6d4',
    location: 'London, UK',
    email: 'noah.campbell@fractional.com',
    phone: '+44 7700 900418',
    education: 'PhD Machine Learning, Cambridge; MEng AI, Oxford',
    certifications: ['TensorFlow Certified', 'AWS ML Certified'],
    achievements: ['Deployed ML models with 95%+ accuracy', 'Built recommendation engine for 200M users', 'Published 20+ AI papers'],
    linkedIn: 'linkedin.com/in/noahcampbell',
  },
  {
    id: 'exec-19',
    name: 'Zara Ali',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Ops'],
    rating: 4.9,
    experience: 12,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Digital transformation and marketing operations expert. Modernized marketing stacks and improved ROI by 200%+.',
    skills: ['Marketing Operations', 'MarTech Stack', 'Attribution', 'Digital Transformation'],
    previousCompanies: ['Adobe', 'HubSpot', 'Marketo'],
    avatarColor: '#a855f7',
    location: 'Sheffield, UK',
    email: 'zara.ali@fractional.com',
    phone: '+44 7700 900419',
    education: 'MBA Digital Marketing, Warwick Business School',
    certifications: ['MarTech Certified', 'Digital Transformation Certified'],
    achievements: ['Implemented marketing automation for 50+ companies', 'Improved attribution accuracy by 300%', 'Reduced marketing tech costs by 40%'],
    linkedIn: 'linkedin.com/in/zaraali',
  },
  {
    id: 'exec-20',
    name: 'Henry O\'Brien',
    role: 'FractionalExec',
    specialization: ['Finance', 'Sales'],
    rating: 4.8,
    experience: 17,
    costPerDay: 900,
    availability: 'Available from Feb 8',
    bio: 'Strategic finance and pricing expert. Optimized pricing models that increased revenue 30%+ without losing customers.',
    skills: ['Pricing Strategy', 'Revenue Modeling', 'Strategic Finance', 'Value-based Selling'],
    previousCompanies: ['McKinsey', 'BCG', 'Stripe'],
    avatarColor: '#22c55e',
    location: 'London, UK',
    email: 'henry.obrien@fractional.com',
    phone: '+44 7700 900420',
    education: 'MBA Strategy, INSEAD; BA Economics, Cambridge',
    certifications: ['Strategic Pricing Professional', 'Management Consulting Certified'],
    achievements: ['Increased revenue by avg 35% through pricing optimization', 'Led 100+ pricing projects', 'Advised Fortune 500 companies'],
    linkedIn: 'linkedin.com/in/henryobrien',
  },
  {
    id: 'exec-21',
    name: 'Hannah Stewart',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.7,
    experience: 13,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Content marketing and SEO strategist. Grew organic traffic from 0 to 10M monthly visits through content-led growth.',
    skills: ['Content Marketing', 'SEO', 'Content Strategy', 'Editorial Management'],
    previousCompanies: ['Moz', 'Buffer', 'Contentful'],
    avatarColor: '#10b981',
    location: 'Newcastle, UK',
    email: 'hannah.stewart@fractional.com',
    phone: '+44 7700 900421',
    education: 'MA Journalism, City University London',
    certifications: ['Content Marketing Institute Certified', 'Technical SEO Certified'],
    achievements: ['Grew organic traffic by 2000%', 'Managed editorial team of 20+', 'Published 500+ high-performing articles'],
    linkedIn: 'linkedin.com/in/hannahstewart',
  },
  {
    id: 'exec-22',
    name: 'Oscar Bennett',
    role: 'FractionalExec',
    specialization: ['Sales'],
    rating: 4.8,
    experience: 14,
    costPerDay: 800,
    availability: 'Available from Jan 26',
    bio: 'SaaS sales leader specializing in PLG and sales-led growth. Built hybrid sales models generating £100M+ ARR.',
    skills: ['Product-Led Growth', 'SaaS Sales', 'Sales Strategy', 'Hybrid Sales Models'],
    previousCompanies: ['Atlassian', 'Zoom', 'Calendly'],
    avatarColor: '#3b82f6',
    location: 'Edinburgh, UK',
    email: 'oscar.bennett@fractional.com',
    phone: '+44 7700 900422',
    education: 'BSc Business, Edinburgh University',
    certifications: ['Product-Led Growth Certified', 'SaaS Sales Leadership'],
    achievements: ['Built PLG motion generating £80M ARR', 'Scaled from 10 to 200 sales reps', '98% quota attainment rate'],
    linkedIn: 'linkedin.com/in/oscarbennett',
  },
  {
    id: 'exec-23',
    name: 'Freya Hughes',
    role: 'FractionalExec',
    specialization: ['Ops', 'Engineering'],
    rating: 4.9,
    experience: 16,
    costPerDay: 900,
    availability: 'Available Now',
    bio: 'Technical operations and DevOps leader. Built CI/CD pipelines and infrastructure automation for unicorn startups.',
    skills: ['DevOps', 'Infrastructure as Code', 'CI/CD', 'Cloud Operations'],
    previousCompanies: ['GitHub', 'GitLab', 'CircleCI'],
    avatarColor: '#8b5cf6',
    location: 'Manchester, UK',
    email: 'freya.hughes@fractional.com',
    phone: '+44 7700 900423',
    education: 'MEng Software Engineering, Imperial College',
    certifications: ['AWS DevOps Professional', 'Terraform Certified'],
    achievements: ['Reduced deployment time by 95%', 'Automated infrastructure for 50+ companies', 'Built platform used by 10K+ developers'],
    linkedIn: 'linkedin.com/in/freyahughes',
  },
  {
    id: 'exec-24',
    name: 'George Mitchell',
    role: 'FractionalExec',
    specialization: ['Finance'],
    rating: 4.7,
    experience: 15,
    costPerDay: 850,
    availability: 'Available from Feb 12',
    bio: 'Corporate finance expert specializing in IPO preparation and public company readiness for high-growth startups.',
    skills: ['IPO Preparation', 'Financial Controls', 'Audit Management', 'SOX Compliance'],
    previousCompanies: ['Deloitte', 'KPMG', 'Wise'],
    avatarColor: '#f59e0b',
    location: 'London, UK',
    email: 'george.mitchell@fractional.com',
    phone: '+44 7700 900424',
    education: 'ACA Qualified; BSc Accounting, LSE',
    certifications: ['ACA Chartered Accountant', 'SOX Compliance Certified'],
    achievements: ['Led IPO prep for 3 companies', 'Implemented financial controls for 25+ startups', 'Managed audits with zero findings'],
    linkedIn: 'linkedin.com/in/georgemitchell',
  },
  {
    id: 'exec-25',
    name: 'Lily Cooper',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Sales'],
    rating: 4.8,
    experience: 12,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Customer acquisition specialist. Built multi-channel acquisition strategies generating 500K+ customers for B2C companies.',
    skills: ['Customer Acquisition', 'Paid Media', 'Lifecycle Marketing', 'Attribution'],
    previousCompanies: ['Revolut', 'Monzo', 'Starling Bank'],
    avatarColor: '#ec4899',
    location: 'Bristol, UK',
    email: 'lily.cooper@fractional.com',
    phone: '+44 7700 900425',
    education: 'BSc Marketing, Bath University',
    certifications: ['Growth Marketing Certified', 'Performance Marketing Certified'],
    achievements: ['Acquired 2M+ customers', 'Reduced CPA by 55%', 'Built attribution model for £100M spend'],
    linkedIn: 'linkedin.com/in/lilycooper',
  },
  {
    id: 'exec-26',
    name: 'Sebastian Wood',
    role: 'FractionalExec',
    specialization: ['Engineering'],
    rating: 4.9,
    experience: 19,
    costPerDay: 1000,
    availability: 'Available from Jan 29',
    bio: 'Mobile engineering leader. Built mobile apps with 100M+ downloads and led teams of 50+ mobile engineers.',
    skills: ['Mobile Development', 'iOS/Android', 'React Native', 'Mobile Architecture'],
    previousCompanies: ['Meta', 'WhatsApp', 'Instagram'],
    avatarColor: '#06b6d4',
    location: 'London, UK',
    email: 'sebastian.wood@fractional.com',
    phone: '+44 7700 900426',
    education: 'MSc Computer Science, Stanford; BSc Software Engineering',
    certifications: ['iOS Certified Developer', 'Android Certified Developer'],
    achievements: ['Built apps with 200M+ downloads', 'Reduced app crashes by 90%', 'Led mobile teams at 3 unicorns'],
    linkedIn: 'linkedin.com/in/sebastianwood',
  },
  {
    id: 'exec-27',
    name: 'Ellie Roberts',
    role: 'FractionalExec',
    specialization: ['Ops'],
    rating: 4.7,
    experience: 14,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Customer operations and support leader. Built world-class support teams with <2hr response times and 95%+ CSAT.',
    skills: ['Customer Operations', 'Support Strategy', 'Team Building', 'CSAT/NPS'],
    previousCompanies: ['Intercom', 'Zendesk', 'Freshworks'],
    avatarColor: '#14b8a6',
    location: 'Glasgow, UK',
    email: 'ellie.roberts@fractional.com',
    phone: '+44 7700 900427',
    education: 'BA Business Management, Glasgow University',
    certifications: ['Customer Success Certified', 'Support Leadership Certified'],
    achievements: ['Built support team of 100+', 'Achieved 97% CSAT score', 'Reduced response time by 80%'],
    linkedIn: 'linkedin.com/in/ellieroberts',
  },
  {
    id: 'exec-28',
    name: 'Max Peterson',
    role: 'FractionalExec',
    specialization: ['Sales', 'Marketing'],
    rating: 4.8,
    experience: 13,
    costPerDay: 800,
    availability: 'Available from Feb 6',
    bio: 'Go-to-market strategist. Designed and executed GTM strategies for 30+ product launches with 90%+ success rate.',
    skills: ['Go-to-Market Strategy', 'Product Launches', 'Market Research', 'Competitive Analysis'],
    previousCompanies: ['Google', 'Amazon', 'Microsoft'],
    avatarColor: '#f97316',
    location: 'Cambridge, UK',
    email: 'max.peterson@fractional.com',
    phone: '+44 7700 900428',
    education: 'MBA, Cambridge Judge Business School',
    certifications: ['Product Management Certified', 'Market Research Certified'],
    achievements: ['Launched 35+ products successfully', 'Generated £200M in new revenue', 'Built GTM playbook for Fortune 500'],
    linkedIn: 'linkedin.com/in/maxpeterson',
  },
  {
    id: 'exec-29',
    name: 'Ruby Thompson',
    role: 'FractionalExec',
    specialization: ['Finance', 'Ops'],
    rating: 4.9,
    experience: 17,
    costPerDay: 900,
    availability: 'Available Now',
    bio: 'Finance transformation leader. Digitized finance operations and implemented NetSuite for 40+ high-growth companies.',
    skills: ['Finance Transformation', 'ERP Implementation', 'Process Automation', 'Financial Systems'],
    previousCompanies: ['SAP', 'Oracle', 'NetSuite'],
    avatarColor: '#ef4444',
    location: 'London, UK',
    email: 'ruby.thompson@fractional.com',
    phone: '+44 7700 900429',
    education: 'ACCA Qualified; BSc Accounting & Finance',
    certifications: ['NetSuite Certified', 'Financial Systems Certified'],
    achievements: ['Implemented ERP for 50+ companies', 'Reduced close time by 70%', 'Automated 85% of financial processes'],
    linkedIn: 'linkedin.com/in/rubythompson',
  },
  {
    id: 'exec-30',
    name: 'Felix Anderson',
    role: 'FractionalExec',
    specialization: ['Engineering'],
    rating: 4.8,
    experience: 18,
    costPerDay: 950,
    availability: 'Available from Jan 24',
    bio: 'Security and compliance engineering expert. Built security programs achieving SOC 2, ISO 27001, and GDPR compliance.',
    skills: ['Security Engineering', 'Compliance', 'Risk Management', 'Security Architecture'],
    previousCompanies: ['Cloudflare', 'Auth0', 'Okta'],
    avatarColor: '#a855f7',
    location: 'Edinburgh, UK',
    email: 'felix.anderson@fractional.com',
    phone: '+44 7700 900430',
    education: 'MSc Cybersecurity, Royal Holloway; BSc Computer Science',
    certifications: ['CISSP Certified', 'CISM Certified', 'ISO 27001 Lead Auditor'],
    achievements: ['Achieved SOC 2 for 30+ companies', 'Zero security breaches across clients', 'Built security programs from scratch'],
    linkedIn: 'linkedin.com/in/felixanderson',
  },
];

// First 30 handcrafted apprentice profiles
const baseApprentices: Candidate[] = [
  {
    id: 'app-1',
    name: 'Emily Carter',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available Now',
    bio: 'Recent marketing graduate with hands-on experience in social media and content creation. Eager to learn growth strategies.',
    skills: ['Social Media', 'Content Writing', 'Canva', 'Basic Analytics'],
    previousCompanies: ['Local Startup', 'Marketing Agency Intern'],
    avatarColor: '#3b82f6',
    location: 'London, UK',
    email: 'emily.carter@apprentice.com',
    phone: '+44 7700 900501',
    education: 'BA Marketing, University of Westminster',
    achievements: ['Managed social accounts with 20K followers', 'Created 100+ social posts', 'Ran successful Instagram campaign'],
  },
  {
    id: 'app-2',
    name: 'Daniel Lee',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.5,
    experience: 1,
    costPerDay: 120,
    availability: 'Available Now',
    bio: 'Computer science grad with strong fundamentals. Completed several personal projects and contributing to open source.',
    skills: ['React', 'Node.js', 'Python', 'Git'],
    previousCompanies: ['University Projects', 'Coding Bootcamp'],
    avatarColor: '#8b5cf6',
    location: 'Manchester, UK',
    email: 'daniel.lee@apprentice.com',
    phone: '+44 7700 900502',
    education: 'BSc Computer Science, Manchester University',
    achievements: ['Built 5 web applications', 'Contributed to 3 open source projects', 'Completed 200+ LeetCode problems'],
  },
  {
    id: 'app-3',
    name: 'Aisha Patel',
    role: 'Apprentice',
    specialization: ['Sales'],
    rating: 4.8,
    experience: 2,
    costPerDay: 160,
    availability: 'Available from Jan 20',
    bio: 'Natural communicator with sales internship experience. Consistently exceeded targets in SDR role.',
    skills: ['Cold Calling', 'Email Outreach', 'CRM (Salesforce)', 'Lead Qualification'],
    previousCompanies: ['Tech Startup - SDR', 'Retail Sales'],
    avatarColor: '#ec4899',
    location: 'Birmingham, UK',
    email: 'aisha.patel@apprentice.com',
    phone: '+44 7700 900503',
    education: 'BA Business Studies, Aston University',
    achievements: ['Exceeded quota by 130%', 'Booked 50+ qualified meetings', 'Top SDR performer 6 months running'],
  },
  {
    id: 'app-4',
    name: 'Oliver Hughes',
    role: 'Apprentice',
    specialization: ['Finance'],
    rating: 4.6,
    experience: 1,
    costPerDay: 140,
    availability: 'Available Now',
    bio: 'Finance graduate with strong Excel and analytical skills. Completed financial modeling course and seeking real-world experience.',
    skills: ['Excel', 'Financial Modeling', 'QuickBooks', 'Data Analysis'],
    previousCompanies: ['Accounting Firm Intern', 'University Finance Club'],
    avatarColor: '#10b981',
    location: 'Leeds, UK',
    email: 'oliver.hughes@apprentice.com',
    phone: '+44 7700 900504',
    education: 'BSc Finance, Leeds University',
    certifications: ['Excel Advanced Certified'],
    achievements: ['Built 10+ financial models', 'Completed AAT Level 2', 'Volunteer treasurer for student society'],
  },
  {
    id: 'app-5',
    name: 'Lily Wong',
    role: 'Apprentice',
    specialization: ['Marketing', 'Admin'],
    rating: 4.7,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'Creative and organized multi-tasker. Experience with email campaigns, event coordination, and administrative support.',
    skills: ['Email Marketing', 'Event Planning', 'Mailchimp', 'Project Coordination'],
    previousCompanies: ['Marketing Agency', 'Event Company'],
    avatarColor: '#f59e0b',
    location: 'Bristol, UK',
    email: 'lily.wong@apprentice.com',
    phone: '+44 7700 900505',
    education: 'BA Marketing & Events, UWE Bristol',
    achievements: ['Coordinated 15+ company events', 'Managed email list of 10K subscribers', 'Organized virtual conference for 500 attendees'],
  },
  {
    id: 'app-6',
    name: 'Jake Morrison',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.4,
    experience: 1,
    costPerDay: 125,
    availability: 'Available from Jan 25',
    bio: 'Self-taught developer with passion for mobile development. Built and published two apps on the App Store.',
    skills: ['React Native', 'JavaScript', 'Firebase', 'UI/UX'],
    previousCompanies: ['Freelance Projects', 'Personal Apps'],
    avatarColor: '#06b6d4',
    location: 'Glasgow, UK',
    email: 'jake.morrison@apprentice.com',
    phone: '+44 7700 900506',
    education: 'Self-taught, Online Bootcamps (Udemy, FreeCodeCamp)',
    achievements: ['Published 2 apps with 5K+ downloads', 'Completed 15+ freelance projects', 'Built portfolio with 20+ projects'],
  },
  {
    id: 'app-7',
    name: 'Sophia Martin',
    role: 'Apprentice',
    specialization: ['Ops'],
    rating: 4.6,
    experience: 2,
    costPerDay: 145,
    availability: 'Available Now',
    bio: 'Process-oriented thinker with experience in project management tools. Strong at creating SOPs and workflows.',
    skills: ['Notion', 'Asana', 'Process Documentation', 'Data Entry'],
    previousCompanies: ['Operations Intern', 'Logistics Company'],
    avatarColor: '#14b8a6',
    location: 'Newcastle, UK',
    email: 'sophia.martin@apprentice.com',
    phone: '+44 7700 900507',
    education: 'BSc Business Management, Northumbria University',
    achievements: ['Created 50+ SOPs', 'Improved team efficiency by 25%', 'Managed operations database of 1K+ entries'],
  },
  {
    id: 'app-8',
    name: 'Ryan Taylor',
    role: 'Apprentice',
    specialization: ['Sales', 'Marketing'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available Now',
    bio: 'Energetic and driven with experience in both sales and marketing. Great at creating sales collateral and prospecting.',
    skills: ['Sales Prospecting', 'Content Creation', 'LinkedIn', 'Presentation Design'],
    previousCompanies: ['SaaS Startup', 'Digital Marketing Intern'],
    avatarColor: '#f97316',
    location: 'Sheffield, UK',
    email: 'ryan.taylor@apprentice.com',
    phone: '+44 7700 900508',
    education: 'BA Marketing & Sales, Sheffield Hallam University',
    achievements: ['Generated 200+ qualified leads', 'Created sales deck used by entire team', 'Grew LinkedIn following to 3K'],
  },
  {
    id: 'app-9',
    name: 'Chloe Anderson',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 2,
    costPerDay: 165,
    availability: 'Available from Feb 1',
    bio: 'Creative marketer with strong design skills. Managed social media accounts with 50K+ combined followers.',
    skills: ['Graphic Design', 'Social Media Strategy', 'Adobe Suite', 'Video Editing'],
    previousCompanies: ['Influencer Marketing', 'Brand Partnerships'],
    avatarColor: '#ef4444',
    location: 'Liverpool, UK',
    email: 'chloe.anderson@apprentice.com',
    phone: '+44 7700 900509',
    education: 'BA Graphic Design, Liverpool John Moores',
    achievements: ['Grew Instagram account from 0 to 25K', 'Created 200+ social graphics', 'Ran campaigns with 500K reach'],
  },
  {
    id: 'app-10',
    name: 'Ethan Wright',
    role: 'Apprentice',
    specialization: ['Engineering', 'Ops'],
    rating: 4.5,
    experience: 1,
    costPerDay: 130,
    availability: 'Available Now',
    bio: 'Technical operations enthusiast. Good with automation, scripting, and improving workflows through technology.',
    skills: ['Python Scripting', 'APIs', 'Zapier', 'Database Basics'],
    previousCompanies: ['Tech Support', 'IT Internship'],
    avatarColor: '#a855f7',
    location: 'Cambridge, UK',
    email: 'ethan.wright@apprentice.com',
    phone: '+44 7700 900510',
    education: 'BSc IT, Anglia Ruskin University',
    achievements: ['Automated 10+ manual processes', 'Built 5 Zapier workflows', 'Wrote 20+ Python scripts'],
  },
  {
    id: 'app-11',
    name: 'Megan Clarke',
    role: 'Apprentice',
    specialization: ['Admin', 'Ops'],
    rating: 4.6,
    experience: 2,
    costPerDay: 140,
    availability: 'Available Now',
    bio: 'Highly organized with exceptional attention to detail. Experience managing calendars, travel, and admin tasks.',
    skills: ['Calendar Management', 'Travel Coordination', 'Google Workspace', 'Meeting Preparation'],
    previousCompanies: ['Executive Assistant Intern', 'Office Manager'],
    avatarColor: '#84cc16',
    location: 'Oxford, UK',
    email: 'megan.clarke@apprentice.com',
    phone: '+44 7700 900511',
    education: 'BA Business Administration, Oxford Brookes',
    achievements: ['Managed calendars for 3 executives', 'Coordinated 50+ business trips', 'Organized 100+ meetings'],
  },
  {
    id: 'app-12',
    name: 'Noah Bennett',
    role: 'Apprentice',
    specialization: ['Finance', 'Admin'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available from Jan 28',
    bio: 'Detail-oriented with experience in bookkeeping and financial admin. Strong with numbers and reconciliation.',
    skills: ['Bookkeeping', 'Invoicing', 'Xero', 'Expense Management'],
    previousCompanies: ['Accounting Startup', 'Finance Admin Role'],
    avatarColor: '#0ea5e9',
    location: 'Nottingham, UK',
    email: 'noah.bennett@apprentice.com',
    phone: '+44 7700 900512',
    education: 'AAT Level 3, Nottingham College',
    achievements: ['Processed 500+ invoices', 'Reconciled 1000+ transactions', 'Maintained 100% accuracy in bookkeeping'],
  },
  {
    id: 'app-13',
    name: 'Ava Robinson',
    role: 'Apprentice',
    specialization: ['Sales'],
    rating: 4.8,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'High-energy sales professional with customer service background. Excellent at building rapport and closing deals.',
    skills: ['Customer Service', 'Inside Sales', 'Objection Handling', 'Pipeline Management'],
    previousCompanies: ['Retail Management', 'Inside Sales Rep'],
    avatarColor: '#6366f1',
    location: 'Southampton, UK',
    email: 'ava.robinson@apprentice.com',
    phone: '+44 7700 900513',
    education: 'BA Business, Southampton Solent University',
    achievements: ['Closed £200K in sales', 'Maintained 85% win rate', 'Exceeded monthly targets 18 months straight'],
  },
  {
    id: 'app-14',
    name: 'Mason Cooper',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.4,
    experience: 1,
    costPerDay: 120,
    availability: 'Available from Feb 5',
    bio: 'Junior full-stack developer with internship experience. Eager to work on real production systems and learn best practices.',
    skills: ['HTML/CSS', 'JavaScript', 'SQL', 'Basic Backend'],
    previousCompanies: ['Web Development Intern', 'Freelance Websites'],
    avatarColor: '#22c55e',
    location: 'Cardiff, UK',
    email: 'mason.cooper@apprentice.com',
    phone: '+44 7700 900514',
    education: 'BSc Web Development, Cardiff Metropolitan',
    achievements: ['Built 8 client websites', 'Completed full-stack bootcamp', 'Contributed to startup MVP'],
  },
  {
    id: 'app-15',
    name: 'Isabella Foster',
    role: 'Apprentice',
    specialization: ['Marketing', 'Sales'],
    rating: 4.7,
    experience: 2,
    costPerDay: 160,
    availability: 'Available Now',
    bio: 'Versatile team player with experience in both marketing campaigns and sales support. Great at multitasking.',
    skills: ['Campaign Management', 'Sales Support', 'Market Research', 'Reporting'],
    previousCompanies: ['Growth Marketing Intern', 'Sales Enablement'],
    avatarColor: '#fb923c',
    location: 'Edinburgh, UK',
    email: 'isabella.foster@apprentice.com',
    phone: '+44 7700 900515',
    education: 'BA Marketing, Edinburgh Napier University',
    achievements: ['Supported 5 product launches', 'Created 30+ marketing reports', 'Assisted with £500K pipeline'],
  },
  {
    id: 'app-16',
    name: 'James Phillips',
    role: 'Apprentice',
    specialization: ['Ops'],
    rating: 4.5,
    experience: 1,
    costPerDay: 135,
    availability: 'Available from Jan 22',
    bio: 'Operations-minded with supply chain internship experience. Good at process improvement and inventory management.',
    skills: ['Supply Chain Basics', 'Inventory Tracking', 'Excel', 'Documentation'],
    previousCompanies: ['Logistics Intern', 'Warehouse Operations'],
    avatarColor: '#d946ef',
    location: 'Leicester, UK',
    email: 'james.phillips@apprentice.com',
    phone: '+44 7700 900516',
    education: 'BSc Supply Chain Management, De Montfort University',
    achievements: ['Improved inventory accuracy to 98%', 'Documented 20+ processes', 'Reduced waste by 15%'],
  },
  {
    id: 'app-17',
    name: 'Grace Mitchell',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 2,
    costPerDay: 165,
    availability: 'Available Now',
    bio: 'Content marketing specialist with blogging and SEO experience. Published 100+ articles with proven engagement results.',
    skills: ['SEO Writing', 'Blogging', 'WordPress', 'Content Strategy'],
    previousCompanies: ['Content Agency', 'Freelance Writer'],
    avatarColor: '#f43f5e',
    location: 'Brighton, UK',
    email: 'grace.mitchell@apprentice.com',
    phone: '+44 7700 900517',
    education: 'BA English & Creative Writing, Sussex University',
    achievements: ['Published 150+ articles', 'Drove 50K+ organic visits', 'Ranked 20+ keywords on page 1'],
  },
  {
    id: 'app-18',
    name: 'Liam Scott',
    role: 'Apprentice',
    specialization: ['Engineering', 'Admin'],
    rating: 4.6,
    experience: 1,
    costPerDay: 140,
    availability: 'Available from Feb 3',
    bio: 'Technical support specialist transitioning to development. Strong problem-solving skills and customer communication.',
    skills: ['Technical Support', 'Troubleshooting', 'Documentation', 'Basic Coding'],
    previousCompanies: ['Help Desk', 'IT Support'],
    avatarColor: '#06b6d4',
    location: 'Reading, UK',
    email: 'liam.scott@apprentice.com',
    phone: '+44 7700 900518',
    education: 'IT Support Apprenticeship, Level 3',
    achievements: ['Resolved 1000+ support tickets', '95% customer satisfaction', 'Created 50+ help articles'],
  },
  {
    id: 'app-19',
    name: 'Emma Harris',
    role: 'Apprentice',
    specialization: ['Finance', 'Ops'],
    rating: 4.7,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'Financial operations assistant with experience in AR/AP and budget tracking. Very reliable and accurate.',
    skills: ['AR/AP', 'Budget Tracking', 'Reconciliation', 'NetSuite'],
    previousCompanies: ['Finance Operations', 'Accounting Assistant'],
    avatarColor: '#a855f7',
    location: 'Coventry, UK',
    email: 'emma.harris@apprentice.com',
    phone: '+44 7700 900519',
    education: 'AAT Level 4, Coventry Technical College',
    achievements: ['Processed £2M in payments', 'Reconciled 500+ accounts', 'Reduced payment errors to <1%'],
  },
  {
    id: 'app-20',
    name: 'Benjamin King',
    role: 'Apprentice',
    specialization: ['Sales', 'Ops'],
    rating: 4.5,
    experience: 1,
    costPerDay: 145,
    availability: 'Available from Jan 30',
    bio: 'Operations and sales support with CRM experience. Great at data hygiene, reporting, and sales process optimization.',
    skills: ['CRM Management', 'Sales Operations', 'Data Hygiene', 'Reporting'],
    previousCompanies: ['Sales Ops Intern', 'CRM Administrator'],
    avatarColor: '#22c55e',
    location: 'Plymouth, UK',
    email: 'benjamin.king@apprentice.com',
    phone: '+44 7700 900520',
    education: 'BSc Business Information Systems, Plymouth University',
    achievements: ['Cleaned 10K+ CRM records', 'Built 15+ sales reports', 'Improved data accuracy by 40%'],
  },
  {
    id: 'app-21',
    name: 'Poppy Walker',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.6,
    experience: 2,
    costPerDay: 150,
    availability: 'Available Now',
    bio: 'Email marketing specialist with strong copywriting skills. Experience with automation and segmentation strategies.',
    skills: ['Email Marketing', 'Copywriting', 'Mailchimp', 'A/B Testing'],
    previousCompanies: ['E-commerce Startup', 'Email Marketing Intern'],
    avatarColor: '#10b981',
    location: 'York, UK',
    email: 'poppy.walker@apprentice.com',
    phone: '+44 7700 900521',
    education: 'BA Marketing Communications, York St John University',
    achievements: ['Achieved 25% open rate avg', 'Created 100+ email campaigns', 'Grew email list by 5K subscribers'],
  },
  {
    id: 'app-22',
    name: 'Harry Wilson',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.7,
    experience: 2,
    costPerDay: 155,
    availability: 'Available from Jan 27',
    bio: 'Backend developer with API integration experience. Comfortable with databases and building RESTful services.',
    skills: ['Node.js', 'Express', 'PostgreSQL', 'REST APIs'],
    previousCompanies: ['Startup Developer', 'Backend Intern'],
    avatarColor: '#3b82f6',
    location: 'Swansea, UK',
    email: 'harry.wilson@apprentice.com',
    phone: '+44 7700 900522',
    education: 'BSc Software Engineering, Swansea University',
    achievements: ['Built 5 REST APIs', 'Integrated 10+ third-party services', 'Optimized database queries by 50%'],
  },
  {
    id: 'app-23',
    name: 'Rosie Thompson',
    role: 'Apprentice',
    specialization: ['Sales'],
    rating: 4.8,
    experience: 2,
    costPerDay: 160,
    availability: 'Available Now',
    bio: 'Customer-focused sales rep with strong phone skills. Experienced in inbound and outbound sales.',
    skills: ['Phone Sales', 'Lead Nurturing', 'Product Demos', 'Closing Techniques'],
    previousCompanies: ['SaaS Sales', 'Telesales'],
    avatarColor: '#8b5cf6',
    location: 'Bournemouth, UK',
    email: 'rosie.thompson@apprentice.com',
    phone: '+44 7700 900523',
    education: 'BA Business & Sales, Bournemouth University',
    achievements: ['Closed 120+ deals', 'Maintained 75% close rate on demos', 'Generated £300K in revenue'],
  },
  {
    id: 'app-24',
    name: 'Alfie Davies',
    role: 'Apprentice',
    specialization: ['Ops', 'Admin'],
    rating: 4.5,
    experience: 1,
    costPerDay: 135,
    availability: 'Available from Feb 8',
    bio: 'Administrative coordinator with project management skills. Organized and detail-focused with strong communication.',
    skills: ['Project Coordination', 'Scheduling', 'Microsoft Office', 'Task Management'],
    previousCompanies: ['Admin Assistant', 'Project Coordinator'],
    avatarColor: '#f59e0b',
    location: 'Bath, UK',
    email: 'alfie.davies@apprentice.com',
    phone: '+44 7700 900524',
    education: 'BA Business Administration, Bath Spa University',
    achievements: ['Coordinated 20+ projects', 'Managed schedules for 5 managers', 'Organized 30+ team events'],
  },
  {
    id: 'app-25',
    name: 'Scarlett Brown',
    role: 'Apprentice',
    specialization: ['Marketing', 'Sales'],
    rating: 4.7,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'Marketing and sales coordinator with event management experience. Strong at lead generation and follow-up.',
    skills: ['Lead Generation', 'Event Marketing', 'Follow-up', 'Presentation Skills'],
    previousCompanies: ['B2B Marketing', 'Events Company'],
    avatarColor: '#ec4899',
    location: 'Winchester, UK',
    email: 'scarlett.brown@apprentice.com',
    phone: '+44 7700 900525',
    education: 'BA Marketing & Events, Winchester University',
    achievements: ['Generated 300+ leads from events', 'Organized 12 trade show booths', 'Achieved 40% event lead conversion'],
  },
  {
    id: 'app-26',
    name: 'Charlie Taylor',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.6,
    experience: 1,
    costPerDay: 130,
    availability: 'Available from Jan 23',
    bio: 'Frontend developer passionate about UI/UX. Experience building responsive websites and modern web apps.',
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Tailwind CSS'],
    previousCompanies: ['Web Agency', 'Frontend Intern'],
    avatarColor: '#06b6d4',
    location: 'Preston, UK',
    email: 'charlie.taylor@apprentice.com',
    phone: '+44 7700 900526',
    education: 'BSc Web Design & Development, UCLan',
    achievements: ['Built 12 responsive websites', 'Created component library used by team', 'Improved page load time by 60%'],
  },
  {
    id: 'app-27',
    name: 'Daisy Evans',
    role: 'Apprentice',
    specialization: ['Finance'],
    rating: 4.8,
    experience: 2,
    costPerDay: 160,
    availability: 'Available Now',
    bio: 'Finance assistant with accounts payable experience. Strong analytical skills and attention to detail.',
    skills: ['Accounts Payable', 'Financial Reporting', 'Sage', 'Bank Reconciliation'],
    previousCompanies: ['Finance Team', 'AP Specialist'],
    avatarColor: '#14b8a6',
    location: 'Derby, UK',
    email: 'daisy.evans@apprentice.com',
    phone: '+44 7700 900527',
    education: 'AAT Level 3, Derby College',
    achievements: ['Processed £5M in payments', 'Achieved 100% on-time payment rate', 'Reduced payment processing time by 30%'],
  },
  {
    id: 'app-28',
    name: 'Oscar Roberts',
    role: 'Apprentice',
    specialization: ['Ops'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available from Feb 2',
    bio: 'Operations analyst with data analysis skills. Good at finding inefficiencies and suggesting improvements.',
    skills: ['Data Analysis', 'Excel', 'Process Mapping', 'Performance Metrics'],
    previousCompanies: ['Operations Analyst', 'Business Intelligence Intern'],
    avatarColor: '#f97316',
    location: 'Stoke-on-Trent, UK',
    email: 'oscar.roberts@apprentice.com',
    phone: '+44 7700 900528',
    education: 'BSc Business Analytics, Staffordshire University',
    achievements: ['Analyzed 50+ business processes', 'Identified £100K in savings', 'Built 25+ Excel dashboards'],
  },
  {
    id: 'app-29',
    name: 'Isla Moore',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 2,
    costPerDay: 165,
    availability: 'Available Now',
    bio: 'Digital marketing specialist with paid advertising experience. Managed campaigns on Google Ads and Meta.',
    skills: ['Google Ads', 'Facebook Ads', 'Campaign Management', 'ROI Analysis'],
    previousCompanies: ['Digital Agency', 'PPC Specialist'],
    avatarColor: '#ef4444',
    location: 'Canterbury, UK',
    email: 'isla.moore@apprentice.com',
    phone: '+44 7700 900529',
    education: 'BA Digital Marketing, Canterbury Christ Church',
    certifications: ['Google Ads Certified'],
    achievements: ['Managed £200K ad budget', 'Achieved 3.5x ROAS', 'Ran 50+ successful campaigns'],
  },
  {
    id: 'app-30',
    name: 'Theo Jackson',
    role: 'Apprentice',
    specialization: ['Engineering', 'Ops'],
    rating: 4.6,
    experience: 1,
    costPerDay: 140,
    availability: 'Available from Jan 31',
    bio: 'Technical operations trainee with automation interest. Learning DevOps practices and infrastructure management.',
    skills: ['Linux', 'Bash Scripting', 'Git', 'Basic AWS'],
    previousCompanies: ['IT Operations', 'DevOps Intern'],
    avatarColor: '#a855f7',
    location: 'Exeter, UK',
    email: 'theo.jackson@apprentice.com',
    phone: '+44 7700 900530',
    education: 'BSc Computer Science, Exeter University',
    achievements: ['Automated 8 manual tasks', 'Learned Docker and Kubernetes basics', 'Managed Linux servers for startup'],
  },
];

// Generate additional profiles to reach 100+ each
const generatedExecutives = generateExecutives(31, 70); // Generate 70 more executives (31-100)
const generatedApprentices = generateApprentices(31, 70); // Generate 70 more apprentices (31-100)

// Export combined arrays with 100+ profiles each
export const fractionalExecutives: Candidate[] = [...baseExecutives, ...generatedExecutives];
export const apprentices: Candidate[] = [...baseApprentices, ...generatedApprentices];
