import type { Role, Function as BusinessFunction } from '@/types';

export interface Candidate {
  id: string;
  name: string;
  role: Role;
  specialization: BusinessFunction[];
  rating: number;
  experience: number; // years
  costPerDay: number; // GBP
  availability: string;
  bio: string;
  skills: string[];
  previousCompanies: string[];
  avatarColor: string;
}

export const fractionalExecutives: Candidate[] = [
  {
    id: 'exec-1',
    name: 'Sarah Mitchell',
    role: 'FractionalExec',
    specialization: ['Sales', 'Marketing'],
    rating: 4.9,
    experience: 15,
    costPerDay: 850,
    availability: 'Available Now',
    bio: 'Former VP of Sales at SaaS unicorn. Expert in building high-performing sales teams and scaling revenue operations.',
    skills: ['B2B Sales', 'Revenue Operations', 'Team Building', 'CRM Strategy'],
    previousCompanies: ['Salesforce', 'HubSpot', 'Stripe'],
    avatarColor: '#3b82f6',
  },
  {
    id: 'exec-2',
    name: 'James Chen',
    role: 'FractionalExec',
    specialization: ['Finance', 'Ops'],
    rating: 4.8,
    experience: 18,
    costPerDay: 950,
    availability: 'Available from Feb 1',
    bio: 'Ex-CFO with extensive experience in fundraising, financial modeling, and operational efficiency for tech startups.',
    skills: ['Financial Planning', 'Fundraising', 'Unit Economics', 'Cash Flow Management'],
    previousCompanies: ['Revolut', 'TransferWise', 'Monzo'],
    avatarColor: '#10b981',
  },
  {
    id: 'exec-3',
    name: 'Priya Sharma',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.7,
    experience: 12,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Growth marketing specialist with proven track record in scaling startups from 0 to 10M ARR through data-driven campaigns.',
    skills: ['Growth Marketing', 'SEO/SEM', 'Content Strategy', 'Analytics'],
    previousCompanies: ['Notion', 'Airtable', 'Figma'],
    avatarColor: '#f59e0b',
  },
  {
    id: 'exec-4',
    name: 'Marcus Rodriguez',
    role: 'FractionalExec',
    specialization: ['Engineering', 'Ops'],
    rating: 4.9,
    experience: 20,
    costPerDay: 1100,
    availability: 'Available from Jan 20',
    bio: 'Former CTO at multiple successful startups. Specializes in technical architecture, team scaling, and engineering culture.',
    skills: ['System Architecture', 'Team Leadership', 'DevOps', 'Technical Strategy'],
    previousCompanies: ['Uber', 'Airbnb', 'Dropbox'],
    avatarColor: '#8b5cf6',
  },
  {
    id: 'exec-5',
    name: 'Emma Thompson',
    role: 'FractionalExec',
    specialization: ['Sales'],
    rating: 4.6,
    experience: 10,
    costPerDay: 700,
    availability: 'Available Now',
    bio: 'Enterprise sales expert with experience closing 7-figure deals. Specialized in building sales playbooks and processes.',
    skills: ['Enterprise Sales', 'Deal Strategy', 'Sales Enablement', 'Customer Success'],
    previousCompanies: ['Oracle', 'SAP', 'ServiceNow'],
    avatarColor: '#ec4899',
  },
  {
    id: 'exec-6',
    name: 'David Kim',
    role: 'FractionalExec',
    specialization: ['Finance'],
    rating: 4.8,
    experience: 16,
    costPerDay: 900,
    availability: 'Available from Jan 25',
    bio: 'Investment banking background with deep expertise in M&A, valuations, and strategic financial planning for scale-ups.',
    skills: ['M&A', 'Valuation', 'Strategic Planning', 'Investor Relations'],
    previousCompanies: ['Goldman Sachs', 'J.P. Morgan', 'Revolut'],
    avatarColor: '#06b6d4',
  },
  {
    id: 'exec-7',
    name: 'Olivia Martinez',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Sales'],
    rating: 4.7,
    experience: 14,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Integrated marketing and sales strategist. Built demand gen engines that generated $50M+ pipeline for B2B companies.',
    skills: ['Demand Generation', 'ABM', 'Marketing Automation', 'Sales Alignment'],
    previousCompanies: ['Gong', 'Drift', 'Outreach'],
    avatarColor: '#14b8a6',
  },
  {
    id: 'exec-8',
    name: 'Thomas Anderson',
    role: 'FractionalExec',
    specialization: ['Ops'],
    rating: 4.9,
    experience: 17,
    costPerDay: 850,
    availability: 'Available from Feb 5',
    bio: 'Operations excellence expert. Led operational transformations at hyper-growth companies, improving efficiency by 40%+.',
    skills: ['Process Optimization', 'Supply Chain', 'Project Management', 'Lean Six Sigma'],
    previousCompanies: ['Amazon', 'Tesla', 'Deliveroo'],
    avatarColor: '#f97316',
  },
  {
    id: 'exec-9',
    name: 'Sophia Patel',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 11,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Brand and product marketing specialist. Launched 20+ products with combined $500M+ in revenue impact.',
    skills: ['Product Marketing', 'Brand Strategy', 'Go-to-Market', 'Positioning'],
    previousCompanies: ['Apple', 'Google', 'Spotify'],
    avatarColor: '#ef4444',
  },
  {
    id: 'exec-10',
    name: 'Robert Zhang',
    role: 'FractionalExec',
    specialization: ['Engineering'],
    rating: 4.7,
    experience: 19,
    costPerDay: 1000,
    availability: 'Available from Jan 30',
    bio: 'Platform engineering leader. Built infrastructure supporting billions of daily requests at major tech companies.',
    skills: ['Platform Engineering', 'Cloud Architecture', 'Scalability', 'Security'],
    previousCompanies: ['Netflix', 'Twitter', 'LinkedIn'],
    avatarColor: '#a855f7',
  },
  {
    id: 'exec-11',
    name: 'Isabella Romano',
    role: 'FractionalExec',
    specialization: ['Finance', 'Ops'],
    rating: 4.9,
    experience: 13,
    costPerDay: 850,
    availability: 'Available Now',
    bio: 'FP&A and operations leader. Helped 15+ startups optimize burn rate and extend runway during difficult market conditions.',
    skills: ['FP&A', 'Scenario Planning', 'Cost Optimization', 'KPI Frameworks'],
    previousCompanies: ['Meta', 'Snap', 'Pinterest'],
    avatarColor: '#84cc16',
  },
  {
    id: 'exec-12',
    name: 'William Foster',
    role: 'FractionalExec',
    specialization: ['Sales'],
    rating: 4.6,
    experience: 12,
    costPerDay: 700,
    availability: 'Available from Feb 10',
    bio: 'Channel sales and partnerships expert. Built partner networks generating $100M+ in indirect revenue.',
    skills: ['Channel Sales', 'Partnerships', 'Ecosystem Development', 'Co-selling'],
    previousCompanies: ['Microsoft', 'AWS', 'Cisco'],
    avatarColor: '#0ea5e9',
  },
  {
    id: 'exec-13',
    name: 'Amara Johnson',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Sales'],
    rating: 4.8,
    experience: 15,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Customer lifecycle expert. Designed retention and expansion programs that doubled customer LTV across multiple companies.',
    skills: ['Customer Marketing', 'Retention', 'Upsell/Cross-sell', 'Community Building'],
    previousCompanies: ['Slack', 'Intercom', 'Zendesk'],
    avatarColor: '#6366f1',
  },
  {
    id: 'exec-14',
    name: 'Alexander Novak',
    role: 'FractionalExec',
    specialization: ['Engineering', 'Ops'],
    rating: 4.7,
    experience: 16,
    costPerDay: 900,
    availability: 'Available from Jan 28',
    bio: 'Engineering operations and site reliability expert. Reduced incidents by 80% and improved deployment frequency 10x.',
    skills: ['SRE', 'Incident Management', 'Monitoring', 'Automation'],
    previousCompanies: ['Google', 'Cloudflare', 'DataDog'],
    avatarColor: '#22c55e',
  },
  {
    id: 'exec-15',
    name: 'Mia Wilson',
    role: 'FractionalExec',
    specialization: ['Finance'],
    rating: 4.9,
    experience: 14,
    costPerDay: 850,
    availability: 'Available Now',
    bio: 'Venture debt and growth financing specialist. Raised $200M+ in non-dilutive capital for high-growth tech companies.',
    skills: ['Venture Debt', 'Growth Financing', 'Cap Table Management', 'Financial Modeling'],
    previousCompanies: ['Silicon Valley Bank', 'Brex', 'Ramp'],
    avatarColor: '#fb923c',
  },
  {
    id: 'exec-16',
    name: 'Lucas Schmidt',
    role: 'FractionalExec',
    specialization: ['Marketing'],
    rating: 4.6,
    experience: 11,
    costPerDay: 700,
    availability: 'Available from Feb 3',
    bio: 'Performance marketing and growth hacking specialist. Achieved sub-$20 CAC across multiple competitive verticals.',
    skills: ['Performance Marketing', 'Growth Hacking', 'Conversion Optimization', 'A/B Testing'],
    previousCompanies: ['Uber', 'DoorDash', 'Instacart'],
    avatarColor: '#d946ef',
  },
  {
    id: 'exec-17',
    name: 'Charlotte Davis',
    role: 'FractionalExec',
    specialization: ['Sales', 'Ops'],
    rating: 4.8,
    experience: 13,
    costPerDay: 750,
    availability: 'Available Now',
    bio: 'Revenue operations architect. Integrated sales, marketing, and CS systems to create unified revenue engine.',
    skills: ['RevOps', 'Systems Integration', 'Data Analytics', 'Process Design'],
    previousCompanies: ['Salesforce', 'Twilio', 'Segment'],
    avatarColor: '#f43f5e',
  },
  {
    id: 'exec-18',
    name: 'Noah Campbell',
    role: 'FractionalExec',
    specialization: ['Engineering'],
    rating: 4.7,
    experience: 18,
    costPerDay: 950,
    availability: 'Available from Jan 22',
    bio: 'AI/ML engineering leader. Built and deployed production ML systems serving 100M+ users at top tech companies.',
    skills: ['Machine Learning', 'AI Strategy', 'Data Engineering', 'MLOps'],
    previousCompanies: ['OpenAI', 'DeepMind', 'Tesla'],
    avatarColor: '#06b6d4',
  },
  {
    id: 'exec-19',
    name: 'Zara Ali',
    role: 'FractionalExec',
    specialization: ['Marketing', 'Ops'],
    rating: 4.9,
    experience: 12,
    costPerDay: 800,
    availability: 'Available Now',
    bio: 'Digital transformation and marketing operations expert. Modernized marketing stacks and improved ROI by 200%+.',
    skills: ['Marketing Operations', 'MarTech Stack', 'Attribution', 'Digital Transformation'],
    previousCompanies: ['Adobe', 'HubSpot', 'Marketo'],
    avatarColor: '#a855f7',
  },
  {
    id: 'exec-20',
    name: 'Henry O\'Brien',
    role: 'FractionalExec',
    specialization: ['Finance', 'Sales'],
    rating: 4.8,
    experience: 17,
    costPerDay: 900,
    availability: 'Available from Feb 8',
    bio: 'Strategic finance and pricing expert. Optimized pricing models that increased revenue 30%+ without losing customers.',
    skills: ['Pricing Strategy', 'Revenue Modeling', 'Strategic Finance', 'Value-based Selling'],
    previousCompanies: ['McKinsey', 'BCG', 'Stripe'],
    avatarColor: '#22c55e',
  },
];

export const apprentices: Candidate[] = [
  {
    id: 'app-1',
    name: 'Emily Carter',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available Now',
    bio: 'Recent marketing graduate with hands-on experience in social media and content creation. Eager to learn growth strategies.',
    skills: ['Social Media', 'Content Writing', 'Canva', 'Basic Analytics'],
    previousCompanies: ['Local Startup', 'Marketing Agency Intern'],
    avatarColor: '#3b82f6',
  },
  {
    id: 'app-2',
    name: 'Daniel Lee',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.5,
    experience: 1,
    costPerDay: 120,
    availability: 'Available Now',
    bio: 'Computer science grad with strong fundamentals. Completed several personal projects and contributing to open source.',
    skills: ['React', 'Node.js', 'Python', 'Git'],
    previousCompanies: ['University Projects', 'Coding Bootcamp'],
    avatarColor: '#8b5cf6',
  },
  {
    id: 'app-3',
    name: 'Aisha Patel',
    role: 'Apprentice',
    specialization: ['Sales'],
    rating: 4.8,
    experience: 2,
    costPerDay: 160,
    availability: 'Available from Jan 20',
    bio: 'Natural communicator with sales internship experience. Consistently exceeded targets in SDR role.',
    skills: ['Cold Calling', 'Email Outreach', 'CRM (Salesforce)', 'Lead Qualification'],
    previousCompanies: ['Tech Startup - SDR', 'Retail Sales'],
    avatarColor: '#ec4899',
  },
  {
    id: 'app-4',
    name: 'Oliver Hughes',
    role: 'Apprentice',
    specialization: ['Finance'],
    rating: 4.6,
    experience: 1,
    costPerDay: 140,
    availability: 'Available Now',
    bio: 'Finance graduate with strong Excel and analytical skills. Completed financial modeling course and seeking real-world experience.',
    skills: ['Excel', 'Financial Modeling', 'QuickBooks', 'Data Analysis'],
    previousCompanies: ['Accounting Firm Intern', 'University Finance Club'],
    avatarColor: '#10b981',
  },
  {
    id: 'app-5',
    name: 'Lily Wong',
    role: 'Apprentice',
    specialization: ['Marketing', 'Admin'],
    rating: 4.7,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'Creative and organized multi-tasker. Experience with email campaigns, event coordination, and administrative support.',
    skills: ['Email Marketing', 'Event Planning', 'Mailchimp', 'Project Coordination'],
    previousCompanies: ['Marketing Agency', 'Event Company'],
    avatarColor: '#f59e0b',
  },
  {
    id: 'app-6',
    name: 'Jake Morrison',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.4,
    experience: 1,
    costPerDay: 125,
    availability: 'Available from Jan 25',
    bio: 'Self-taught developer with passion for mobile development. Built and published two apps on the App Store.',
    skills: ['React Native', 'JavaScript', 'Firebase', 'UI/UX'],
    previousCompanies: ['Freelance Projects', 'Personal Apps'],
    avatarColor: '#06b6d4',
  },
  {
    id: 'app-7',
    name: 'Sophia Martin',
    role: 'Apprentice',
    specialization: ['Ops'],
    rating: 4.6,
    experience: 2,
    costPerDay: 145,
    availability: 'Available Now',
    bio: 'Process-oriented thinker with experience in project management tools. Strong at creating SOPs and workflows.',
    skills: ['Notion', 'Asana', 'Process Documentation', 'Data Entry'],
    previousCompanies: ['Operations Intern', 'Logistics Company'],
    avatarColor: '#14b8a6',
  },
  {
    id: 'app-8',
    name: 'Ryan Taylor',
    role: 'Apprentice',
    specialization: ['Sales', 'Marketing'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available Now',
    bio: 'Energetic and driven with experience in both sales and marketing. Great at creating sales collateral and prospecting.',
    skills: ['Sales Prospecting', 'Content Creation', 'LinkedIn', 'Presentation Design'],
    previousCompanies: ['SaaS Startup', 'Digital Marketing Intern'],
    avatarColor: '#f97316',
  },
  {
    id: 'app-9',
    name: 'Chloe Anderson',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 2,
    costPerDay: 165,
    availability: 'Available from Feb 1',
    bio: 'Creative marketer with strong design skills. Managed social media accounts with 50K+ combined followers.',
    skills: ['Graphic Design', 'Social Media Strategy', 'Adobe Suite', 'Video Editing'],
    previousCompanies: ['Influencer Marketing', 'Brand Partnerships'],
    avatarColor: '#ef4444',
  },
  {
    id: 'app-10',
    name: 'Ethan Wright',
    role: 'Apprentice',
    specialization: ['Engineering', 'Ops'],
    rating: 4.5,
    experience: 1,
    costPerDay: 130,
    availability: 'Available Now',
    bio: 'Technical operations enthusiast. Good with automation, scripting, and improving workflows through technology.',
    skills: ['Python Scripting', 'APIs', 'Zapier', 'Database Basics'],
    previousCompanies: ['Tech Support', 'IT Internship'],
    avatarColor: '#a855f7',
  },
  {
    id: 'app-11',
    name: 'Megan Clarke',
    role: 'Apprentice',
    specialization: ['Admin', 'Ops'],
    rating: 4.6,
    experience: 2,
    costPerDay: 140,
    availability: 'Available Now',
    bio: 'Highly organized with exceptional attention to detail. Experience managing calendars, travel, and admin tasks.',
    skills: ['Calendar Management', 'Travel Coordination', 'Google Workspace', 'Meeting Preparation'],
    previousCompanies: ['Executive Assistant Intern', 'Office Manager'],
    avatarColor: '#84cc16',
  },
  {
    id: 'app-12',
    name: 'Noah Bennett',
    role: 'Apprentice',
    specialization: ['Finance', 'Admin'],
    rating: 4.7,
    experience: 2,
    costPerDay: 150,
    availability: 'Available from Jan 28',
    bio: 'Detail-oriented with experience in bookkeeping and financial admin. Strong with numbers and reconciliation.',
    skills: ['Bookkeeping', 'Invoicing', 'Xero', 'Expense Management'],
    previousCompanies: ['Accounting Startup', 'Finance Admin Role'],
    avatarColor: '#0ea5e9',
  },
  {
    id: 'app-13',
    name: 'Ava Robinson',
    role: 'Apprentice',
    specialization: ['Sales'],
    rating: 4.8,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'High-energy sales professional with customer service background. Excellent at building rapport and closing deals.',
    skills: ['Customer Service', 'Inside Sales', 'Objection Handling', 'Pipeline Management'],
    previousCompanies: ['Retail Management', 'Inside Sales Rep'],
    avatarColor: '#6366f1',
  },
  {
    id: 'app-14',
    name: 'Mason Cooper',
    role: 'Apprentice',
    specialization: ['Engineering'],
    rating: 4.4,
    experience: 1,
    costPerDay: 120,
    availability: 'Available from Feb 5',
    bio: 'Junior full-stack developer with internship experience. Eager to work on real production systems and learn best practices.',
    skills: ['HTML/CSS', 'JavaScript', 'SQL', 'Basic Backend'],
    previousCompanies: ['Web Development Intern', 'Freelance Websites'],
    avatarColor: '#22c55e',
  },
  {
    id: 'app-15',
    name: 'Isabella Foster',
    role: 'Apprentice',
    specialization: ['Marketing', 'Sales'],
    rating: 4.7,
    experience: 2,
    costPerDay: 160,
    availability: 'Available Now',
    bio: 'Versatile team player with experience in both marketing campaigns and sales support. Great at multitasking.',
    skills: ['Campaign Management', 'Sales Support', 'Market Research', 'Reporting'],
    previousCompanies: ['Growth Marketing Intern', 'Sales Enablement'],
    avatarColor: '#fb923c',
  },
  {
    id: 'app-16',
    name: 'James Phillips',
    role: 'Apprentice',
    specialization: ['Ops'],
    rating: 4.5,
    experience: 1,
    costPerDay: 135,
    availability: 'Available from Jan 22',
    bio: 'Operations-minded with supply chain internship experience. Good at process improvement and inventory management.',
    skills: ['Supply Chain Basics', 'Inventory Tracking', 'Excel', 'Documentation'],
    previousCompanies: ['Logistics Intern', 'Warehouse Operations'],
    avatarColor: '#d946ef',
  },
  {
    id: 'app-17',
    name: 'Grace Mitchell',
    role: 'Apprentice',
    specialization: ['Marketing'],
    rating: 4.8,
    experience: 2,
    costPerDay: 165,
    availability: 'Available Now',
    bio: 'Content marketing specialist with blogging and SEO experience. Published 100+ articles with proven engagement results.',
    skills: ['SEO Writing', 'Blogging', 'WordPress', 'Content Strategy'],
    previousCompanies: ['Content Agency', 'Freelance Writer'],
    avatarColor: '#f43f5e',
  },
  {
    id: 'app-18',
    name: 'Liam Scott',
    role: 'Apprentice',
    specialization: ['Engineering', 'Admin'],
    rating: 4.6,
    experience: 1,
    costPerDay: 140,
    availability: 'Available from Feb 3',
    bio: 'Technical support specialist transitioning to development. Strong problem-solving skills and customer communication.',
    skills: ['Technical Support', 'Troubleshooting', 'Documentation', 'Basic Coding'],
    previousCompanies: ['Help Desk', 'IT Support'],
    avatarColor: '#06b6d4',
  },
  {
    id: 'app-19',
    name: 'Emma Harris',
    role: 'Apprentice',
    specialization: ['Finance', 'Ops'],
    rating: 4.7,
    experience: 2,
    costPerDay: 155,
    availability: 'Available Now',
    bio: 'Financial operations assistant with experience in AR/AP and budget tracking. Very reliable and accurate.',
    skills: ['AR/AP', 'Budget Tracking', 'Reconciliation', 'NetSuite'],
    previousCompanies: ['Finance Operations', 'Accounting Assistant'],
    avatarColor: '#a855f7',
  },
  {
    id: 'app-20',
    name: 'Benjamin King',
    role: 'Apprentice',
    specialization: ['Sales', 'Ops'],
    rating: 4.5,
    experience: 1,
    costPerDay: 145,
    availability: 'Available from Jan 30',
    bio: 'Operations and sales support with CRM experience. Great at data hygiene, reporting, and sales process optimization.',
    skills: ['CRM Management', 'Sales Operations', 'Data Hygiene', 'Reporting'],
    previousCompanies: ['Sales Ops Intern', 'CRM Administrator'],
    avatarColor: '#22c55e',
  },
];
