/**
 * Manufacturing-Focused AI Tools
 * These replace the generic software engineering tools with manufacturing-specific AI
 */

import type { ThirdPartyAITool } from './third-party-ai-tools';

export const MANUFACTURING_AI_TOOLS: ThirdPartyAITool[] = [
  {
    id: 'ai-mfg-1',
    name: 'Autodesk Fusion AI',
    provider: 'Autodesk',
    purpose: 'Generative design and AI-powered CAD for manufacturing optimization',
    description: 'Autodesk Fusion 360 with AI capabilities enables engineers to create optimized designs by defining goals and constraints. The AI explores thousands of design alternatives, generating lightweight, manufacturable parts that meet your specifications while reducing material waste and manufacturing costs.',
    functions: ['Engineering'],
    costPerMonth: 680,
    website: 'https://autodesk.com/products/fusion-360',
    capabilities: [
      'Generative design with manufacturing constraints',
      'Topology optimization for weight reduction',
      'DFM (Design for Manufacturing) analysis',
      'Material selection optimization',
      'Cost estimation and simulation',
      'Multi-physics simulation integration',
    ],
    integrations: ['SolidWorks', 'Inventor', 'STEP/IGES', 'CAM software', '3D printers'],
    category: 'manufacturing',
    useCases: [
      'Optimize bracket designs for aerospace components',
      'Reduce material costs while maintaining structural integrity',
      'Generate multiple design alternatives for rapid prototyping',
      'Validate manufacturability before production',
    ],
    keyFeatures: [
      'AI-driven generative design engine',
      'Cloud-based collaboration',
      'Integrated CAM and simulation',
      'Real-time cost feedback',
    ],
    pricing: {
      professional: '£680/month (includes AI features)',
      enterprise: 'Custom pricing for teams',
      notes: 'Annual subscription available at discount',
    },
    setup: {
      difficulty: 'Advanced',
      timeToValue: '2-4 weeks (requires CAD training)',
      requirements: ['Windows 10/11 or macOS', '8GB RAM minimum', 'GPU recommended', 'Engineering background'],
    },
    support: {
      documentation: 'Extensive tutorials and API docs',
      community: 'Active forums with 1M+ users',
      email: true,
      phone: true,
    },
    reviews: {
      rating: 4.6,
      totalReviews: 3200,
      pros: [
        'Industry-leading generative design',
        'Seamless CAD to CAM workflow',
        'Cloud collaboration features',
        'Regular updates and improvements',
      ],
      cons: [
        'Steep learning curve for beginners',
        'Requires powerful hardware',
        'Subscription can be expensive',
      ],
    },
  },
  {
    id: 'ai-mfg-2',
    name: 'Monolith AI',
    provider: 'Monolith',
    purpose: 'AI-powered FEA simulation that learns from your engineering data',
    description: 'Monolith uses machine learning to dramatically speed up finite element analysis (FEA) simulations. Instead of waiting hours or days for traditional FEA results, Monolith learns patterns from your historical simulation data and provides near-instant predictions with high accuracy.',
    functions: ['Engineering'],
    costPerMonth: 850,
    website: 'https://monolith.ai',
    capabilities: [
      'Instant FEA predictions using ML',
      'Multi-physics simulation acceleration',
      'Design space exploration',
      'Sensitivity analysis automation',
      'Integration with existing CAE tools',
      'Uncertainty quantification',
    ],
    integrations: ['ANSYS', 'Abaqus', 'LS-DYNA', 'Python', 'Excel'],
    category: 'manufacturing',
    useCases: [
      'Reduce simulation time from days to minutes',
      'Run thousands of design variations quickly',
      'Optimize crashworthiness in automotive design',
      'Predict structural failures before physical testing',
    ],
    keyFeatures: [
      'Self-learning AI that improves over time',
      'No simulation knowledge required',
      'Runs on existing hardware',
      'Explainable AI predictions',
    ],
    pricing: {
      professional: '£850/month per user',
      enterprise: 'Custom pricing with dedicated support',
      notes: 'ROI typically realized within 3 months',
    },
    setup: {
      difficulty: 'Moderate',
      timeToValue: '1-2 weeks (requires historical simulation data)',
      requirements: ['Historical FEA data', 'Python 3.7+', '16GB RAM', 'Engineering team buy-in'],
    },
    support: {
      documentation: 'Comprehensive guides and case studies',
      community: 'Slack workspace with engineers',
      email: true,
      phone: false,
    },
    reviews: {
      rating: 4.8,
      totalReviews: 180,
      pros: [
        'Dramatic time savings (10-100x faster)',
        'Accurate predictions',
        'Easy integration with existing tools',
        'Excellent customer support',
      ],
      cons: [
        'Requires good quality historical data',
        'Premium pricing',
        'Limited to specific simulation types',
      ],
    },
  },
  {
    id: 'ai-mfg-3',
    name: 'Paperless Parts',
    provider: 'Paperless Parts',
    purpose: 'AI-powered quoting and RFQ management for manufacturing',
    description: 'Paperless Parts uses AI to automatically generate accurate quotes for CNC machining, sheet metal, and 3D printing. Upload CAD files and receive instant pricing, lead times, and DFM feedback. Streamlines the entire quote-to-order process for contract manufacturers and helps you get instant RFQ responses.',
    functions: ['Engineering', 'Ops'],
    costPerMonth: 500,
    website: 'https://paperlessparts.com',
    capabilities: [
      'Instant automated quoting from CAD',
      'DFM analysis and recommendations',
      'Material and finish selection',
      'Lead time estimation',
      'ERP/CRM integration',
      'Customer portal for quotes',
    ],
    integrations: ['SolidWorks', 'Fusion 360', 'QuickBooks', 'Salesforce', 'NetSuite'],
    category: 'manufacturing',
    useCases: [
      'Generate quotes in minutes instead of hours',
      'Identify manufacturing issues before production',
      'Track RFQs through entire lifecycle',
      'Get instant pricing from suppliers',
    ],
    keyFeatures: [
      'Geometric analysis AI',
      'Automated pricing algorithms',
      'Customer self-service portal',
      'Order management system',
    ],
    pricing: {
      professional: '£500/month base + transaction fees',
      enterprise: 'Custom pricing for high volume',
      notes: 'Pricing scales with quote volume',
    },
    setup: {
      difficulty: 'Easy',
      timeToValue: '1 week (mostly configuration)',
      requirements: ['CAD files in STEP/IGES format', 'Pricing data for materials/processes', 'Web browser'],
    },
    support: {
      documentation: 'Video tutorials and setup guides',
      community: 'User forum and webinars',
      email: true,
      phone: true,
    },
    reviews: {
      rating: 4.7,
      totalReviews: 420,
      pros: [
        'Massive time savings on quoting',
        'Improved quote accuracy',
        'Great customer experience',
        'Easy to implement',
      ],
      cons: [
        'Transaction fees can add up',
        'Limited customization options',
        'Works best for standard processes',
      ],
    },
  },
  {
    id: 'ai-mfg-4',
    name: 'Instrumental',
    provider: 'Instrumental',
    purpose: 'AI-powered manufacturing quality inspection and root cause analysis',
    description: 'Instrumental uses computer vision and AI to automatically inspect products on manufacturing lines. Detects defects faster than human inspection, traces issues back to root causes, and predicts quality problems before they occur. Perfect for electronics and hardware production.',
    functions: ['Engineering', 'Ops'],
    costPerMonth: 1200,
    website: 'https://instrumental.com',
    capabilities: [
      'Automated optical inspection (AOI)',
      'Defect detection and classification',
      'Root cause analysis automation',
      'Predictive quality analytics',
      'Yield improvement tracking',
      'Supplier quality monitoring',
    ],
    integrations: ['Custom cameras', 'MES systems', 'Slack', 'Jira', 'Webhooks'],
    category: 'manufacturing',
    useCases: [
      'Catch defects early in production',
      'Reduce scrap and rework costs',
      'Identify supplier quality issues',
      'Improve first-pass yield rates',
    ],
    keyFeatures: [
      'Computer vision AI trained on manufacturing',
      'Real-time defect alerts',
      'Trace defects to specific processes',
      'Historical trend analysis',
    ],
    pricing: {
      professional: '£1,200/month per production line',
      enterprise: 'Custom pricing for multiple facilities',
      notes: 'Includes hardware and software',
    },
    setup: {
      difficulty: 'Moderate',
      timeToValue: '4-6 weeks (includes camera installation)',
      requirements: ['Production line access', 'Network connectivity', 'Training data (images)', 'Quality team involvement'],
    },
    support: {
      documentation: 'Implementation guides and API docs',
      community: 'Private customer Slack',
      email: true,
      phone: true,
    },
    reviews: {
      rating: 4.5,
      totalReviews: 95,
      pros: [
        'Significantly improves quality metrics',
        'Fast detection of issues',
        'Great analytics dashboard',
        'Proactive customer success team',
      ],
      cons: [
        'High initial investment',
        'Requires good lighting setup',
        'Training period can be lengthy',
      ],
    },
  },
];
