/**
 * Supabase Invitation Service
 *
 * Handles secure invitation management using people_invites table
 * with cryptographically secure tokens and email verification
 */

import { supabase } from './supabase';
import { composeInvitationEmail, isEmailAvailable } from './email-service';

export interface SecureInvitation {
  id: string;
  email: string;
  token: string;
  invited_by_user_id: string | null;
  invited_by_workspace_id: string | null;
  prefill_name: string | null;
  prefill_role_archetypes: string[] | null;
  prefill_source_notes: string | null;
  status: 'pending' | 'sent' | 'opened' | 'completed' | 'expired' | 'cancelled';
  created_at: string;
  expires_at: string;
  sent_at: string | null;
  opened_at: string | null;
  completed_at: string | null;
  person_id: string | null;
}

export interface CreateInvitationParams {
  email: string;
  workspaceId: string;
  userId: string;
  prefillName?: string;
  prefillRoleArchetypes?: string[];
  prefillSourceNotes?: string;
  expiresInDays?: number;
  // Additional params for email
  inviterName?: string;
  companyName?: string;
  personalMessage?: string;
  sendEmail?: boolean; // Default: true if email is configured
}

/**
 * Create a secure invitation with cryptographically random token
 */
export async function createSecureInvitation(
  params: CreateInvitationParams
): Promise<{ success: true; data: SecureInvitation } | { success: false; error: string }> {
  try {
    const {
      email,
      workspaceId,
      userId,
      prefillName,
      prefillRoleArchetypes,
      prefillSourceNotes,
      expiresInDays = 7,
      inviterName,
      companyName,
      personalMessage,
      sendEmail = await isEmailAvailable(),
    } = params;

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return { success: false, error: 'Invalid email format' };
    }

    // Check if email already has a pending invite from this workspace
    const { data: existingInvite } = await supabase
      .from('people_invites')
      .select('id, status, expires_at')
      .eq('email', email.toLowerCase())
      .eq('invited_by_workspace_id', workspaceId)
      .in('status', ['pending', 'sent'])
      .maybeSingle();

    if (existingInvite) {
      // Check if existing invite is expired
      const expiresAt = new Date(existingInvite.expires_at);
      if (expiresAt > new Date()) {
        return { success: false, error: 'An active invite is already pending for this email' };
      }
      // If expired, we'll create a new one
    }

    // Calculate expiration date
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + expiresInDays);

    // Create invitation (token is auto-generated by database)
    const { data: invitation, error } = await supabase
      .from('people_invites')
      .insert({
        email: email.toLowerCase(),
        invited_by_user_id: userId,
        invited_by_workspace_id: workspaceId,
        prefill_name: prefillName || null,
        prefill_role_archetypes: prefillRoleArchetypes || null,
        prefill_source_notes: prefillSourceNotes || null,
        status: 'pending',
        expires_at: expiresAt.toISOString(),
      })
      .select()
      .single();

    if (error) {
      console.error('[InvitationService] Create error:', error);
      return { success: false, error: 'Failed to create invitation' };
    }

    // Send email if configured and requested
    if (sendEmail && inviterName && companyName) {
      const invitationLink = generateInvitationLink(invitation.token);

      const emailResult = await composeInvitationEmail(email, {
        recipientName: prefillName || 'there',
        companyName,
        position: prefillRoleArchetypes?.join(', ') || 'Team Member',
        proposedRate: 0, // Rate can be negotiated on platform
        rateType: 'daily',
        senderName: inviterName,
        invitationLink,
        personalMessage,
        expiresInDays,
      });

      if (emailResult.sent) {
        // Mark invitation as sent
        await markInvitationAsSent(invitation.id);
        console.log(`[InvitationService] Email sent successfully to ${email}`);
      } else {
        console.warn(`[InvitationService] Email failed, but invitation created: ${emailResult.error}`);
        // Don't fail the whole operation if email fails - user can still copy the link
      }
    } else {
      console.log('[InvitationService] Email not configured or not requested - invitation link must be shared manually');
    }

    return { success: true, data: invitation as SecureInvitation };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}

/**
 * Get invitations for a workspace
 */
export async function getWorkspaceInvitations(
  workspaceId: string,
  status?: 'pending' | 'sent' | 'opened' | 'completed' | 'expired' | 'cancelled'
): Promise<{ success: true; data: SecureInvitation[] } | { success: false; error: string }> {
  try {
    let query = supabase
      .from('people_invites')
      .select('*')
      .eq('invited_by_workspace_id', workspaceId)
      .order('created_at', { ascending: false });

    if (status) {
      query = query.eq('status', status);
    }

    const { data: invitations, error } = await query;

    if (error) {
      console.error('[InvitationService] Fetch error:', error);
      return { success: false, error: 'Failed to fetch invitations' };
    }

    return { success: true, data: (invitations || []) as SecureInvitation[] };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}

/**
 * Get invitation by token (for accepting invites)
 */
export async function getInvitationByToken(
  token: string
): Promise<{ success: true; data: SecureInvitation } | { success: false; error: string }> {
  try {
    const { data: invitation, error } = await supabase
      .from('people_invites')
      .select('*')
      .eq('token', token)
      .single();

    if (error || !invitation) {
      return { success: false, error: 'Invalid or expired invitation link' };
    }

    // Check if expired
    const expiresAt = new Date(invitation.expires_at);
    if (expiresAt < new Date()) {
      // Mark as expired
      await supabase
        .from('people_invites')
        .update({ status: 'expired' })
        .eq('id', invitation.id);

      return { success: false, error: 'This invitation has expired' };
    }

    // Check if already completed
    if (invitation.status === 'completed') {
      return { success: false, error: 'This invitation has already been accepted' };
    }

    if (invitation.status === 'cancelled') {
      return { success: false, error: 'This invitation has been cancelled' };
    }

    // Mark as opened if first time
    if (invitation.status === 'pending' || invitation.status === 'sent') {
      await supabase
        .from('people_invites')
        .update({ status: 'opened', opened_at: new Date().toISOString() })
        .eq('id', invitation.id);
    }

    return { success: true, data: invitation as SecureInvitation };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}

/**
 * Mark invitation as sent (after email is successfully sent)
 */
export async function markInvitationAsSent(
  invitationId: string
): Promise<{ success: true } | { success: false; error: string }> {
  try {
    const { error } = await supabase
      .from('people_invites')
      .update({
        status: 'sent',
        sent_at: new Date().toISOString(),
      })
      .eq('id', invitationId);

    if (error) {
      console.error('[InvitationService] Mark sent error:', error);
      return { success: false, error: 'Failed to update invitation status' };
    }

    return { success: true };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}

/**
 * Mark invitation as completed (after user accepts)
 */
export async function markInvitationAsCompleted(
  invitationId: string,
  personId: string
): Promise<{ success: true } | { success: false; error: string }> {
  try {
    const { error } = await supabase
      .from('people_invites')
      .update({
        status: 'completed',
        completed_at: new Date().toISOString(),
        person_id: personId,
      })
      .eq('id', invitationId);

    if (error) {
      console.error('[InvitationService] Mark completed error:', error);
      return { success: false, error: 'Failed to update invitation status' };
    }

    return { success: true };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}

/**
 * Cancel an invitation
 */
export async function cancelInvitation(
  invitationId: string,
  workspaceId: string
): Promise<{ success: true } | { success: false; error: string }> {
  try {
    // Verify invitation belongs to workspace
    const { data: invitation } = await supabase
      .from('people_invites')
      .select('id, status')
      .eq('id', invitationId)
      .eq('invited_by_workspace_id', workspaceId)
      .single();

    if (!invitation) {
      return { success: false, error: 'Invitation not found' };
    }

    if (invitation.status === 'completed') {
      return { success: false, error: 'Cannot cancel a completed invitation' };
    }

    const { error } = await supabase
      .from('people_invites')
      .update({ status: 'cancelled' })
      .eq('id', invitationId);

    if (error) {
      console.error('[InvitationService] Cancel error:', error);
      return { success: false, error: 'Failed to cancel invitation' };
    }

    return { success: true };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}

/**
 * Generate invitation link
 */
export function generateInvitationLink(token: string): string {
  const baseUrl = process.env.EXPO_PUBLIC_APP_URL || 'https://app.fractionalfoundry.com';
  return `${baseUrl}/join/${token}`;
}

/**
 * Clean up expired invitations (run periodically)
 */
export async function cleanupExpiredInvitations(): Promise<{ success: true; count: number } | { success: false; error: string }> {
  try {
    const { data, error } = await supabase
      .from('people_invites')
      .update({ status: 'expired' })
      .lt('expires_at', new Date().toISOString())
      .in('status', ['pending', 'sent', 'opened'])
      .select();

    if (error) {
      console.error('[InvitationService] Cleanup error:', error);
      return { success: false, error: 'Failed to cleanup expired invitations' };
    }

    return { success: true, count: data?.length || 0 };
  } catch (error) {
    console.error('[InvitationService] Unexpected error:', error);
    return { success: false, error: 'An unexpected error occurred' };
  }
}
