// Seed data for UK manufacturing suppliers
// This creates a shared supplier network across all Centaur OS workspaces

import { v4 as uuidv4 } from 'uuid';
import type { Supplier, ManufacturingCapability } from '@/types';

export const UK_SUPPLIERS: Omit<Supplier, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Proto Labs UK',
    description: 'Digital manufacturing for custom prototypes and low-volume production parts',
    detailedDescription: 'Proto Labs is the world\'s fastest digital manufacturing source for custom prototypes and on-demand production parts. Our automated quoting and manufacturing systems transform your digital designs into custom parts in as fast as 1 day. We offer CNC machining, injection molding, 3D printing, and sheet metal fabrication with no minimum order quantities.',
    capabilities: [
      'CNC Machining',
      'Injection Molding',
      'Additive Manufacturing - Plastic',
      'Additive Manufacturing - Metal',
      'Sheet Metal Fabrication',
    ],
    region: 'UK',
    location: {
      city: 'Telford',
      country: 'United Kingdom',
      postcode: 'TF3 3AQ',
    },
    contact: {
      email: 'customerservice@protolabs.co.uk',
      phone: '+44 1952 683047',
      website: 'https://www.protolabs.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.5,
    reviewCount: 127,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1999,
      employeeCount: '500-1000',
      priceRange: 'premium',
    },
    specialties: [
      'Rapid prototyping (1-3 day turnaround)',
      'Bridge tooling for injection molding',
      'Complex 5-axis CNC machining',
      'Metal 3D printing (DMLS)',
    ],
    materials: [
      'Aluminium alloys (6061, 7075)',
      'Stainless steel (303, 316)',
      'Engineering plastics (ABS, PC, Nylon)',
      'Medical-grade materials (PEEK, PPSU)',
    ],
    industries: [
      'Medical devices',
      'Aerospace',
      'Consumer electronics',
      'Automotive',
      'Robotics',
    ],
    caseStudies: [
      {
        title: 'Medical Ventilator Component Rapid Production',
        client: 'UK Medical Device Startup',
        challenge: 'Needed 500 ventilator housing components produced in 2 weeks during COVID-19 pandemic',
        solution: 'Used rapid injection molding with aluminum tooling to produce parts in 10 days',
        results: [
          'Parts delivered in 10 days vs 8-week industry standard',
          '100% first-article inspection pass rate',
          'Saved £50,000 in tooling costs vs steel tooling',
        ],
      },
      {
        title: 'Aerospace Bracket Lightweighting',
        client: 'Drone Manufacturer',
        challenge: 'Aluminum brackets too heavy, needed 40% weight reduction',
        solution: 'Redesigned for CNC machining with topology optimization, produced in 2 days',
        results: [
          '42% weight reduction achieved',
          '3x faster than traditional machining',
          'Met all strength requirements',
        ],
      },
    ],
    pricing: {
      setup: 'Free instant online quotes',
      perUnit: 'Varies by geometry - typically £50-500/part for CNC',
      minimumProject: '£100',
      notes: 'Volume discounts available. No tooling costs for prototypes.',
    },
    qualityControl: {
      processes: [
        'First article inspection (FAI)',
        'In-process quality checks',
        'CMM measurement',
        'Material certification',
      ],
      certifications: ['ISO 9001:2015', 'ISO 13485', 'AS9100'],
      defectRate: '< 0.5% defect rate',
    },
    equipment: {
      machines: [
        '100+ CNC mills and lathes',
        '50+ injection molding presses',
        '30+ industrial 3D printers (SLS, SLA, DMLS)',
      ],
      capacity: '10,000+ parts per day',
      technology: [
        '5-axis CNC machining',
        'Aluminum tooling for injection molding',
        'Direct metal laser sintering (DMLS)',
      ],
    },
    support: {
      designAssistance: true,
      prototyping: true,
      engineering: true,
      logistics: true,
    },
    customerReviews: {
      rating: 4.5,
      totalReviews: 127,
      pros: [
        'Incredibly fast turnaround times',
        'High quality parts',
        'Easy online quoting system',
        'Great customer service',
      ],
      cons: [
        'Premium pricing',
        'Limited to their material selection',
        'Not cost-effective for high volumes',
      ],
      testimonials: [
        {
          company: 'MedTech Innovations Ltd',
          quote: 'Proto Labs saved our product launch. We got injection molded parts in 5 days that would have taken 8 weeks elsewhere.',
          author: 'Sarah Chen',
          role: 'CEO',
        },
        {
          company: 'Robotics UK',
          quote: 'The quality is excellent and the speed is unmatched. Perfect for rapid iteration during product development.',
          author: 'James Miller',
          role: 'Chief Engineer',
        },
      ],
    },
  },
  {
    name: 'Omega Plastics',
    description: 'Injection moulding specialists for production volumes from 1,000 to 1,000,000+ units',
    capabilities: [
      'Injection Molding',
      'Overmolding',
      'Insert Molding',
      'Ultrasonic Welding',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Telford',
      country: 'United Kingdom',
      postcode: 'TF3 5DN',
    },
    contact: {
      email: 'enquiries@omegaplastics.co.uk',
      phone: '+44 1952 607000',
      website: 'https://www.omegaplastics.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 1000,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.7,
    reviewCount: 89,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1979,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Laser Master UK',
    description: 'Precision laser cutting and engraving services for metals, plastics, and composites',
    capabilities: [
      'Laser Cutting',
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Powder Coating',
      'Screen Printing',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B6 7BA',
    },
    contact: {
      email: 'sales@lasermaster.co.uk',
      phone: '+44 121 359 5888',
      website: 'https://www.lasermaster.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.6,
    reviewCount: 156,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1997,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'RPWORLD UK',
    description: 'One-stop rapid prototyping and low-volume manufacturing service',
    capabilities: [
      'Additive Manufacturing - Plastic',
      'CNC Machining',
      'Vacuum Forming',
      'Injection Molding',
      'Sheet Metal Fabrication',
      'Anodizing',
      'Powder Coating',
    ],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC1V 2NX',
    },
    contact: {
      email: 'info@rpworld.co.uk',
      phone: '+44 20 3322 3910',
      website: 'https://www.rpworld.co.uk',
    },
    certifications: ['ISO 9001:2015', 'RoHS'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.4,
    reviewCount: 92,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2010,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Newbury Electronics',
    description: 'PCB assembly and electronic manufacturing services',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Cable Assembly',
      'Wire Harness Assembly',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Newbury',
      country: 'United Kingdom',
      postcode: 'RG14 2PZ',
    },
    contact: {
      email: 'sales@newburyelectronics.co.uk',
      phone: '+44 1635 40347',
      website: 'https://www.newburyelectronics.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'IPC-A-610', 'AS9100'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.8,
    reviewCount: 74,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1973,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Formero',
    description: 'Vacuum forming, pressure forming and thermoforming specialists',
    capabilities: [
      'Vacuum Forming',
      'Compression Molding',
      'CNC Machining',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Sheffield',
      country: 'United Kingdom',
      postcode: 'S9 2YL',
    },
    contact: {
      email: 'info@formero.co.uk',
      phone: '+44 114 244 4500',
      website: 'https://www.formero.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.5,
    reviewCount: 63,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1990,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'MJN Neuro',
    description: 'Specialist in EPS molding, EPP molding, and expanded foam products',
    capabilities: [
      'EPS Molding',
      'EPP Molding',
      'Heat Chest Molding',
      'CNC Machining',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Leicester',
      country: 'United Kingdom',
      postcode: 'LE4 1AW',
    },
    contact: {
      email: 'sales@mjnneuro.co.uk',
      phone: '+44 116 266 8989',
      website: 'https://www.mjnneuro.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 5,
    status: 'verified',
    rating: 4.6,
    reviewCount: 51,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1987,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'EMS UK',
    description: 'Full-service electronics manufacturing - from design to finished product',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Wire Harness Assembly',
      'Cable Assembly',
      'Quality Control & Testing',
      'Certification Support',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Camberley',
      country: 'United Kingdom',
      postcode: 'GU15 3YL',
    },
    contact: {
      email: 'info@emsuk.com',
      phone: '+44 1276 691371',
      website: 'https://www.emsuk.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'ISO 14001', 'IPC-A-610'],
    minimumOrderQuantity: 50,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.7,
    reviewCount: 85,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1982,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Brandauer',
    description: 'Precision stamping, tooling, and metal fabrication since 1862',
    capabilities: [
      'Sheet Metal Fabrication',
      'Die Casting',
      'CNC Machining',
      'Welding & Assembly',
      'Powder Coating',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B19 2XF',
    },
    contact: {
      email: 'sales@brandauer.co.uk',
      phone: '+44 121 359 3646',
      website: 'https://www.brandauer.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'IATF 16949'],
    minimumOrderQuantity: 5000,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.8,
    reviewCount: 67,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1862,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Tharsus',
    description: 'Robotic and automated assembly solutions with full production capabilities',
    capabilities: [
      'Electronic Assembly',
      'Final Assembly & Packaging',
      'Welding & Assembly',
      'Quality Control & Testing',
      'Design for Manufacturing',
      'Certification Support',
    ],
    region: 'UK',
    location: {
      city: 'Blyth',
      country: 'United Kingdom',
      postcode: 'NE24 1LZ',
    },
    contact: {
      email: 'hello@tharsus.co.uk',
      phone: '+44 1670 734 334',
      website: 'https://www.tharsus.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'ISO 45001'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 8,
    status: 'verified',
    rating: 4.9,
    reviewCount: 42,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2007,
      employeeCount: '250-500',
      priceRange: 'premium',
    },
  },
  {
    name: '3D Hubs (Protolabs Network)',
    description: 'On-demand manufacturing network connecting designers with verified UK manufacturers for rapid prototyping',
    capabilities: [
      'Additive Manufacturing - Plastic',
      'Additive Manufacturing - Metal',
      'CNC Machining',
      'Injection Molding',
      'Sheet Metal Fabrication',
    ],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC2A 4NE',
    },
    contact: {
      email: 'support@hubs.com',
      phone: '+44 20 3695 2676',
      website: 'https://www.hubs.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.6,
    reviewCount: 234,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2013,
      employeeCount: '250-500',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'XYZ Machine Tools',
    description: 'CNC machine tool supplier offering contract machining and manufacturing services',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Design for Manufacturing',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Buxton',
      country: 'United Kingdom',
      postcode: 'SK17 6SF',
    },
    contact: {
      email: 'sales@xyzmachinetools.com',
      phone: '+44 1298 872200',
      website: 'https://www.xyzmachinetools.com',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.5,
    reviewCount: 78,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1961,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Paragon Rapid Technologies',
    description: 'Additive manufacturing specialists offering SLA, SLS, and FDM 3D printing with post-processing',
    capabilities: [
      'Additive Manufacturing - Plastic',
      'Additive Manufacturing - Metal',
      'Vacuum Casting',
      'CNC Machining',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Wellingborough',
      country: 'United Kingdom',
      postcode: 'NN8 6BA',
    },
    contact: {
      email: 'info@paragon-rt.co.uk',
      phone: '+44 1933 276047',
      website: 'https://www.paragon-rt.co.uk',
    },
    certifications: ['ISO 9001:2015', 'AS9100'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.7,
    reviewCount: 95,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2000,
      employeeCount: '50-100',
      priceRange: 'premium',
    },
  },
  {
    name: 'Olympus Metal Finishing',
    description: 'Specialist metal finishing services including anodizing, plating, and powder coating',
    capabilities: [
      'Anodizing',
      'Electroplating',
      'Powder Coating',
      'Sheet Metal Fabrication',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Bristol',
      country: 'United Kingdom',
      postcode: 'BS5 9QB',
    },
    contact: {
      email: 'sales@olympusmf.com',
      phone: '+44 117 955 2481',
      website: 'https://www.olympusmf.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'NADCAP'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.8,
    reviewCount: 112,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1992,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Abbey Plastics',
    description: 'Custom injection moulding and toolmaking for low to high volume production',
    capabilities: [
      'Injection Molding',
      'Insert Molding',
      'Overmolding',
      'Ultrasonic Welding',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Walsall',
      country: 'United Kingdom',
      postcode: 'WS10 7LR',
    },
    contact: {
      email: 'sales@abbeyplastics.co.uk',
      phone: '+44 1922 743050',
      website: 'https://www.abbeyplastics.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 5,
    status: 'verified',
    rating: 4.6,
    reviewCount: 87,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1967,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'European Springs & Pressings',
    description: 'Precision spring manufacturing and wire forming specialists',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Die Casting',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Redruth',
      country: 'United Kingdom',
      postcode: 'TR15 3RQ',
    },
    contact: {
      email: 'sales@europeansprings.com',
      phone: '+44 1209 314831',
      website: 'https://www.europeansprings.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.7,
    reviewCount: 103,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1948,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Airedale Springs',
    description: 'Precision spring and wireform manufacturer for engineering applications',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Welding & Assembly',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Leeds',
      country: 'United Kingdom',
      postcode: 'LS12 6JW',
    },
    contact: {
      email: 'sales@airedalesprings.co.uk',
      phone: '+44 113 246 3747',
      website: 'https://www.airedalesprings.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 50,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.5,
    reviewCount: 68,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1945,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Fastenright Ltd',
    description: 'Specialist fixings and fasteners supplier with custom manufacturing capabilities',
    capabilities: [
      'CNC Machining',
      'Die Casting',
      'Electroplating',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Andover',
      country: 'United Kingdom',
      postcode: 'SP10 2NJ',
    },
    contact: {
      email: 'sales@fastenright.com',
      phone: '+44 1264 333533',
      website: 'https://www.fastenright.com',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1000,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.4,
    reviewCount: 56,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1984,
      employeeCount: '10-50',
      priceRange: 'budget',
    },
  },
  {
    name: 'V&F Sheet Metal',
    description: 'Precision sheet metal fabrication specialists with laser cutting and folding capabilities',
    capabilities: [
      'Sheet Metal Fabrication',
      'Laser Cutting',
      'Powder Coating',
      'Welding & Assembly',
      'CNC Machining',
    ],
    region: 'UK',
    location: {
      city: 'Witney',
      country: 'United Kingdom',
      postcode: 'OX28 4FF',
    },
    contact: {
      email: 'sales@vandf.co.uk',
      phone: '+44 1993 774444',
      website: 'https://www.vandf.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.8,
    reviewCount: 142,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1971,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Dean Group International',
    description: 'Investment casting and precision machining for complex metal components',
    capabilities: [
      'Investment Casting',
      'Die Casting',
      'CNC Machining',
      'Anodizing',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Manchester',
      country: 'United Kingdom',
      postcode: 'M27 8UJ',
    },
    contact: {
      email: 'sales@deangroupinternational.com',
      phone: '+44 161 775 7300',
      website: 'https://www.deangroupinternational.com',
    },
    certifications: ['ISO 9001:2015', 'AS9100', 'ISO 14001'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.7,
    reviewCount: 91,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1963,
      employeeCount: '250-500',
      priceRange: 'premium',
    },
  },
  {
    name: 'Gooch & Housego',
    description: 'Precision optical components and photonics manufacturing',
    capabilities: [
      'CNC Machining',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
      'Certification Support',
    ],
    region: 'UK',
    location: {
      city: 'Ilminster',
      country: 'United Kingdom',
      postcode: 'TA19 9DH',
    },
    contact: {
      email: 'sales@goochandhousego.com',
      phone: '+44 1460 256440',
      website: 'https://www.goochandhousego.com',
    },
    certifications: ['ISO 9001:2015', 'AS9100', 'ISO 14001'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 8,
    status: 'verified',
    rating: 4.9,
    reviewCount: 48,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1948,
      employeeCount: '500-1000',
      priceRange: 'premium',
    },
  },
  {
    name: 'Stadium Export',
    description: 'Contract electronics manufacturer specializing in PCB assembly and box build',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Cable Assembly',
      'Wire Harness Assembly',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Poole',
      country: 'United Kingdom',
      postcode: 'BH17 7BA',
    },
    contact: {
      email: 'sales@stadium.co.uk',
      phone: '+44 1202 422000',
      website: 'https://www.stadium.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'IPC-A-610'],
    minimumOrderQuantity: 20,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.6,
    reviewCount: 83,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1969,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Qualitetch',
    description: 'Chemical etching and photo etching specialists for precision metal components',
    capabilities: [
      'Sheet Metal Fabrication',
      'Laser Cutting',
      'Electroforming',
      'CNC Machining',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B42 2LH',
    },
    contact: {
      email: 'sales@qualitetch.co.uk',
      phone: '+44 121 333 6840',
      website: 'https://www.qualitetch.co.uk',
    },
    certifications: ['ISO 9001:2015', 'AS9100'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.7,
    reviewCount: 79,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1982,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'J & L Engineering',
    description: 'CNC turning and milling specialists for precision engineering components',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Welding & Assembly',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Rotherham',
      country: 'United Kingdom',
      postcode: 'S63 5DB',
    },
    contact: {
      email: 'sales@jandlengineering.co.uk',
      phone: '+44 1709 873007',
      website: 'https://www.jandlengineering.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.5,
    reviewCount: 64,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1994,
      employeeCount: '10-50',
      priceRange: 'budget',
    },
  },
  {
    name: 'Grainger & Worrall',
    description: 'Aluminium and magnesium casting specialists with full machining capabilities',
    capabilities: [
      'Die Casting',
      'Investment Casting',
      'CNC Machining',
      'Powder Coating',
      'Anodizing',
    ],
    region: 'UK',
    location: {
      city: 'Bridgnorth',
      country: 'United Kingdom',
      postcode: 'WV15 5HP',
    },
    contact: {
      email: 'sales@gwcastings.co.uk',
      phone: '+44 1746 765432',
      website: 'https://www.gwcastings.co.uk',
    },
    certifications: ['ISO 9001:2015', 'IATF 16949', 'ISO 14001'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 8,
    status: 'verified',
    rating: 4.8,
    reviewCount: 96,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1865,
      employeeCount: '250-500',
      priceRange: 'premium',
    },
  },
  {
    name: 'Weston Aerospace',
    description: 'Precision machining and fabrication for aerospace and defense sectors',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Welding & Assembly',
      'Quality Control & Testing',
      'Certification Support',
    ],
    region: 'UK',
    location: {
      city: 'Portland',
      country: 'United Kingdom',
      postcode: 'DT5 2JT',
    },
    contact: {
      email: 'sales@westonaerospace.com',
      phone: '+44 1305 824834',
      website: 'https://www.westonaerospace.com',
    },
    certifications: ['ISO 9001:2015', 'AS9100', 'NADCAP'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.9,
    reviewCount: 57,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1992,
      employeeCount: '100-250',
      priceRange: 'premium',
    },
  },
  {
    name: 'Airedale Group',
    description: 'Full-service manufacturer offering PCB assembly, cable assembly, and box build',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Cable Assembly',
      'Wire Harness Assembly',
      'Final Assembly & Packaging',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Halifax',
      country: 'United Kingdom',
      postcode: 'HX3 5AY',
    },
    contact: {
      email: 'sales@airedale-group.com',
      phone: '+44 1422 320420',
      website: 'https://www.airedale-group.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'IPC-A-610', 'ISO 14001'],
    minimumOrderQuantity: 50,
    leadTimeWeeks: 5,
    status: 'verified',
    rating: 4.7,
    reviewCount: 88,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1972,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Plastic Concepts',
    description: 'Injection moulding and product design specialists for consumer products',
    capabilities: [
      'Injection Molding',
      'Overmolding',
      'Insert Molding',
      'Design for Manufacturing',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Leicester',
      country: 'United Kingdom',
      postcode: 'LE8 0RX',
    },
    contact: {
      email: 'info@plasticconcepts.co.uk',
      phone: '+44 116 277 6677',
      website: 'https://www.plasticconcepts.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1000,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.5,
    reviewCount: 72,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1988,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Cooksongold',
    description: 'Precious metals casting, finishing and jewellery manufacturing services',
    capabilities: [
      'Investment Casting',
      'CNC Machining',
      'Electroplating',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B1 3DR',
    },
    contact: {
      email: 'sales@cooksongold.com',
      phone: '+44 345 100 1122',
      website: 'https://www.cooksongold.com',
    },
    certifications: ['ISO 9001:2015', 'RJC'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.6,
    reviewCount: 154,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1873,
      employeeCount: '100-250',
      priceRange: 'premium',
    },
  },
  {
    name: 'Produmax',
    description: 'Automated manufacturing solutions with robotic assembly and production line integration',
    capabilities: [
      'Electronic Assembly',
      'Final Assembly & Packaging',
      'Welding & Assembly',
      'Quality Control & Testing',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Coventry',
      country: 'United Kingdom',
      postcode: 'CV6 4AP',
    },
    contact: {
      email: 'enquiries@produmax.co.uk',
      phone: '+44 24 7666 8844',
      website: 'https://www.produmax.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'IATF 16949'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 10,
    status: 'verified',
    rating: 4.8,
    reviewCount: 65,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2003,
      employeeCount: '100-250',
      priceRange: 'premium',
    },
  },
  // ==================== BUSINESS BANKS FOR SMEs ====================
  {
    name: 'Tide Business Banking',
    description: 'Digital business banking designed for SMEs with instant account opening and no monthly fees',
    detailedDescription: 'Tide is the UK\'s leading digital business banking platform built specifically for small businesses and startups. Open a business account in minutes, manage finances on mobile, and access integrated accounting tools. No credit checks, no monthly fees on the Free plan, and instant payments.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC1V 2NX',
    },
    contact: {
      email: 'hello@tide.co',
      phone: '+44 20 3608 6846',
      website: 'https://www.tide.co',
    },
    certifications: ['FCA Regulated', 'FSCS Protected'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 0,
    status: 'verified',
    rating: 4.6,
    reviewCount: 2847,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2015,
      employeeCount: '250-500',
      priceRange: 'budget',
      notes: 'Digital business bank account',
    },
    specialties: [
      'Instant account opening (10 minutes)',
      'Free business account (no monthly fees)',
      'Integrated accounting software (Xero, QuickBooks)',
      'Multi-currency accounts',
      'Corporate cards for team',
    ],
    industries: [
      'Startups',
      'SMEs',
      'Limited companies',
      'Sole traders',
      'Freelancers',
    ],
    pricing: {
      setup: 'Free account opening',
      perUnit: 'Free plan: £0/month. Plus plan: £9.99/month',
      minimumProject: '£0',
      notes: 'Free transactions, 1% fee on international payments. Plus plan includes unlimited transactions.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.6,
      totalReviews: 2847,
      pros: [
        'Instant account setup',
        'No monthly fees on Free plan',
        'Great mobile app',
        'Integrated accounting',
      ],
      cons: [
        'Limited branch access',
        'Phone support can be slow',
        'Some features require paid plan',
      ],
      testimonials: [
        {
          company: 'TechStart Ltd',
          quote: 'Opened our account in 10 minutes and had our first invoice paid the same day. Perfect for startups.',
          author: 'Emma Watson',
          role: 'Founder',
        },
        {
          company: 'Design Studio UK',
          quote: 'The Xero integration saves us hours every month. Best business banking app we\'ve used.',
          author: 'David Chen',
          role: 'Managing Director',
        },
      ],
    },
  },
  {
    name: 'Starling Bank Business',
    description: 'Award-winning digital business bank with integrated accounting and spending controls',
    detailedDescription: 'Starling Bank offers full UK business banking with no monthly fees, real-time notifications, and powerful spending analytics. Fully licensed UK bank with FSCS protection. Integrate with Xero, FreeAgent, and other accounting software. Get corporate debit cards for your team with customizable spending limits.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC2V 7NG',
    },
    contact: {
      email: 'business@starlingbank.com',
      phone: '+44 20 3322 9500',
      website: 'https://www.starlingbank.com/business-account',
    },
    certifications: ['FCA Regulated', 'FSCS Protected', 'PRA Authorized'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 0,
    status: 'verified',
    rating: 4.8,
    reviewCount: 1923,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2014,
      employeeCount: '1000-2000',
      priceRange: 'mid-range',
      notes: 'Full UK banking license',
    },
    specialties: [
      'No monthly fees on business account',
      'Real-time spending notifications',
      'Team spending controls and cards',
      'Built-in invoicing and accounting',
      'Savings pots with competitive interest',
    ],
    industries: [
      'Startups',
      'SMEs',
      'Limited companies',
      'Partnerships',
      'Freelancers',
    ],
    pricing: {
      setup: 'Free',
      perUnit: '£0/month',
      minimumProject: '£0',
      notes: 'Free UK transactions. Small fees on international payments and cash deposits.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.8,
      totalReviews: 1923,
      pros: [
        'True UK bank with full protection',
        'Excellent mobile app',
        'No hidden fees',
        'Great customer service',
      ],
      cons: [
        'No physical branches',
        'Cash deposits have fees',
        'Limited business loan options',
      ],
    },
  },
  {
    name: 'NatWest Business Banking',
    description: 'Traditional high-street bank with comprehensive SME banking and relationship management',
    detailedDescription: 'NatWest provides full-service business banking for UK SMEs with dedicated relationship managers, business loans, overdrafts, and nationwide branch network. Access to business support programs, startup accelerators, and networking events. Ideal for established businesses needing comprehensive banking services.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'Edinburgh',
      country: 'United Kingdom',
      postcode: 'EH2 2YB',
    },
    contact: {
      email: 'business.banking@natwest.com',
      phone: '+44 345 030 3605',
      website: 'https://www.natwestbusiness.com',
    },
    certifications: ['FCA Regulated', 'FSCS Protected', 'PRA Authorized'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.3,
    reviewCount: 1247,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1968,
      employeeCount: '10000+',
      priceRange: 'mid-range',
      notes: 'High-street bank with branches',
    },
    specialties: [
      'Dedicated relationship managers',
      'Business loans and overdrafts (£1k-£1M)',
      'Nationwide branch network',
      'Startup accelerator programs',
      'International payments and trade finance',
    ],
    industries: [
      'Established SMEs',
      'Growing businesses',
      'Export businesses',
      'Manufacturing',
      'Professional services',
    ],
    pricing: {
      setup: 'Free for 18 months for new startups',
      perUnit: '£6-£10/month after free period',
      minimumProject: '£0',
      notes: 'Transaction fees apply. Business Lending available from 3.9% APR.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.3,
      totalReviews: 1247,
      pros: [
        'Physical branches for cash deposits',
        'Relationship manager support',
        'Business loan access',
        'Established reputation',
      ],
      cons: [
        'Monthly fees after free period',
        'Slower online features vs digital banks',
        'More paperwork required',
      ],
    },
  },
  // ==================== LAWYERS FOR STARTUPS & SMEs ====================
  {
    name: 'SeedLegals',
    description: 'Legal platform for startups covering incorporation, fundraising, employee options, and contracts',
    detailedDescription: 'SeedLegals is the UK\'s #1 platform for startup legal work. Handle company formation, SEIS/EIS advance assurance, fundraising rounds, EMI option schemes, shareholder agreements, and contracts all online. Transparent fixed pricing, fast turnaround, and backed by real lawyers for complex questions.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC1V 2NX',
    },
    contact: {
      email: 'hello@seedlegals.com',
      phone: '+44 20 3535 1373',
      website: 'https://www.seedlegals.com',
    },
    certifications: ['SRA Regulated', 'ISO 27001'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.9,
    reviewCount: 3421,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2016,
      employeeCount: '100-250',
      priceRange: 'mid-range',
      notes: 'Online legal platform for startups',
    },
    specialties: [
      'Company formation (£99)',
      'SEIS/EIS advance assurance',
      'Fundraising rounds (Seed to Series A)',
      'EMI employee option schemes',
      'Shareholder agreements and ASAs',
    ],
    industries: [
      'Pre-seed startups',
      'Seed-stage companies',
      'Series A companies',
      'Tech startups',
      'Hardware startups',
    ],
    caseStudies: [
      {
        title: 'Series A Round in 48 Hours',
        client: 'AI SaaS Startup',
        challenge: 'Needed to close £2M Series A round quickly with 3 investors',
        solution: 'Used SeedLegals platform to generate all legal docs, manage investor signatures, and complete Companies House filings',
        results: [
          'Round closed in 48 hours vs 4-6 weeks',
          'Saved £15,000 in legal fees',
          'All documents signed electronically',
        ],
      },
      {
        title: 'SEIS Advance Assurance in 10 Days',
        client: 'Hardware Startup',
        challenge: 'Needed SEIS approval before investor deadline',
        solution: 'SeedLegals prepared and submitted SEIS advance assurance application',
        results: [
          'SEIS approval in 10 days',
          'Investors able to claim 50% tax relief',
          '£300k round closed successfully',
        ],
      },
    ],
    pricing: {
      setup: '£99 company formation',
      perUnit: 'Fundraising: £999-£2,999 depending on round size',
      minimumProject: '£99',
      notes: 'Fixed pricing. EMI schemes from £599. Ongoing subscription £39/month for post-fundraising support.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.9,
      totalReviews: 3421,
      pros: [
        'Transparent fixed pricing',
        'Fast online process',
        'Backed by real lawyers',
        'Perfect for fundraising',
      ],
      cons: [
        'Limited for complex IP issues',
        'Subscription required for ongoing support',
        'Best for standard startup structures',
      ],
      testimonials: [
        {
          company: 'Quantum Robotics',
          quote: 'Closed our £1.5M seed round in a week. SeedLegals made it incredibly simple.',
          author: 'Sarah Ahmed',
          role: 'CEO & Founder',
        },
      ],
    },
  },
  {
    name: 'Taylor Vinters',
    description: 'Leading technology and life sciences law firm specializing in startups and scaleups',
    detailedDescription: 'Taylor Vinters is one of the UK\'s premier law firms for tech and life sciences companies. Providing full-service legal support including corporate, commercial, IP, employment, and fundraising. Known for working with high-growth startups from formation through IPO. Strong connections with VC community.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'Cambridge',
      country: 'United Kingdom',
      postcode: 'CB2 1SJ',
    },
    contact: {
      email: 'info@taylorvinters.com',
      phone: '+44 1223 423444',
      website: 'https://www.taylorvinters.com',
    },
    certifications: ['SRA Regulated', 'Legal 500 Ranked'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.7,
    reviewCount: 286,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1990,
      employeeCount: '250-500',
      priceRange: 'premium',
      notes: 'Full-service law firm',
    },
    specialties: [
      'VC fundraising (Seed to Series C)',
      'IP portfolio management and patent strategy',
      'M&A transactions',
      'Employment law and stock options',
      'Commercial contracts and licensing',
    ],
    industries: [
      'Deep tech',
      'Life sciences',
      'Hardware & IoT',
      'SaaS',
      'Climate tech',
    ],
    pricing: {
      setup: 'Varies by engagement',
      perUnit: '£300-£600/hour for partners',
      minimumProject: '£5,000',
      notes: 'Fixed fee arrangements available for fundraising rounds. Free initial consultation for startups.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.7,
      totalReviews: 286,
      pros: [
        'Deep tech and hardware expertise',
        'Strong VC network',
        'Excellent for complex IP',
        'Partner-level attention',
      ],
      cons: [
        'Premium pricing',
        'Minimum project sizes',
        'Better for Series A+ companies',
      ],
    },
  },
  {
    name: 'Keystone Law',
    description: 'Flexible commercial law firm with specialist startup and IP lawyers',
    detailedDescription: 'Keystone Law operates a unique model with experienced lawyers working flexibly across the UK. Specializing in commercial contracts, IP protection, employment law, and corporate transactions for SMEs and startups. Lower overheads mean competitive pricing with Big Law expertise.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC4R 3TE',
    },
    contact: {
      email: 'info@keystonelaw.com',
      phone: '+44 20 3319 3700',
      website: 'https://www.keystonelaw.com',
    },
    certifications: ['SRA Regulated', 'Listed on AIM'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.6,
    reviewCount: 412,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2002,
      employeeCount: '500-1000',
      priceRange: 'mid-range',
      notes: 'Distributed law firm model',
    },
    specialties: [
      'Commercial contracts and NDAs',
      'IP protection (trademarks, patents, copyright)',
      'Employment contracts and disputes',
      'Fundraising and shareholder agreements',
      'Data protection and GDPR compliance',
    ],
    industries: [
      'Startups',
      'SMEs',
      'Creative industries',
      'Technology',
      'Manufacturing',
    ],
    pricing: {
      setup: 'No upfront fees',
      perUnit: '£200-£450/hour depending on specialist',
      minimumProject: '£500',
      notes: 'Transparent hourly rates. Fixed fee packages available for common startup needs.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.6,
      totalReviews: 412,
      pros: [
        'Competitive pricing',
        'Flexible engagement',
        'Experienced lawyers',
        'Good for ongoing legal needs',
      ],
      cons: [
        'No physical offices',
        'Less suited for complex M&A',
        'Multiple lawyers for different issues',
      ],
    },
  },
  // ==================== ACCOUNTANTS FOR STARTUPS & SMEs ====================
  {
    name: 'Crunch',
    description: 'Online accountancy platform for freelancers, contractors, and small businesses',
    detailedDescription: 'Crunch is the UK\'s leading online accountancy service combining smart software with real accountants. Perfect for startups, freelancers, and SMEs. Includes bookkeeping, VAT returns, payroll, self-assessment, year-end accounts, and Companies House filing. Flat monthly fee with unlimited support.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'Brighton',
      country: 'United Kingdom',
      postcode: 'BN1 4JR',
    },
    contact: {
      email: 'hello@crunch.co.uk',
      phone: '+44 1273 257 814',
      website: 'https://www.crunch.co.uk',
    },
    certifications: ['ICAEW Registered', 'ACCA Members', 'Xero Gold Partner'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 0,
    status: 'verified',
    rating: 4.7,
    reviewCount: 4829,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2009,
      employeeCount: '100-250',
      priceRange: 'budget',
      notes: 'Online accounting service',
    },
    specialties: [
      'Real-time bookkeeping and bank feeds',
      'VAT returns and MTD compliance',
      'Year-end accounts and tax filing',
      'Payroll and pension auto-enrolment',
      'R&D tax credit claims',
    ],
    industries: [
      'Freelancers and contractors',
      'Startups',
      'E-commerce businesses',
      'Professional services',
      'Small manufacturers',
    ],
    caseStudies: [
      {
        title: 'R&D Tax Credit Claim for Hardware Startup',
        client: 'IoT Device Manufacturer',
        challenge: 'First-time R&D claim for hardware development costs',
        solution: 'Crunch identified qualifying R&D expenditure and prepared detailed technical report',
        results: [
          '£47,000 R&D tax credit received',
          'Funded 6 months of additional development',
          'Annual R&D claims now part of financial planning',
        ],
      },
    ],
    pricing: {
      setup: 'Free onboarding',
      perUnit: '£29.50-£49.50/month depending on plan',
      minimumProject: '£29.50/month',
      notes: 'All-inclusive pricing. Year-end accounts included. Self-Assessment from £120. R&D claims from £795+15% success fee.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.7,
      totalReviews: 4829,
      pros: [
        'Affordable flat monthly fee',
        'Great mobile app',
        'Responsive accountants',
        'R&D tax credit expertise',
      ],
      cons: [
        'Limited for complex group structures',
        'Additional fees for some services',
        'Better for small businesses',
      ],
      testimonials: [
        {
          company: 'SmartSense Ltd',
          quote: 'Crunch helped us claim £47k in R&D tax credits we didn\'t know we were eligible for.',
          author: 'James Park',
          role: 'CTO',
        },
      ],
    },
  },
  {
    name: 'Mazuma',
    description: 'Award-winning online accountants for small businesses with transparent pricing',
    detailedDescription: 'Mazuma provides comprehensive online accounting services for UK small businesses. Includes bookkeeping, VAT, payroll, tax returns, and year-end accounts with a dedicated accountant. Cloud-based platform with real-time dashboards. Specializes in helping startups with SEIS/EIS claims and growth stage financial planning.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'Liverpool',
      country: 'United Kingdom',
      postcode: 'L3 9AG',
    },
    contact: {
      email: 'hello@mazumamoney.co.uk',
      phone: '+44 151 380 8080',
      website: 'https://www.mazumamoney.co.uk',
    },
    certifications: ['ICAEW Registered', 'Xero Platinum Partner', 'QBO ProAdvisor'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 0,
    status: 'verified',
    rating: 4.8,
    reviewCount: 3247,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2012,
      employeeCount: '50-100',
      priceRange: 'mid-range',
      notes: 'Online accountancy with dedicated accountants',
    },
    specialties: [
      'Startup packages with SEIS/EIS support',
      'Cloud accounting (Xero, QuickBooks)',
      'Management accounts and financial forecasting',
      'Investor-ready financial reporting',
      'Corporation tax and year-end compliance',
    ],
    industries: [
      'Startups seeking investment',
      'E-commerce',
      'SaaS businesses',
      'Professional services',
      'Manufacturing SMEs',
    ],
    pricing: {
      setup: 'Free consultation',
      perUnit: '£85-£195/month depending on complexity',
      minimumProject: '£85/month',
      notes: 'Year-end accounts and tax included. SEIS/EIS applications £500. Management accounts from £150/month.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.8,
      totalReviews: 3247,
      pros: [
        'Dedicated accountant assigned',
        'Great for fundraising support',
        'Transparent pricing',
        'Proactive tax planning',
      ],
      cons: [
        'More expensive than pure DIY options',
        'Limited for international entities',
        'Startup package has minimum commitment',
      ],
    },
  },
  {
    name: 'Haines Watts',
    description: 'Top 15 UK accountancy firm with specialist SME and manufacturing expertise',
    detailedDescription: 'Haines Watts is one of the UK\'s leading mid-tier accountancy firms with 34 offices nationwide. Provides comprehensive accounting, audit, tax advisory, and business consultancy services. Strong manufacturing sector expertise with R&D tax credit specialists. Ideal for established SMEs and growing hardware companies.',
    capabilities: [] as ManufacturingCapability[],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC2N 4AY',
    },
    contact: {
      email: 'info@hwca.com',
      phone: '+44 20 7025 4650',
      website: 'https://www.hwca.com',
    },
    certifications: ['ICAEW Regulated', 'Top 15 UK Firm', 'Manufacturing Specialists'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.6,
    reviewCount: 892,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1930,
      employeeCount: '1000-2000',
      priceRange: 'premium',
      notes: 'Full-service accountancy firm',
    },
    specialties: [
      'Manufacturing sector accounting',
      'R&D tax credits (£100k+ claims)',
      'Corporate finance and fundraising advisory',
      'Statutory audit and assurance',
      'International tax planning',
    ],
    industries: [
      'Manufacturing',
      'Engineering',
      'Technology',
      'Life sciences',
      'Professional services',
    ],
    caseStudies: [
      {
        title: 'R&D Tax Credit Maximization',
        client: 'Medical Device Manufacturer',
        challenge: '£2M R&D spend but never claimed tax credits',
        solution: 'Comprehensive review of 3 years of R&D activities, prepared technical documentation',
        results: [
          '£680,000 in R&D tax credits recovered',
          'Implemented ongoing R&D tracking system',
          'Annual claims now exceed £200k',
        ],
      },
    ],
    pricing: {
      setup: 'Free initial consultation',
      perUnit: 'Annual accounts: £2,000-£10,000. R&D claims: £3,000+12% success fee',
      minimumProject: '£2,000',
      notes: 'Pricing varies by company size and complexity. Monthly retainers available for ongoing CFO advisory.',
    },
    support: {
      designAssistance: false,
      prototyping: false,
      engineering: false,
      logistics: false,
    },
    customerReviews: {
      rating: 4.6,
      totalReviews: 892,
      pros: [
        'Manufacturing sector expertise',
        'Large R&D claim capability',
        'Nationwide coverage',
        'Partner-led service',
      ],
      cons: [
        'Premium pricing',
        'Better for established companies',
        'Minimum engagement sizes',
      ],
    },
  },
];

// Helper to seed suppliers into the platform
export function createSuppliersSeedData(): Record<string, Supplier> {
  const suppliers: Record<string, Supplier> = {};

  UK_SUPPLIERS.forEach((supplierData) => {
    const supplier: Supplier = {
      ...supplierData,
      id: uuidv4(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    suppliers[supplier.id] = supplier;
  });

  return suppliers;
}

// Get all unique capabilities for UI filtering
export function getAllCapabilities(): ManufacturingCapability[] {
  const capabilities = new Set<ManufacturingCapability>();
  UK_SUPPLIERS.forEach((supplier) => {
    supplier.capabilities.forEach((cap) => capabilities.add(cap));
  });
  return Array.from(capabilities).sort();
}
