// Seed data for UK manufacturing suppliers
// This creates a shared supplier network across all Centaur OS workspaces

import { v4 as uuidv4 } from 'uuid';
import type { Supplier, ManufacturingCapability } from '@/types';

export const UK_SUPPLIERS: Omit<Supplier, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Proto Labs UK',
    description: 'Digital manufacturing for custom prototypes and low-volume production parts',
    detailedDescription: 'Proto Labs is the world\'s fastest digital manufacturing source for custom prototypes and on-demand production parts. Our automated quoting and manufacturing systems transform your digital designs into custom parts in as fast as 1 day. We offer CNC machining, injection molding, 3D printing, and sheet metal fabrication with no minimum order quantities.',
    capabilities: [
      'CNC Machining',
      'Injection Molding',
      'Additive Manufacturing - Plastic',
      'Additive Manufacturing - Metal',
      'Sheet Metal Fabrication',
    ],
    region: 'UK',
    location: {
      city: 'Telford',
      country: 'United Kingdom',
      postcode: 'TF3 3AQ',
    },
    contact: {
      email: 'customerservice@protolabs.co.uk',
      phone: '+44 1952 683047',
      website: 'https://www.protolabs.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.5,
    reviewCount: 127,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1999,
      employeeCount: '500-1000',
      priceRange: 'premium',
    },
    specialties: [
      'Rapid prototyping (1-3 day turnaround)',
      'Bridge tooling for injection molding',
      'Complex 5-axis CNC machining',
      'Metal 3D printing (DMLS)',
    ],
    materials: [
      'Aluminium alloys (6061, 7075)',
      'Stainless steel (303, 316)',
      'Engineering plastics (ABS, PC, Nylon)',
      'Medical-grade materials (PEEK, PPSU)',
    ],
    industries: [
      'Medical devices',
      'Aerospace',
      'Consumer electronics',
      'Automotive',
      'Robotics',
    ],
    caseStudies: [
      {
        title: 'Medical Ventilator Component Rapid Production',
        client: 'UK Medical Device Startup',
        challenge: 'Needed 500 ventilator housing components produced in 2 weeks during COVID-19 pandemic',
        solution: 'Used rapid injection molding with aluminum tooling to produce parts in 10 days',
        results: [
          'Parts delivered in 10 days vs 8-week industry standard',
          '100% first-article inspection pass rate',
          'Saved £50,000 in tooling costs vs steel tooling',
        ],
      },
      {
        title: 'Aerospace Bracket Lightweighting',
        client: 'Drone Manufacturer',
        challenge: 'Aluminum brackets too heavy, needed 40% weight reduction',
        solution: 'Redesigned for CNC machining with topology optimization, produced in 2 days',
        results: [
          '42% weight reduction achieved',
          '3x faster than traditional machining',
          'Met all strength requirements',
        ],
      },
    ],
    pricing: {
      setup: 'Free instant online quotes',
      perUnit: 'Varies by geometry - typically £50-500/part for CNC',
      minimumProject: '£100',
      notes: 'Volume discounts available. No tooling costs for prototypes.',
    },
    qualityControl: {
      processes: [
        'First article inspection (FAI)',
        'In-process quality checks',
        'CMM measurement',
        'Material certification',
      ],
      certifications: ['ISO 9001:2015', 'ISO 13485', 'AS9100'],
      defectRate: '< 0.5% defect rate',
    },
    equipment: {
      machines: [
        '100+ CNC mills and lathes',
        '50+ injection molding presses',
        '30+ industrial 3D printers (SLS, SLA, DMLS)',
      ],
      capacity: '10,000+ parts per day',
      technology: [
        '5-axis CNC machining',
        'Aluminum tooling for injection molding',
        'Direct metal laser sintering (DMLS)',
      ],
    },
    support: {
      designAssistance: true,
      prototyping: true,
      engineering: true,
      logistics: true,
    },
    customerReviews: {
      rating: 4.5,
      totalReviews: 127,
      pros: [
        'Incredibly fast turnaround times',
        'High quality parts',
        'Easy online quoting system',
        'Great customer service',
      ],
      cons: [
        'Premium pricing',
        'Limited to their material selection',
        'Not cost-effective for high volumes',
      ],
      testimonials: [
        {
          company: 'MedTech Innovations Ltd',
          quote: 'Proto Labs saved our product launch. We got injection molded parts in 5 days that would have taken 8 weeks elsewhere.',
          author: 'Sarah Chen',
          role: 'CEO',
        },
        {
          company: 'Robotics UK',
          quote: 'The quality is excellent and the speed is unmatched. Perfect for rapid iteration during product development.',
          author: 'James Miller',
          role: 'Chief Engineer',
        },
      ],
    },
  },
  {
    name: 'Omega Plastics',
    description: 'Injection moulding specialists for production volumes from 1,000 to 1,000,000+ units',
    capabilities: [
      'Injection Molding',
      'Overmolding',
      'Insert Molding',
      'Ultrasonic Welding',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Telford',
      country: 'United Kingdom',
      postcode: 'TF3 5DN',
    },
    contact: {
      email: 'enquiries@omegaplastics.co.uk',
      phone: '+44 1952 607000',
      website: 'https://www.omegaplastics.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 1000,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.7,
    reviewCount: 89,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1979,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Laser Master UK',
    description: 'Precision laser cutting and engraving services for metals, plastics, and composites',
    capabilities: [
      'Laser Cutting',
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Powder Coating',
      'Screen Printing',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B6 7BA',
    },
    contact: {
      email: 'sales@lasermaster.co.uk',
      phone: '+44 121 359 5888',
      website: 'https://www.lasermaster.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.6,
    reviewCount: 156,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1997,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'RPWORLD UK',
    description: 'One-stop rapid prototyping and low-volume manufacturing service',
    capabilities: [
      'Additive Manufacturing - Plastic',
      'CNC Machining',
      'Vacuum Forming',
      'Injection Molding',
      'Sheet Metal Fabrication',
      'Anodizing',
      'Powder Coating',
    ],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC1V 2NX',
    },
    contact: {
      email: 'info@rpworld.co.uk',
      phone: '+44 20 3322 3910',
      website: 'https://www.rpworld.co.uk',
    },
    certifications: ['ISO 9001:2015', 'RoHS'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.4,
    reviewCount: 92,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2010,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Newbury Electronics',
    description: 'PCB assembly and electronic manufacturing services',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Cable Assembly',
      'Wire Harness Assembly',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Newbury',
      country: 'United Kingdom',
      postcode: 'RG14 2PZ',
    },
    contact: {
      email: 'sales@newburyelectronics.co.uk',
      phone: '+44 1635 40347',
      website: 'https://www.newburyelectronics.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'IPC-A-610', 'AS9100'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.8,
    reviewCount: 74,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1973,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Formero',
    description: 'Vacuum forming, pressure forming and thermoforming specialists',
    capabilities: [
      'Vacuum Forming',
      'Compression Molding',
      'CNC Machining',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Sheffield',
      country: 'United Kingdom',
      postcode: 'S9 2YL',
    },
    contact: {
      email: 'info@formero.co.uk',
      phone: '+44 114 244 4500',
      website: 'https://www.formero.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.5,
    reviewCount: 63,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1990,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'MJN Neuro',
    description: 'Specialist in EPS molding, EPP molding, and expanded foam products',
    capabilities: [
      'EPS Molding',
      'EPP Molding',
      'Heat Chest Molding',
      'CNC Machining',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Leicester',
      country: 'United Kingdom',
      postcode: 'LE4 1AW',
    },
    contact: {
      email: 'sales@mjnneuro.co.uk',
      phone: '+44 116 266 8989',
      website: 'https://www.mjnneuro.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 5,
    status: 'verified',
    rating: 4.6,
    reviewCount: 51,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1987,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'EMS UK',
    description: 'Full-service electronics manufacturing - from design to finished product',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Wire Harness Assembly',
      'Cable Assembly',
      'Quality Control & Testing',
      'Certification Support',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Camberley',
      country: 'United Kingdom',
      postcode: 'GU15 3YL',
    },
    contact: {
      email: 'info@emsuk.com',
      phone: '+44 1276 691371',
      website: 'https://www.emsuk.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'ISO 14001', 'IPC-A-610'],
    minimumOrderQuantity: 50,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.7,
    reviewCount: 85,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1982,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Brandauer',
    description: 'Precision stamping, tooling, and metal fabrication since 1862',
    capabilities: [
      'Sheet Metal Fabrication',
      'Die Casting',
      'CNC Machining',
      'Welding & Assembly',
      'Powder Coating',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B19 2XF',
    },
    contact: {
      email: 'sales@brandauer.co.uk',
      phone: '+44 121 359 3646',
      website: 'https://www.brandauer.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'IATF 16949'],
    minimumOrderQuantity: 5000,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.8,
    reviewCount: 67,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1862,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Tharsus',
    description: 'Robotic and automated assembly solutions with full production capabilities',
    capabilities: [
      'Electronic Assembly',
      'Final Assembly & Packaging',
      'Welding & Assembly',
      'Quality Control & Testing',
      'Design for Manufacturing',
      'Certification Support',
    ],
    region: 'UK',
    location: {
      city: 'Blyth',
      country: 'United Kingdom',
      postcode: 'NE24 1LZ',
    },
    contact: {
      email: 'hello@tharsus.co.uk',
      phone: '+44 1670 734 334',
      website: 'https://www.tharsus.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'ISO 45001'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 8,
    status: 'verified',
    rating: 4.9,
    reviewCount: 42,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2007,
      employeeCount: '250-500',
      priceRange: 'premium',
    },
  },
  {
    name: '3D Hubs (Protolabs Network)',
    description: 'On-demand manufacturing network connecting designers with verified UK manufacturers for rapid prototyping',
    capabilities: [
      'Additive Manufacturing - Plastic',
      'Additive Manufacturing - Metal',
      'CNC Machining',
      'Injection Molding',
      'Sheet Metal Fabrication',
    ],
    region: 'UK',
    location: {
      city: 'London',
      country: 'United Kingdom',
      postcode: 'EC2A 4NE',
    },
    contact: {
      email: 'support@hubs.com',
      phone: '+44 20 3695 2676',
      website: 'https://www.hubs.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 1,
    status: 'verified',
    rating: 4.6,
    reviewCount: 234,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2013,
      employeeCount: '250-500',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'XYZ Machine Tools',
    description: 'CNC machine tool supplier offering contract machining and manufacturing services',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Design for Manufacturing',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Buxton',
      country: 'United Kingdom',
      postcode: 'SK17 6SF',
    },
    contact: {
      email: 'sales@xyzmachinetools.com',
      phone: '+44 1298 872200',
      website: 'https://www.xyzmachinetools.com',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.5,
    reviewCount: 78,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1961,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Paragon Rapid Technologies',
    description: 'Additive manufacturing specialists offering SLA, SLS, and FDM 3D printing with post-processing',
    capabilities: [
      'Additive Manufacturing - Plastic',
      'Additive Manufacturing - Metal',
      'Vacuum Casting',
      'CNC Machining',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Wellingborough',
      country: 'United Kingdom',
      postcode: 'NN8 6BA',
    },
    contact: {
      email: 'info@paragon-rt.co.uk',
      phone: '+44 1933 276047',
      website: 'https://www.paragon-rt.co.uk',
    },
    certifications: ['ISO 9001:2015', 'AS9100'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.7,
    reviewCount: 95,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2000,
      employeeCount: '50-100',
      priceRange: 'premium',
    },
  },
  {
    name: 'Olympus Metal Finishing',
    description: 'Specialist metal finishing services including anodizing, plating, and powder coating',
    capabilities: [
      'Anodizing',
      'Electroplating',
      'Powder Coating',
      'Sheet Metal Fabrication',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Bristol',
      country: 'United Kingdom',
      postcode: 'BS5 9QB',
    },
    contact: {
      email: 'sales@olympusmf.com',
      phone: '+44 117 955 2481',
      website: 'https://www.olympusmf.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'NADCAP'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.8,
    reviewCount: 112,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1992,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Abbey Plastics',
    description: 'Custom injection moulding and toolmaking for low to high volume production',
    capabilities: [
      'Injection Molding',
      'Insert Molding',
      'Overmolding',
      'Ultrasonic Welding',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Walsall',
      country: 'United Kingdom',
      postcode: 'WS10 7LR',
    },
    contact: {
      email: 'sales@abbeyplastics.co.uk',
      phone: '+44 1922 743050',
      website: 'https://www.abbeyplastics.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 5,
    status: 'verified',
    rating: 4.6,
    reviewCount: 87,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1967,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'European Springs & Pressings',
    description: 'Precision spring manufacturing and wire forming specialists',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Die Casting',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Redruth',
      country: 'United Kingdom',
      postcode: 'TR15 3RQ',
    },
    contact: {
      email: 'sales@europeansprings.com',
      phone: '+44 1209 314831',
      website: 'https://www.europeansprings.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.7,
    reviewCount: 103,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1948,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Airedale Springs',
    description: 'Precision spring and wireform manufacturer for engineering applications',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Welding & Assembly',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Leeds',
      country: 'United Kingdom',
      postcode: 'LS12 6JW',
    },
    contact: {
      email: 'sales@airedalesprings.co.uk',
      phone: '+44 113 246 3747',
      website: 'https://www.airedalesprings.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 50,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.5,
    reviewCount: 68,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1945,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Fastenright Ltd',
    description: 'Specialist fixings and fasteners supplier with custom manufacturing capabilities',
    capabilities: [
      'CNC Machining',
      'Die Casting',
      'Electroplating',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Andover',
      country: 'United Kingdom',
      postcode: 'SP10 2NJ',
    },
    contact: {
      email: 'sales@fastenright.com',
      phone: '+44 1264 333533',
      website: 'https://www.fastenright.com',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1000,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.4,
    reviewCount: 56,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1984,
      employeeCount: '10-50',
      priceRange: 'budget',
    },
  },
  {
    name: 'V&F Sheet Metal',
    description: 'Precision sheet metal fabrication specialists with laser cutting and folding capabilities',
    capabilities: [
      'Sheet Metal Fabrication',
      'Laser Cutting',
      'Powder Coating',
      'Welding & Assembly',
      'CNC Machining',
    ],
    region: 'UK',
    location: {
      city: 'Witney',
      country: 'United Kingdom',
      postcode: 'OX28 4FF',
    },
    contact: {
      email: 'sales@vandf.co.uk',
      phone: '+44 1993 774444',
      website: 'https://www.vandf.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.8,
    reviewCount: 142,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1971,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Dean Group International',
    description: 'Investment casting and precision machining for complex metal components',
    capabilities: [
      'Investment Casting',
      'Die Casting',
      'CNC Machining',
      'Anodizing',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Manchester',
      country: 'United Kingdom',
      postcode: 'M27 8UJ',
    },
    contact: {
      email: 'sales@deangroupinternational.com',
      phone: '+44 161 775 7300',
      website: 'https://www.deangroupinternational.com',
    },
    certifications: ['ISO 9001:2015', 'AS9100', 'ISO 14001'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.7,
    reviewCount: 91,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1963,
      employeeCount: '250-500',
      priceRange: 'premium',
    },
  },
  {
    name: 'Gooch & Housego',
    description: 'Precision optical components and photonics manufacturing',
    capabilities: [
      'CNC Machining',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
      'Certification Support',
    ],
    region: 'UK',
    location: {
      city: 'Ilminster',
      country: 'United Kingdom',
      postcode: 'TA19 9DH',
    },
    contact: {
      email: 'sales@goochandhousego.com',
      phone: '+44 1460 256440',
      website: 'https://www.goochandhousego.com',
    },
    certifications: ['ISO 9001:2015', 'AS9100', 'ISO 14001'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 8,
    status: 'verified',
    rating: 4.9,
    reviewCount: 48,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1948,
      employeeCount: '500-1000',
      priceRange: 'premium',
    },
  },
  {
    name: 'Stadium Export',
    description: 'Contract electronics manufacturer specializing in PCB assembly and box build',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Cable Assembly',
      'Wire Harness Assembly',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Poole',
      country: 'United Kingdom',
      postcode: 'BH17 7BA',
    },
    contact: {
      email: 'sales@stadium.co.uk',
      phone: '+44 1202 422000',
      website: 'https://www.stadium.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'IPC-A-610'],
    minimumOrderQuantity: 20,
    leadTimeWeeks: 4,
    status: 'verified',
    rating: 4.6,
    reviewCount: 83,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1969,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Qualitetch',
    description: 'Chemical etching and photo etching specialists for precision metal components',
    capabilities: [
      'Sheet Metal Fabrication',
      'Laser Cutting',
      'Electroforming',
      'CNC Machining',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B42 2LH',
    },
    contact: {
      email: 'sales@qualitetch.co.uk',
      phone: '+44 121 333 6840',
      website: 'https://www.qualitetch.co.uk',
    },
    certifications: ['ISO 9001:2015', 'AS9100'],
    minimumOrderQuantity: 100,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.7,
    reviewCount: 79,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1982,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'J & L Engineering',
    description: 'CNC turning and milling specialists for precision engineering components',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Welding & Assembly',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Rotherham',
      country: 'United Kingdom',
      postcode: 'S63 5DB',
    },
    contact: {
      email: 'sales@jandlengineering.co.uk',
      phone: '+44 1709 873007',
      website: 'https://www.jandlengineering.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 2,
    status: 'verified',
    rating: 4.5,
    reviewCount: 64,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1994,
      employeeCount: '10-50',
      priceRange: 'budget',
    },
  },
  {
    name: 'Grainger & Worrall',
    description: 'Aluminium and magnesium casting specialists with full machining capabilities',
    capabilities: [
      'Die Casting',
      'Investment Casting',
      'CNC Machining',
      'Powder Coating',
      'Anodizing',
    ],
    region: 'UK',
    location: {
      city: 'Bridgnorth',
      country: 'United Kingdom',
      postcode: 'WV15 5HP',
    },
    contact: {
      email: 'sales@gwcastings.co.uk',
      phone: '+44 1746 765432',
      website: 'https://www.gwcastings.co.uk',
    },
    certifications: ['ISO 9001:2015', 'IATF 16949', 'ISO 14001'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 8,
    status: 'verified',
    rating: 4.8,
    reviewCount: 96,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1865,
      employeeCount: '250-500',
      priceRange: 'premium',
    },
  },
  {
    name: 'Weston Aerospace',
    description: 'Precision machining and fabrication for aerospace and defense sectors',
    capabilities: [
      'CNC Machining',
      'Sheet Metal Fabrication',
      'Welding & Assembly',
      'Quality Control & Testing',
      'Certification Support',
    ],
    region: 'UK',
    location: {
      city: 'Portland',
      country: 'United Kingdom',
      postcode: 'DT5 2JT',
    },
    contact: {
      email: 'sales@westonaerospace.com',
      phone: '+44 1305 824834',
      website: 'https://www.westonaerospace.com',
    },
    certifications: ['ISO 9001:2015', 'AS9100', 'NADCAP'],
    minimumOrderQuantity: 1,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.9,
    reviewCount: 57,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1992,
      employeeCount: '100-250',
      priceRange: 'premium',
    },
  },
  {
    name: 'Airedale Group',
    description: 'Full-service manufacturer offering PCB assembly, cable assembly, and box build',
    capabilities: [
      'PCB Assembly',
      'Electronic Assembly',
      'Cable Assembly',
      'Wire Harness Assembly',
      'Final Assembly & Packaging',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Halifax',
      country: 'United Kingdom',
      postcode: 'HX3 5AY',
    },
    contact: {
      email: 'sales@airedale-group.com',
      phone: '+44 1422 320420',
      website: 'https://www.airedale-group.com',
    },
    certifications: ['ISO 9001:2015', 'ISO 13485', 'IPC-A-610', 'ISO 14001'],
    minimumOrderQuantity: 50,
    leadTimeWeeks: 5,
    status: 'verified',
    rating: 4.7,
    reviewCount: 88,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1972,
      employeeCount: '100-250',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Plastic Concepts',
    description: 'Injection moulding and product design specialists for consumer products',
    capabilities: [
      'Injection Molding',
      'Overmolding',
      'Insert Molding',
      'Design for Manufacturing',
      'Quality Control & Testing',
    ],
    region: 'UK',
    location: {
      city: 'Leicester',
      country: 'United Kingdom',
      postcode: 'LE8 0RX',
    },
    contact: {
      email: 'info@plasticconcepts.co.uk',
      phone: '+44 116 277 6677',
      website: 'https://www.plasticconcepts.co.uk',
    },
    certifications: ['ISO 9001:2015'],
    minimumOrderQuantity: 1000,
    leadTimeWeeks: 6,
    status: 'verified',
    rating: 4.5,
    reviewCount: 72,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1988,
      employeeCount: '50-100',
      priceRange: 'mid-range',
    },
  },
  {
    name: 'Cooksongold',
    description: 'Precious metals casting, finishing and jewellery manufacturing services',
    capabilities: [
      'Investment Casting',
      'CNC Machining',
      'Electroplating',
      'Quality Control & Testing',
      'Final Assembly & Packaging',
    ],
    region: 'UK',
    location: {
      city: 'Birmingham',
      country: 'United Kingdom',
      postcode: 'B1 3DR',
    },
    contact: {
      email: 'sales@cooksongold.com',
      phone: '+44 345 100 1122',
      website: 'https://www.cooksongold.com',
    },
    certifications: ['ISO 9001:2015', 'RJC'],
    minimumOrderQuantity: 10,
    leadTimeWeeks: 3,
    status: 'verified',
    rating: 4.6,
    reviewCount: 154,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 1873,
      employeeCount: '100-250',
      priceRange: 'premium',
    },
  },
  {
    name: 'Produmax',
    description: 'Automated manufacturing solutions with robotic assembly and production line integration',
    capabilities: [
      'Electronic Assembly',
      'Final Assembly & Packaging',
      'Welding & Assembly',
      'Quality Control & Testing',
      'Design for Manufacturing',
    ],
    region: 'UK',
    location: {
      city: 'Coventry',
      country: 'United Kingdom',
      postcode: 'CV6 4AP',
    },
    contact: {
      email: 'enquiries@produmax.co.uk',
      phone: '+44 24 7666 8844',
      website: 'https://www.produmax.co.uk',
    },
    certifications: ['ISO 9001:2015', 'ISO 14001', 'IATF 16949'],
    minimumOrderQuantity: 500,
    leadTimeWeeks: 10,
    status: 'verified',
    rating: 4.8,
    reviewCount: 65,
    recommendedByWorkspaceIds: [],
    approvedByAdminAt: new Date().toISOString(),
    metadata: {
      yearEstablished: 2003,
      employeeCount: '100-250',
      priceRange: 'premium',
    },
  },
];

// Helper to seed suppliers into the platform
export function createSuppliersSeedData(): Record<string, Supplier> {
  const suppliers: Record<string, Supplier> = {};

  UK_SUPPLIERS.forEach((supplierData) => {
    const supplier: Supplier = {
      ...supplierData,
      id: uuidv4(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    suppliers[supplier.id] = supplier;
  });

  return suppliers;
}

// Get all unique capabilities for UI filtering
export function getAllCapabilities(): ManufacturingCapability[] {
  const capabilities = new Set<ManufacturingCapability>();
  UK_SUPPLIERS.forEach((supplier) => {
    supplier.capabilities.forEach((cap) => capabilities.add(cap));
  });
  return Array.from(capabilities).sort();
}
