/**
 * Third-Party AI Tools Data for Community Marketplace
 * External AI tools that teams can use, organized by business function
 */

export type BusinessFunction = 'Sales' | 'Marketing' | 'Finance' | 'Ops' | 'Engineering' | 'Admin';

export interface ThirdPartyAITool {
  id: string;
  name: string;
  provider: string;
  purpose: string;
  functions: BusinessFunction[];
  costPerMonth: number;
  website: string;
  capabilities: string[];
  integrations: string[];
  category: 'productivity' | 'sales' | 'marketing' | 'finance' | 'engineering' | 'operations';
}

export const THIRD_PARTY_AI_TOOLS: ThirdPartyAITool[] = [
  // ========== FINANCE (3 agents) ==========
  {
    id: 'ai-finance-1',
    name: 'Vic AI',
    provider: 'Vic.ai',
    purpose: 'Autonomous invoice processing and accounts payable automation',
    functions: ['Finance'],
    costPerMonth: 450,
    website: 'https://vic.ai',
    capabilities: [
      'Automated invoice extraction',
      'GL code assignment',
      'Duplicate invoice detection',
      'Purchase order matching',
      'Approval workflow automation',
      'Real-time spend analytics',
    ],
    integrations: ['QuickBooks', 'Xero', 'NetSuite', 'Slack'],
    category: 'finance',
  },
  {
    id: 'ai-finance-2',
    name: 'Digits AI',
    provider: 'Digits',
    purpose: 'AI-powered bookkeeping and financial insights',
    functions: ['Finance'],
    costPerMonth: 350,
    website: 'https://digits.com',
    capabilities: [
      'Automated bookkeeping',
      'Financial reporting dashboards',
      'Cash flow forecasting',
      'Expense categorization',
      'Revenue recognition',
      'Financial health scoring',
    ],
    integrations: ['Bank accounts', 'Credit cards', 'Stripe', 'Plaid'],
    category: 'finance',
  },
  {
    id: 'ai-finance-3',
    name: 'Gemini Pro',
    provider: 'Google',
    purpose: 'Financial data analysis and spreadsheet automation',
    functions: ['Finance'],
    costPerMonth: 200,
    website: 'https://ai.google.dev',
    capabilities: [
      'Financial modeling',
      'Google Sheets integration',
      'Budget variance analysis',
      'Scenario planning',
      'Chart and report generation',
      'Data validation',
    ],
    integrations: ['Google Workspace', 'Sheets', 'Docs', 'Drive'],
    category: 'finance',
  },

  // ========== SALES (4 agents) ==========
  {
    id: 'ai-sales-1',
    name: '11x Alice',
    provider: '11x',
    purpose: 'Autonomous AI SDR for outbound sales',
    functions: ['Sales'],
    costPerMonth: 850,
    website: 'https://11x.ai',
    capabilities: [
      'Automated lead prospecting',
      'Personalized email sequences',
      'Multi-channel outreach',
      'Meeting scheduling',
      'Lead qualification',
      'CRM integration',
    ],
    integrations: ['Salesforce', 'HubSpot', 'LinkedIn', 'Gmail'],
    category: 'sales',
  },
  {
    id: 'ai-sales-2',
    name: 'Gong AI',
    provider: 'Gong',
    purpose: 'Sales call analysis and revenue intelligence',
    functions: ['Sales'],
    costPerMonth: 400,
    website: 'https://gong.io',
    capabilities: [
      'Call recording and transcription',
      'Conversation insights',
      'Deal risk assessment',
      'Coaching recommendations',
      'Competitor mention tracking',
      'Revenue forecasting',
    ],
    integrations: ['Zoom', 'Salesforce', 'Slack', 'Teams'],
    category: 'sales',
  },
  {
    id: 'ai-sales-3',
    name: 'Clay AI',
    provider: 'Clay',
    purpose: 'Lead enrichment and prospecting automation',
    functions: ['Sales'],
    costPerMonth: 300,
    website: 'https://clay.com',
    capabilities: [
      'Contact data enrichment',
      'Company intelligence',
      'Tech stack detection',
      'Social media insights',
      'Intent data signals',
      'List building automation',
    ],
    integrations: ['Clearbit', 'LinkedIn', 'Salesforce', 'CSV'],
    category: 'sales',
  },
  {
    id: 'ai-sales-4',
    name: 'ElevenLabs Voice AI',
    provider: 'ElevenLabs',
    purpose: 'Sales demo voiceovers and presentation narration',
    functions: ['Sales'],
    costPerMonth: 99,
    website: 'https://elevenlabs.io',
    capabilities: [
      'Text-to-speech for demos',
      'Multi-language support',
      'Voice cloning',
      'Custom pronunciations',
      'Audio editing tools',
      'API integration',
    ],
    integrations: ['Descript', 'Adobe Premiere', 'API'],
    category: 'sales',
  },

  // ========== MARKETING (6 agents) ==========
  {
    id: 'ai-marketing-1',
    name: 'Jasper AI',
    provider: 'Jasper',
    purpose: 'Content creation for marketing campaigns',
    functions: ['Marketing'],
    costPerMonth: 200,
    website: 'https://jasper.ai',
    capabilities: [
      'Blog post generation',
      'Social media content',
      'Email campaign copy',
      'SEO optimization',
      'Brand voice consistency',
      'Content templates',
    ],
    integrations: ['WordPress', 'Webflow', 'Grammarly', 'Surfer SEO'],
    category: 'marketing',
  },
  {
    id: 'ai-marketing-2',
    name: 'Copy.ai',
    provider: 'Copy.ai',
    purpose: 'Marketing copy and workflow automation',
    functions: ['Marketing'],
    costPerMonth: 180,
    website: 'https://copy.ai',
    capabilities: [
      'Ad copy generation',
      'Product descriptions',
      'Landing page copy',
      'Email sequences',
      'A/B test variants',
      'Workflow automation',
    ],
    integrations: ['HubSpot', 'Mailchimp', 'Shopify', 'WordPress'],
    category: 'marketing',
  },
  {
    id: 'ai-marketing-3',
    name: 'Midjourney',
    provider: 'Midjourney',
    purpose: 'High-quality imagery for marketing materials',
    functions: ['Marketing'],
    costPerMonth: 60,
    website: 'https://midjourney.com',
    capabilities: [
      'Photorealistic imagery',
      'Product visualization',
      'Brand identity concepts',
      'Website hero images',
      'Pitch deck visuals',
      'Style consistency',
    ],
    integrations: ['Discord', 'Figma'],
    category: 'marketing',
  },
  {
    id: 'ai-marketing-4',
    name: 'DALL-E 3',
    provider: 'OpenAI',
    purpose: 'Marketing visuals and social media graphics',
    functions: ['Marketing'],
    costPerMonth: 120,
    website: 'https://openai.com',
    capabilities: [
      'Social media graphics',
      'Ad creative concepts',
      'Presentation visuals',
      'Product mockups',
      'Infographic elements',
      'Text rendering in images',
    ],
    integrations: ['Figma', 'Canva', 'OpenAI API'],
    category: 'marketing',
  },
  {
    id: 'ai-marketing-5',
    name: 'Perplexity Pro',
    provider: 'Perplexity',
    purpose: 'Market research and competitive intelligence',
    functions: ['Marketing'],
    costPerMonth: 80,
    website: 'https://perplexity.ai',
    capabilities: [
      'Real-time web search',
      'Competitor research',
      'Market trend analysis',
      'Citation-backed answers',
      'News monitoring',
      'Industry insights',
    ],
    integrations: ['Browser extension', 'API'],
    category: 'marketing',
  },
  {
    id: 'ai-marketing-6',
    name: 'Runway Gen-2',
    provider: 'Runway',
    purpose: 'AI video generation for marketing content',
    functions: ['Marketing'],
    costPerMonth: 250,
    website: 'https://runwayml.com',
    capabilities: [
      'Text-to-video generation',
      'Image-to-video animation',
      'Video style transfer',
      'Motion graphics',
      'Product demo videos',
      'Social media content',
    ],
    integrations: ['Adobe Premiere', 'Final Cut Pro', 'DaVinci Resolve'],
    category: 'marketing',
  },

  // ========== OPS (3 agents) ==========
  {
    id: 'ai-ops-1',
    name: 'Hebbia AI',
    provider: 'Hebbia',
    purpose: 'Document analysis and operational workflows',
    functions: ['Ops'],
    costPerMonth: 400,
    website: 'https://hebbia.ai',
    capabilities: [
      'Multi-document analysis',
      'Contract review',
      'Compliance checking',
      'Data extraction',
      'Workflow automation',
      'Knowledge synthesis',
    ],
    integrations: ['Google Drive', 'Dropbox', 'SharePoint', 'Slack'],
    category: 'operations',
  },
  {
    id: 'ai-ops-2',
    name: 'Zapier AI',
    provider: 'Zapier',
    purpose: 'Workflow automation across tools',
    functions: ['Ops'],
    costPerMonth: 150,
    website: 'https://zapier.com',
    capabilities: [
      'App integration',
      'Automated workflows',
      'Data syncing',
      'Trigger-based actions',
      'Multi-step automation',
      'AI-powered suggestions',
    ],
    integrations: ['5000+ apps', 'Slack', 'Gmail', 'Sheets', 'CRM'],
    category: 'operations',
  },
  {
    id: 'ai-ops-3',
    name: 'Harvey AI',
    provider: 'Harvey',
    purpose: 'Legal document review and compliance',
    functions: ['Ops'],
    costPerMonth: 500,
    website: 'https://harvey.ai',
    capabilities: [
      'Contract analysis',
      'Legal research',
      'Compliance checking',
      'Risk assessment',
      'Document drafting',
      'Regulatory updates',
    ],
    integrations: ['Microsoft Word', 'Google Docs', 'DocuSign'],
    category: 'operations',
  },

  // ========== ENGINEERING (4 agents) ==========
  {
    id: 'ai-eng-1',
    name: 'GitHub Copilot',
    provider: 'OpenAI',
    purpose: 'Real-time code completion and suggestions',
    functions: ['Engineering'],
    costPerMonth: 60,
    website: 'https://github.com/features/copilot',
    capabilities: [
      'Code autocomplete',
      'Function generation',
      'Refactoring suggestions',
      'Test generation',
      'Documentation writing',
      'Multi-language support',
    ],
    integrations: ['VS Code', 'JetBrains IDEs', 'Neovim', 'GitHub'],
    category: 'engineering',
  },
  {
    id: 'ai-eng-2',
    name: 'Cursor AI',
    provider: 'Cursor',
    purpose: 'AI code editor with advanced IDE features',
    functions: ['Engineering'],
    costPerMonth: 80,
    website: 'https://cursor.sh',
    capabilities: [
      'Natural language code editing',
      'Codebase understanding',
      'Refactoring assistance',
      'Bug detection',
      'Code generation',
      'Context-aware suggestions',
    ],
    integrations: ['VS Code fork', 'GitHub', 'GitLab', 'Terminal'],
    category: 'engineering',
  },
  {
    id: 'ai-eng-3',
    name: 'Replit Ghostwriter',
    provider: 'Replit',
    purpose: 'Code generation and debugging assistance',
    functions: ['Engineering'],
    costPerMonth: 40,
    website: 'https://replit.com',
    capabilities: [
      'Code completion',
      'Error explanation',
      'Code generation',
      'Debugging assistance',
      'Terminal command suggestions',
      'Package recommendations',
    ],
    integrations: ['Replit IDE', 'GitHub import', 'NPM', 'PyPI'],
    category: 'engineering',
  },
  {
    id: 'ai-eng-4',
    name: 'Tabnine',
    provider: 'Tabnine',
    purpose: 'Private code completion for sensitive codebases',
    functions: ['Engineering'],
    costPerMonth: 90,
    website: 'https://tabnine.com',
    capabilities: [
      'On-premise code completion',
      'Team model training',
      'Context-aware suggestions',
      'Code pattern learning',
      'Security compliance',
      'No data sharing',
    ],
    integrations: ['VS Code', 'IntelliJ', 'PyCharm', 'WebStorm'],
    category: 'engineering',
  },

  // ========== ADMIN/ALL (4 agents) ==========
  {
    id: 'ai-admin-1',
    name: 'ChatGPT Enterprise',
    provider: 'OpenAI',
    purpose: 'General-purpose assistant for all team members',
    functions: ['Admin'],
    costPerMonth: 600,
    website: 'https://openai.com',
    capabilities: [
      'Email drafting',
      'Meeting summaries',
      'Task planning',
      'Problem solving',
      'Brainstorming',
      'Data privacy (enterprise)',
    ],
    integrations: ['Web', 'Mobile app', 'API', 'Microsoft Teams'],
    category: 'productivity',
  },
  {
    id: 'ai-admin-2',
    name: 'Notion AI',
    provider: 'Notion',
    purpose: 'Note-taking and knowledge management with AI',
    functions: ['Admin'],
    costPerMonth: 120,
    website: 'https://notion.so',
    capabilities: [
      'Smart note summarization',
      'Writing assistance',
      'Action item extraction',
      'Content generation',
      'Knowledge base search',
      'Translation',
    ],
    integrations: ['Notion workspace', 'Slack', 'Google Drive', 'API'],
    category: 'productivity',
  },
  {
    id: 'ai-admin-3',
    name: 'Otter.ai',
    provider: 'Otter.ai',
    purpose: 'Meeting transcription and notes automation',
    functions: ['Admin'],
    costPerMonth: 75,
    website: 'https://otter.ai',
    capabilities: [
      'Real-time transcription',
      'Meeting summaries',
      'Speaker identification',
      'Action item extraction',
      'Searchable transcripts',
      'Calendar integration',
    ],
    integrations: ['Zoom', 'Google Meet', 'Teams', 'Dropbox', 'Slack'],
    category: 'productivity',
  },
  {
    id: 'ai-admin-4',
    name: 'Grammarly Business',
    provider: 'Grammarly',
    purpose: 'Writing quality and consistency across communications',
    functions: ['Admin'],
    costPerMonth: 100,
    website: 'https://grammarly.com',
    capabilities: [
      'Grammar and spelling checks',
      'Tone detection',
      'Style guide enforcement',
      'Plagiarism detection',
      'Clarity suggestions',
      'Brand voice consistency',
    ],
    integrations: ['Browser', 'Microsoft Office', 'Google Docs', 'Slack'],
    category: 'productivity',
  },
];

// Helper functions
export function getAIToolsByFunction(func: BusinessFunction | 'all'): ThirdPartyAITool[] {
  if (func === 'all') {
    return THIRD_PARTY_AI_TOOLS;
  }
  return THIRD_PARTY_AI_TOOLS.filter(tool => tool.functions.includes(func));
}

export function getTotalAIToolsCount(): number {
  return THIRD_PARTY_AI_TOOLS.length;
}

export function getCategoryColor(category: string): { bg: string; text: string; border: string; iconColor: string } {
  const colors: Record<string, { bg: string; text: string; border: string; iconColor: string }> = {
    productivity: { bg: 'bg-blue-100 dark:bg-blue-900/30', text: 'text-blue-900 dark:text-blue-100', border: 'border-blue-200 dark:border-blue-800', iconColor: '#3b82f6' },
    sales: { bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-900 dark:text-emerald-100', border: 'border-emerald-200 dark:border-emerald-800', iconColor: '#10b981' },
    marketing: { bg: 'bg-pink-100 dark:bg-pink-900/30', text: 'text-pink-900 dark:text-pink-100', border: 'border-pink-200 dark:border-pink-800', iconColor: '#ec4899' },
    finance: { bg: 'bg-purple-100 dark:bg-purple-900/30', text: 'text-purple-900 dark:text-purple-100', border: 'border-purple-200 dark:border-purple-800', iconColor: '#a855f7' },
    engineering: { bg: 'bg-cyan-100 dark:bg-cyan-900/30', text: 'text-cyan-900 dark:text-cyan-100', border: 'border-cyan-200 dark:border-cyan-800', iconColor: '#06b6d4' },
    operations: { bg: 'bg-amber-100 dark:bg-amber-900/30', text: 'text-amber-900 dark:text-amber-100', border: 'border-amber-200 dark:border-amber-800', iconColor: '#f59e0b' },
  };
  return colors[category] || colors.productivity;
}
