// Pre-defined workflow templates for each function
// These provide suggested task sequences that executives can follow

import type { WorkflowTemplate, Function } from '@/types';

export const WORKFLOW_TEMPLATES: Record<Function, WorkflowTemplate> = {
  Marketing: {
    id: 'marketing-sequence-v1',
    function: 'Marketing',
    title: 'Marketing Launch Sequence',
    description: 'Complete marketing setup and launch sequence for hardware startups',
    isSystem: true,
    createdAt: new Date().toISOString(),
    items: [
      {
        title: 'Define Target Customer & ICP',
        description: 'Create detailed ideal customer profile including demographics, pain points, and buying behavior',
        sequenceOrder: 1,
        estimatedHours: 8,
      },
      {
        title: 'Conduct Competitive Analysis',
        description: 'Research 5-10 competitors, document positioning, pricing, and messaging strategies',
        sequenceOrder: 2,
        estimatedHours: 12,
        dependencies: [0],
      },
      {
        title: 'Develop Brand Positioning & Messaging',
        description: 'Create value proposition, key messages, and brand voice guidelines',
        sequenceOrder: 3,
        estimatedHours: 16,
        dependencies: [0, 1],
      },
      {
        title: 'Set Up Website & Landing Pages',
        description: 'Build core website with product pages, pricing, and lead capture forms',
        sequenceOrder: 4,
        estimatedHours: 40,
        dependencies: [2],
      },
      {
        title: 'Create Content Calendar & Initial Assets',
        description: 'Plan 3-month content calendar, create 10+ blog posts, social templates, and email sequences',
        sequenceOrder: 5,
        estimatedHours: 30,
        dependencies: [2],
      },
      {
        title: 'Set Up Analytics & Tracking',
        description: 'Implement Google Analytics, mixpanel, and conversion tracking across all properties',
        sequenceOrder: 6,
        estimatedHours: 8,
        dependencies: [3],
      },
      {
        title: 'Launch Social Media Channels',
        description: 'Set up and optimize LinkedIn, Twitter, and relevant community channels',
        sequenceOrder: 7,
        estimatedHours: 12,
        dependencies: [2, 4],
      },
      {
        title: 'Execute Initial PR Campaign',
        description: 'Create press kit, reach out to 50+ journalists, secure 3+ media placements',
        sequenceOrder: 8,
        estimatedHours: 24,
        dependencies: [2, 3],
      },
      {
        title: 'Run Paid Acquisition Tests',
        description: 'Test Google Ads, LinkedIn Ads, and 2 other channels with $5k budget',
        sequenceOrder: 9,
        estimatedHours: 20,
        dependencies: [3, 5],
      },
      {
        title: 'Optimize Based on Data',
        description: 'Analyze first 30 days of data, double down on winners, cut losers',
        sequenceOrder: 10,
        estimatedHours: 16,
        dependencies: [8],
      },
    ],
  },

  Sales: {
    id: 'sales-sequence-v1',
    function: 'Sales',
    title: 'Sales Process Setup',
    description: 'Build repeatable sales process from lead to close',
    isSystem: true,
    createdAt: new Date().toISOString(),
    items: [
      {
        title: 'Define Sales Process & Stages',
        description: 'Document lead qualification criteria, sales stages, and exit criteria for each stage',
        sequenceOrder: 1,
        estimatedHours: 8,
      },
      {
        title: 'Set Up CRM & Pipeline',
        description: 'Configure HubSpot/Salesforce, create custom fields, set up automation workflows',
        sequenceOrder: 2,
        estimatedHours: 16,
        dependencies: [0],
      },
      {
        title: 'Create Sales Collateral',
        description: 'Build pitch deck, one-pager, case studies, ROI calculator, and demo scripts',
        sequenceOrder: 3,
        estimatedHours: 24,
      },
      {
        title: 'Build Target Account List',
        description: 'Research and compile list of 200+ target accounts with decision maker contacts',
        sequenceOrder: 4,
        estimatedHours: 20,
        dependencies: [0],
      },
      {
        title: 'Develop Email Outreach Sequences',
        description: 'Write 3 email sequences (cold, warm, referral) with 5-7 touchpoints each',
        sequenceOrder: 5,
        estimatedHours: 12,
        dependencies: [2],
      },
      {
        title: 'Set Up Demo Environment',
        description: 'Create repeatable demo flow, test data, and sandbox environment',
        sequenceOrder: 6,
        estimatedHours: 16,
      },
      {
        title: 'Execute First Outreach Campaign',
        description: 'Reach out to 100 accounts via email, LinkedIn, and phone. Book 10+ meetings',
        sequenceOrder: 7,
        estimatedHours: 30,
        dependencies: [3, 4],
      },
      {
        title: 'Conduct Discovery Calls',
        description: 'Run 10+ discovery calls using BANT/MEDDIC framework, document learnings',
        sequenceOrder: 8,
        estimatedHours: 20,
        dependencies: [6],
      },
      {
        title: 'Run Product Demos',
        description: 'Deliver 5+ demos, gather feedback, iterate on demo flow',
        sequenceOrder: 9,
        estimatedHours: 15,
        dependencies: [5, 7],
      },
      {
        title: 'Close First 3 Deals',
        description: 'Navigate objections, negotiate terms, close first 3 paying customers',
        sequenceOrder: 10,
        estimatedHours: 40,
        dependencies: [8],
      },
    ],
  },

  Finance: {
    id: 'finance-sequence-v1',
    function: 'Finance',
    title: 'Financial Operations Setup',
    description: 'Establish financial systems, reporting, and controls',
    isSystem: true,
    createdAt: new Date().toISOString(),
    items: [
      {
        title: 'Set Up Chart of Accounts',
        description: 'Create standardized chart of accounts aligned with hardware startup needs',
        sequenceOrder: 1,
        estimatedHours: 8,
      },
      {
        title: 'Configure Accounting Software',
        description: 'Set up QuickBooks/Xero, connect bank accounts, configure automation rules',
        sequenceOrder: 2,
        estimatedHours: 12,
        dependencies: [0],
      },
      {
        title: 'Establish Expense Management Process',
        description: 'Set up Brex/Ramp, create expense policies, implement approval workflows',
        sequenceOrder: 3,
        estimatedHours: 8,
      },
      {
        title: 'Build Financial Model',
        description: 'Create 3-year financial model with unit economics, cash flow, and fundraising scenarios',
        sequenceOrder: 4,
        estimatedHours: 24,
      },
      {
        title: 'Set Up Payroll & Benefits',
        description: 'Configure Gusto/Rippling, set up 401k, health insurance, and equity management',
        sequenceOrder: 5,
        estimatedHours: 16,
      },
      {
        title: 'Create Monthly Reporting Package',
        description: 'Build P&L, cash flow, KPI dashboard, and board deck templates',
        sequenceOrder: 6,
        estimatedHours: 20,
        dependencies: [1, 3],
      },
      {
        title: 'Implement Inventory Tracking',
        description: 'Set up system for tracking raw materials, WIP, and finished goods inventory',
        sequenceOrder: 7,
        estimatedHours: 16,
      },
      {
        title: 'Establish Budget & Forecast Process',
        description: 'Create annual budget, monthly forecasting cadence, and variance analysis framework',
        sequenceOrder: 8,
        estimatedHours: 24,
        dependencies: [3, 5],
      },
      {
        title: 'Set Up Fundraising Materials',
        description: 'Prepare data room, cap table, financial statements, and investor-ready metrics',
        sequenceOrder: 9,
        estimatedHours: 30,
        dependencies: [5, 7],
      },
      {
        title: 'Close First Month Books',
        description: 'Complete month-end close process, reconcile accounts, produce financial statements',
        sequenceOrder: 10,
        estimatedHours: 20,
        dependencies: [1, 5],
      },
    ],
  },

  Ops: {
    id: 'ops-sequence-v1',
    function: 'Ops',
    title: 'Operations & Supply Chain Setup',
    description: 'Establish manufacturing, fulfillment, and operational processes',
    isSystem: true,
    createdAt: new Date().toISOString(),
    items: [
      {
        title: 'Document Bill of Materials (BOM)',
        description: 'Create detailed BOM with part numbers, suppliers, costs, and lead times',
        sequenceOrder: 1,
        estimatedHours: 16,
      },
      {
        title: 'Source & Qualify Suppliers',
        description: 'Identify 2-3 suppliers for each critical component, get quotes, samples, and lead times',
        sequenceOrder: 2,
        estimatedHours: 32,
        dependencies: [0],
      },
      {
        title: 'Set Up Manufacturing Partner',
        description: 'Select CM/ODM, negotiate terms, establish quality standards and inspection process',
        sequenceOrder: 3,
        estimatedHours: 40,
        dependencies: [0, 1],
      },
      {
        title: 'Create Quality Control Process',
        description: 'Define inspection criteria, test procedures, and failure/rework protocols',
        sequenceOrder: 4,
        estimatedHours: 20,
        dependencies: [2],
      },
      {
        title: 'Establish Logistics & Fulfillment',
        description: 'Set up 3PL, freight forwarders, customs broker, and shipping carrier accounts',
        sequenceOrder: 5,
        estimatedHours: 24,
      },
      {
        title: 'Build Inventory Management System',
        description: 'Implement system for tracking inventory levels, reorder points, and forecasting demand',
        sequenceOrder: 6,
        estimatedHours: 20,
        dependencies: [4],
      },
      {
        title: 'Run First Production Build',
        description: 'Execute pilot run of 100-500 units, identify issues, implement fixes',
        sequenceOrder: 7,
        estimatedHours: 60,
        dependencies: [2, 3],
      },
      {
        title: 'Optimize Unit Economics',
        description: 'Negotiate volume pricing, identify cost reduction opportunities, target 50%+ margin',
        sequenceOrder: 8,
        estimatedHours: 30,
        dependencies: [6],
      },
      {
        title: 'Set Up Returns & Support Process',
        description: 'Create RMA process, warranty policy, and customer support SOPs',
        sequenceOrder: 9,
        estimatedHours: 16,
      },
      {
        title: 'Scale to Volume Production',
        description: 'Ramp to 1000+ units/month, ensure quality and delivery consistency',
        sequenceOrder: 10,
        estimatedHours: 80,
        dependencies: [6, 7],
      },
    ],
  },

  Engineering: {
    id: 'engineering-sequence-v1',
    function: 'Engineering',
    title: 'Product Development Sequence',
    description: 'Take product from concept to production-ready',
    isSystem: true,
    createdAt: new Date().toISOString(),
    items: [
      {
        title: 'Define Product Requirements',
        description: 'Document functional specs, user stories, technical constraints, and success metrics',
        sequenceOrder: 1,
        estimatedHours: 20,
      },
      {
        title: 'Create System Architecture',
        description: 'Design high-level architecture including hardware, firmware, and software components',
        sequenceOrder: 2,
        estimatedHours: 24,
        dependencies: [0],
      },
      {
        title: 'Build Proof of Concept',
        description: 'Create functional prototype using off-the-shelf components to validate core technology',
        sequenceOrder: 3,
        estimatedHours: 60,
        dependencies: [1],
      },
      {
        title: 'Design Custom PCB',
        description: 'Create schematic and PCB layout, submit for fabrication',
        sequenceOrder: 4,
        estimatedHours: 80,
        dependencies: [2],
      },
      {
        title: 'Develop Firmware',
        description: 'Write embedded software for core functionality, implement communication protocols',
        sequenceOrder: 5,
        estimatedHours: 120,
        dependencies: [3],
      },
      {
        title: 'Design Enclosure & Mechanical',
        description: 'Create industrial design, CAD models, and DFM-optimized enclosure',
        sequenceOrder: 6,
        estimatedHours: 60,
        dependencies: [3],
      },
      {
        title: 'Build Engineering Validation (EVT)',
        description: 'Assemble 10-20 units, test functionality, identify design issues',
        sequenceOrder: 7,
        estimatedHours: 100,
        dependencies: [4, 5],
      },
      {
        title: 'Conduct Design Validation Testing (DVT)',
        description: 'Run environmental, reliability, and compliance testing. Fix identified issues',
        sequenceOrder: 8,
        estimatedHours: 120,
        dependencies: [6],
      },
      {
        title: 'Obtain Certifications (FCC, CE, etc)',
        description: 'Submit for regulatory testing, address findings, obtain certifications',
        sequenceOrder: 9,
        estimatedHours: 80,
        dependencies: [7],
      },
      {
        title: 'Complete Production Validation (PVT)',
        description: 'Build first production run, validate manufacturing process, release to production',
        sequenceOrder: 10,
        estimatedHours: 100,
        dependencies: [7, 8],
      },
    ],
  },

  Admin: {
    id: 'admin-sequence-v1',
    function: 'Admin',
    title: 'Administrative & Legal Setup',
    description: 'Establish corporate structure, compliance, and operational foundation',
    isSystem: true,
    createdAt: new Date().toISOString(),
    items: [
      {
        title: 'Incorporate Company',
        description: 'File Delaware C-Corp, obtain EIN, set up registered agent',
        sequenceOrder: 1,
        estimatedHours: 8,
      },
      {
        title: 'Set Up Cap Table & Equity',
        description: 'Configure Carta, issue founder shares, set up stock option plan',
        sequenceOrder: 2,
        estimatedHours: 12,
        dependencies: [0],
      },
      {
        title: 'Draft Core Legal Documents',
        description: 'Create employee handbook, IP assignment, NDA, contractor agreement templates',
        sequenceOrder: 3,
        estimatedHours: 20,
      },
      {
        title: 'Establish Banking & Financial Accounts',
        description: 'Open business checking, savings, credit card accounts',
        sequenceOrder: 4,
        estimatedHours: 8,
        dependencies: [0],
      },
      {
        title: 'Set Up Insurance Coverage',
        description: 'Obtain D&O, general liability, product liability, and workers comp insurance',
        sequenceOrder: 5,
        estimatedHours: 12,
      },
      {
        title: 'Create Compliance Calendar',
        description: 'Document all filing deadlines (taxes, annual reports, insurance renewals)',
        sequenceOrder: 6,
        estimatedHours: 8,
      },
      {
        title: 'Establish Data Room',
        description: 'Set up secure repository for all corporate documents, contracts, and IP',
        sequenceOrder: 7,
        estimatedHours: 12,
      },
      {
        title: 'File IP Protection (Trademarks/Patents)',
        description: 'File trademarks for brand, provisional patents for core technology',
        sequenceOrder: 8,
        estimatedHours: 30,
      },
      {
        title: 'Set Up HR Systems',
        description: 'Implement HRIS, onboarding workflows, and performance review process',
        sequenceOrder: 9,
        estimatedHours: 16,
      },
      {
        title: 'Establish Board Governance',
        description: 'Create board deck template, meeting cadence, voting procedures, and minutes process',
        sequenceOrder: 10,
        estimatedHours: 16,
        dependencies: [1],
      },
    ],
  },
};

// Helper function to generate workflow items from template
export function createWorkflowItemsFromTemplate(
  workspaceId: string,
  functionType: Function
): Omit<import('@/types').WorkflowItem, 'id' | 'createdAt' | 'updatedAt'>[] {
  const template = WORKFLOW_TEMPLATES[functionType];

  return template.items.map((item, index) => ({
    workspaceId,
    function: functionType,
    title: item.title,
    description: item.description,
    sequenceOrder: item.sequenceOrder,
    status: 'suggested' as const,
    metadata: {
      estimatedHours: item.estimatedHours,
      dependencies: item.dependencies?.map((depIndex) => template.items[depIndex].title),
    },
  }));
}
