import type { StartupChecklistItem } from '@/types';

export const STARTUP_PACK_CHECKLISTS: StartupChecklistItem[] = [
  // ==================== INCORPORATION ====================
  {
    id: 'inc-1',
    sectionId: 'incorporation',
    title: 'Check company name availability',
    description: 'Search Companies House to ensure your desired name is available and not too similar to existing companies.',
    priority: 'critical',
    estimatedHours: 0.5,
    ownerRoleHint: 'Founder',
    order: 1,
    links: [
      { label: 'Companies House Search', url: 'https://find-and-update.company-information.service.gov.uk/' },
    ],
  },
  {
    id: 'inc-2',
    sectionId: 'incorporation',
    title: 'Choose SIC code(s)',
    description: 'Select Standard Industrial Classification codes that describe your business activities.',
    priority: 'high',
    estimatedHours: 0.5,
    ownerRoleHint: 'Founder',
    order: 2,
    links: [
      { label: 'SIC Code Search', url: 'https://resources.companieshouse.gov.uk/sic/' },
    ],
  },
  {
    id: 'inc-3',
    sectionId: 'incorporation',
    title: 'Decide on registered office address',
    description: 'Choose a UK address for official correspondence. Can be your home, office, or a registered agent.',
    priority: 'high',
    estimatedHours: 0.5,
    ownerRoleHint: 'Founder',
    order: 3,
  },
  {
    id: 'inc-4',
    sectionId: 'incorporation',
    title: 'Prepare director and shareholder details',
    description: 'Gather full names, addresses, dates of birth, and nationality for all directors and shareholders.',
    priority: 'high',
    estimatedHours: 0.5,
    ownerRoleHint: 'Founder',
    order: 4,
  },
  {
    id: 'inc-5',
    sectionId: 'incorporation',
    title: 'Decide on initial share capital',
    description: 'Determine number of shares and nominal value. Common: 100-10,000 shares at £0.01-£1 each.',
    priority: 'high',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 5,
    templateIds: ['tpl-cap-table'],
  },
  {
    id: 'inc-6',
    sectionId: 'incorporation',
    title: 'Incorporate at Companies House',
    description: 'Submit incorporation application online. Standard service £12, same-day £30.',
    priority: 'critical',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 6,
    links: [
      { label: 'Companies House Web Incorporation', url: 'https://www.gov.uk/limited-company-formation' },
    ],
  },
  {
    id: 'inc-7',
    sectionId: 'incorporation',
    title: 'Receive and store Certificate of Incorporation',
    description: 'Save your Certificate of Incorporation and company number securely.',
    priority: 'high',
    estimatedHours: 0.25,
    ownerRoleHint: 'Founder',
    order: 7,
  },
  {
    id: 'inc-8',
    sectionId: 'incorporation',
    title: 'Register for Corporation Tax with HMRC',
    description: 'Must be done within 3 months of starting to trade.',
    priority: 'critical',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    defaultDueDays: 90,
    order: 8,
    links: [
      { label: 'HMRC Corporation Tax Registration', url: 'https://www.gov.uk/limited-company-formation/set-up-your-company-for-corporation-tax' },
    ],
  },
  {
    id: 'inc-9',
    sectionId: 'incorporation',
    title: 'Set up PSC register',
    description: 'Create and maintain a register of People with Significant Control.',
    priority: 'high',
    estimatedHours: 0.5,
    ownerRoleHint: 'Founder',
    order: 9,
  },

  // ==================== SHARE STRUCTURE ====================
  {
    id: 'shares-1',
    sectionId: 'share-structure',
    title: 'Agree founder equity split',
    description: 'Discuss and agree on ownership percentages with all co-founders.',
    priority: 'critical',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 1,
    notes: 'This conversation is crucial. Document the reasoning behind the split.',
  },
  {
    id: 'shares-2',
    sectionId: 'share-structure',
    title: 'Create initial cap table',
    description: 'Document the share ownership structure in a spreadsheet.',
    priority: 'high',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 2,
    templateIds: ['tpl-cap-table'],
  },
  {
    id: 'shares-3',
    sectionId: 'share-structure',
    title: 'Decide on vesting schedule',
    description: 'Agree founder vesting terms. Standard: 4 years with 1-year cliff.',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 3,
    templateIds: ['tpl-vesting-memo'],
  },
  {
    id: 'shares-4',
    sectionId: 'share-structure',
    title: 'Plan option pool size',
    description: 'Decide how much equity to reserve for future employees. Typical: 10-15%.',
    priority: 'medium',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 4,
  },
  {
    id: 'shares-5',
    sectionId: 'share-structure',
    title: 'Issue share certificates',
    description: 'Create and distribute share certificates to all shareholders.',
    priority: 'medium',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 5,
  },

  // ==================== SEIS/EIS ====================
  {
    id: 'seis-1',
    sectionId: 'seis-eis',
    title: 'Check SEIS/EIS eligibility',
    description: 'Review HMRC criteria to confirm your company qualifies for SEIS and/or EIS.',
    priority: 'critical',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 1,
    links: [
      { label: 'HMRC SEIS Guidance', url: 'https://www.gov.uk/guidance/venture-capital-schemes-apply-for-the-seed-enterprise-investment-scheme' },
    ],
    templateIds: ['tpl-seis-checklist'],
  },
  {
    id: 'seis-2',
    sectionId: 'seis-eis',
    title: 'Engage accountant for SEIS/EIS advice',
    description: 'Get professional advice to ensure compliance with scheme requirements.',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 2,
    notes: 'SEIS/EIS rules are complex. Professional advice is strongly recommended.',
  },
  {
    id: 'seis-3',
    sectionId: 'seis-eis',
    title: 'Apply for Advance Assurance',
    description: 'Submit advance assurance application to HMRC before raising funds.',
    priority: 'high',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 3,
    links: [
      { label: 'Apply for Advance Assurance', url: 'https://www.gov.uk/guidance/venture-capital-schemes-apply-for-advance-assurance' },
    ],
    templateIds: ['tpl-advance-assurance-checklist'],
  },
  {
    id: 'seis-4',
    sectionId: 'seis-eis',
    title: 'Prepare investor one-pager on SEIS/EIS benefits',
    description: 'Create a simple document explaining tax benefits to potential investors.',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 4,
    templateIds: ['tpl-investor-seis-explainer'],
  },
  {
    id: 'seis-5',
    sectionId: 'seis-eis',
    title: 'File compliance statement after investment',
    description: 'Submit SEIS3/EIS3 forms to HMRC after receiving investment.',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 5,
    links: [
      { label: 'File SEIS/EIS Compliance', url: 'https://www.gov.uk/guidance/venture-capital-schemes-request-for-authority-to-issue-seis-eis-certificates' },
    ],
  },

  // ==================== SHAREHOLDERS AGREEMENT ====================
  {
    id: 'sha-1',
    sectionId: 'shareholders-agreement',
    title: 'Discuss key terms with co-founders',
    description: 'Agree on vesting, leaver provisions, reserved matters before involving lawyers.',
    priority: 'critical',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 1,
    templateIds: ['tpl-sha-term-checklist'],
  },
  {
    id: 'sha-2',
    sectionId: 'shareholders-agreement',
    title: 'Engage startup-experienced lawyer',
    description: 'Find a lawyer who specializes in startup documentation.',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 2,
  },
  {
    id: 'sha-3',
    sectionId: 'shareholders-agreement',
    title: 'Draft shareholders agreement',
    description: 'Work with lawyer to create the agreement based on agreed terms.',
    priority: 'critical',
    estimatedHours: 8,
    ownerRoleHint: 'Founder',
    order: 3,
    templateIds: ['tpl-sha-outline'],
  },
  {
    id: 'sha-4',
    sectionId: 'shareholders-agreement',
    title: 'Review and negotiate terms',
    description: 'All parties review the draft and negotiate any changes.',
    priority: 'high',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 4,
  },
  {
    id: 'sha-5',
    sectionId: 'shareholders-agreement',
    title: 'Sign and store shareholders agreement',
    description: 'Execute the agreement and store copies securely.',
    priority: 'critical',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 5,
  },

  // ==================== ARTICLES ====================
  {
    id: 'art-1',
    sectionId: 'articles',
    title: 'Review Model Articles requirements',
    description: 'Understand what Model Articles provide and identify any customization needs.',
    priority: 'high',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 1,
    links: [
      { label: 'Model Articles for Private Companies', url: 'https://www.gov.uk/guidance/model-articles-of-association-for-limited-companies' },
    ],
  },
  {
    id: 'art-2',
    sectionId: 'articles',
    title: 'Decide: Model Articles or Custom',
    description: 'Determine if you need custom articles for your share structure and governance.',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 2,
    templateIds: ['tpl-articles-customization-checklist'],
  },
  {
    id: 'art-3',
    sectionId: 'articles',
    title: 'Draft custom articles (if needed)',
    description: 'Work with lawyer to create bespoke articles if required.',
    priority: 'medium',
    estimatedHours: 8,
    ownerRoleHint: 'Founder',
    order: 3,
  },
  {
    id: 'art-4',
    sectionId: 'articles',
    title: 'File articles with Companies House',
    description: 'Ensure articles are filed as part of incorporation or as an update.',
    priority: 'high',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 4,
  },

  // ==================== FUNDRAISING ====================
  {
    id: 'fund-1',
    sectionId: 'fundraising',
    title: 'Create data room folder structure',
    description: 'Set up secure folders for all due diligence documents.',
    priority: 'critical',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 1,
    templateIds: ['tpl-data-room-index'],
  },
  {
    id: 'fund-2',
    sectionId: 'fundraising',
    title: 'Gather corporate documents for data room',
    description: 'Collect cert of incorporation, articles, SHA, cap table, board minutes.',
    priority: 'high',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 2,
  },
  {
    id: 'fund-3',
    sectionId: 'fundraising',
    title: 'Prepare financial model',
    description: 'Create 3-year projections with clear assumptions.',
    priority: 'high',
    estimatedHours: 8,
    ownerRoleHint: 'Founder',
    order: 3,
  },
  {
    id: 'fund-4',
    sectionId: 'fundraising',
    title: 'Build pitch deck',
    description: 'Create 10-15 slide deck covering problem, solution, market, team, ask.',
    priority: 'critical',
    estimatedHours: 16,
    ownerRoleHint: 'Founder',
    order: 4,
    templateIds: ['tpl-pitch-deck-outline'],
  },
  {
    id: 'fund-5',
    sectionId: 'fundraising',
    title: 'Research target investors',
    description: 'Build list of investors who fund your stage, sector, and geography.',
    priority: 'high',
    estimatedHours: 8,
    ownerRoleHint: 'Founder',
    order: 5,
  },
  {
    id: 'fund-6',
    sectionId: 'fundraising',
    title: 'Set up investor CRM/tracker',
    description: 'Create spreadsheet or use CRM to track investor outreach.',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 6,
  },
  {
    id: 'fund-7',
    sectionId: 'fundraising',
    title: 'Create investor update template',
    description: 'Design a monthly update format to keep investors engaged.',
    priority: 'low',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 7,
    templateIds: ['tpl-investor-update'],
  },

  // ==================== IP & TRADEMARKS ====================
  {
    id: 'ip-1',
    sectionId: 'ip-trademarks',
    title: 'Register primary domain name',
    description: 'Secure yourcompany.com and key alternative extensions.',
    priority: 'critical',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 1,
  },
  {
    id: 'ip-2',
    sectionId: 'ip-trademarks',
    title: 'Search UK trademark database',
    description: 'Check if your brand name is available for trademark registration.',
    priority: 'high',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 2,
    links: [
      { label: 'UK IPO Trademark Search', url: 'https://trademarks.ipo.gov.uk/ipo-tmtext' },
    ],
  },
  {
    id: 'ip-3',
    sectionId: 'ip-trademarks',
    title: 'Identify trademark classes needed',
    description: 'Determine which Nice Classification classes apply to your business.',
    priority: 'medium',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 3,
    links: [
      { label: 'Nice Classification Guide', url: 'https://www.gov.uk/government/publications/trade-mark-classification' },
    ],
  },
  {
    id: 'ip-4',
    sectionId: 'ip-trademarks',
    title: 'File trademark application',
    description: 'Submit UK trademark application (£170 first class, £50 each additional).',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 4,
    links: [
      { label: 'Apply for UK Trademark', url: 'https://www.gov.uk/how-to-register-a-trade-mark' },
    ],
    templateIds: ['tpl-trademark-filing-checklist'],
  },
  {
    id: 'ip-5',
    sectionId: 'ip-trademarks',
    title: 'Document brand assets',
    description: 'Create inventory of logos, colors, fonts for brand consistency.',
    priority: 'low',
    estimatedHours: 2,
    ownerRoleHint: 'Apprentice',
    order: 5,
    templateIds: ['tpl-brand-assets-checklist'],
  },

  // ==================== BANKING & TAX ====================
  {
    id: 'bank-1',
    sectionId: 'banking-tax',
    title: 'Open business bank account',
    description: 'Set up dedicated business banking (Tide, Starling, or traditional bank).',
    priority: 'critical',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 1,
  },
  {
    id: 'bank-2',
    sectionId: 'banking-tax',
    title: 'Set up accounting software',
    description: 'Configure Xero, FreeAgent, or QuickBooks and connect to bank.',
    priority: 'critical',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 2,
    templateIds: ['tpl-bookkeeping-categories'],
  },
  {
    id: 'bank-3',
    sectionId: 'banking-tax',
    title: 'Decide on accounting year end',
    description: 'Choose your accounting reference date (default: month of incorporation).',
    priority: 'high',
    estimatedHours: 0.5,
    ownerRoleHint: 'Founder',
    order: 3,
  },
  {
    id: 'bank-4',
    sectionId: 'banking-tax',
    title: 'Engage an accountant',
    description: 'Find a startup-friendly accountant for tax filings and advice.',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 4,
  },
  {
    id: 'bank-5',
    sectionId: 'banking-tax',
    title: 'Consider VAT registration',
    description: 'Evaluate whether voluntary VAT registration makes sense.',
    priority: 'medium',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 5,
    links: [
      { label: 'VAT Registration Guide', url: 'https://www.gov.uk/vat-registration' },
    ],
  },
  {
    id: 'bank-6',
    sectionId: 'banking-tax',
    title: 'Set up PAYE (if hiring employees)',
    description: 'Register for PAYE before first payroll run.',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 6,
    links: [
      { label: 'Register for PAYE', url: 'https://www.gov.uk/register-employer' },
    ],
  },

  // ==================== EMPLOYMENT ====================
  {
    id: 'emp-1',
    sectionId: 'employment',
    title: 'Create founder IP assignment',
    description: 'Ensure all founders have assigned IP rights to the company.',
    priority: 'critical',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 1,
    templateIds: ['tpl-ip-assignment-checklist'],
  },
  {
    id: 'emp-2',
    sectionId: 'employment',
    title: 'Draft employment contract template',
    description: 'Create standard employment contract for future hires.',
    priority: 'medium',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 2,
  },
  {
    id: 'emp-3',
    sectionId: 'employment',
    title: 'Draft contractor agreement template',
    description: 'Create standard consultancy agreement for contractors.',
    priority: 'medium',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 3,
    templateIds: ['tpl-contractor-onboarding-checklist'],
  },
  {
    id: 'emp-4',
    sectionId: 'employment',
    title: 'Set up pension scheme (if hiring)',
    description: 'Register for auto-enrollment pension before first employee.',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 4,
    links: [
      { label: 'Workplace Pensions', url: 'https://www.gov.uk/workplace-pensions-employers' },
    ],
  },
  {
    id: 'emp-5',
    sectionId: 'employment',
    title: 'Create confidentiality agreement template',
    description: 'Draft NDA for employees, contractors, and advisors.',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 5,
  },

  // ==================== OPERATIONS ====================
  {
    id: 'ops-1',
    sectionId: 'operations',
    title: 'Set up team communication tools',
    description: 'Configure Slack/Teams and email (Google Workspace/M365).',
    priority: 'high',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 1,
  },
  {
    id: 'ops-2',
    sectionId: 'operations',
    title: 'Set up password manager',
    description: 'Deploy 1Password or Bitwarden for the team.',
    priority: 'high',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 2,
    templateIds: ['tpl-security-checklist'],
  },
  {
    id: 'ops-3',
    sectionId: 'operations',
    title: 'Enable 2FA on critical accounts',
    description: 'Turn on two-factor authentication for email, banking, code repos.',
    priority: 'critical',
    estimatedHours: 1,
    ownerRoleHint: 'Founder',
    order: 3,
  },
  {
    id: 'ops-4',
    sectionId: 'operations',
    title: 'Create privacy policy',
    description: 'Draft and publish privacy policy for your website/app.',
    priority: 'high',
    estimatedHours: 4,
    ownerRoleHint: 'Founder',
    order: 4,
    links: [
      { label: 'ICO Privacy Notice Guide', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/individual-rights/the-right-to-be-informed/' },
    ],
  },
  {
    id: 'ops-5',
    sectionId: 'operations',
    title: 'Set up basic SOPs',
    description: 'Document key processes: onboarding, offboarding, support.',
    priority: 'low',
    estimatedHours: 4,
    ownerRoleHint: 'Apprentice',
    order: 5,
    templateIds: ['tpl-sop-starter'],
  },
  {
    id: 'ops-6',
    sectionId: 'operations',
    title: 'Configure backup systems',
    description: 'Ensure code, documents, and data are backed up regularly.',
    priority: 'medium',
    estimatedHours: 2,
    ownerRoleHint: 'Founder',
    order: 6,
  },
];

export function getChecklistBySectionId(sectionId: string): StartupChecklistItem[] {
  return STARTUP_PACK_CHECKLISTS
    .filter(c => c.sectionId === sectionId)
    .sort((a, b) => a.order - b.order);
}

export function getChecklistItemById(id: string): StartupChecklistItem | undefined {
  return STARTUP_PACK_CHECKLISTS.find(c => c.id === id);
}

export function getCriticalItems(): StartupChecklistItem[] {
  return STARTUP_PACK_CHECKLISTS.filter(c => c.priority === 'critical');
}

export function getTotalEstimatedHours(): number {
  return STARTUP_PACK_CHECKLISTS.reduce((sum, c) => sum + (c.estimatedHours ?? 0), 0);
}
